### ISSUE TITLE
False positive on redirect_to + strong parameters

### ISSUE THREAD

**Issue by JasonBarnabe** [presidentbeef/brakeman#1000]
```ruby
redirect_to params.permit(:page, :per_page, :site, :sort, :q), status: 301
```
gives `Possible unprotected redirect`. As long as the whitelisted parameters aren't one of the [special ones](http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for), this is fine, right?

**Comment by presidentbeef** [comment]
#1000! :tada: 

Yes, I agree this is safe and can be fixed.
