### ISSUE TITLE
False Positive - redirect_to

### ISSUE THREAD

**Issue by duduribeiro** [presidentbeef/brakeman#1006]
Hi, just to check if this is a false positive, or a correct warning.

When I have this code:

```
  def create
    @influencer = Influencer.new(influencer_params)
    if @influencer.save
      redirect_to @influencer, notice: 'Influencer was successfully created.'
    else
      @influencer.build_nested_models
      render :new
    end
  end
```

it passes on brakeman.. 

But when I have this one:

```
  def create
    @influencer = Influencer.new(influencer_params).save_and_get_informations

    if @influencer.valid?
      redirect_to @influencer, notice: 'Influencer was successfully created.'
    else
      @influencer.build_nested_models
      render :new
    end
  end
```
and the `save_and_get_informations` method:
```
  def save_and_get_informations
    save && UpdateInfluencersSourcesJob.perform_later(id)
    self
  end
```

it fails for me:

![image](https://cloud.githubusercontent.com/assets/771411/23095810/4a812bba-f5f7-11e6-8c7b-d2de7dfcbbf4.png)

So, is it a false positive or a correct warning? (I'm using brakeman 3.4.1)

Thanks a lot

🍻

**Comment by presidentbeef** [comment]
Hi Kadu,

It's a false positive. Brakeman doesn't know that your `save_and_get_informations` method is returning the `Influencer` instance.
