### ISSUE TITLE
False positive CSRF protection in APIs

### ISSUE THREAD

**Issue by fny** [presidentbeef/brakeman#1020]
Right now we're using `protect_from_forgery with: :null_session` for our API as recommended by Rails, but we're seeing the following warning:

    | Medium     | Api::V1::ApiApplicationController | Cross-Site Request Forgery | protect_from_forgery should be configured with 'with: :exception' near line 8: protect_from_fo>>
    | Medium     | ErrorsController                  | Cross-Site Request Forgery | protect_from_forgery should be configured with 'with: :exception' near line 4: protect_from_fo>>

Not a big deal really. I'd just ignore the message, but our ISO got cranky about it.

**Comment by SergeyKutsko** [comment]
Is it challenge for you to remove that warning and protect API?

**Comment by presidentbeef** [comment]
@fny Are those controllers inheriting from `ActionController::API`?

**Comment by fny** [comment]
Nope. ActionController::Base, let me check if that fixes things.

**Comment by presidentbeef** [comment]
Did it?

**Comment by fny** [comment]
For posterity's sake, I'll note that yes it did. Sorry for the late reply!

**Comment by Schwad** [comment]
Came here with same issue. Thanks for solving!
