### ISSUE TITLE
Hitting too many open files

### ISSUE THREAD

**Issue by jjoos** [presidentbeef/brakeman#1021]
We're occasionally hitting too many files open issues with brakeman (we're evaluating pro). This is the stack trace we're getting.
```
Errno::EMFILE: Too many open files @ rb_sysopen - <redacted project file name>
  /Users/name/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/brakeman-pro-3.5.0/lib/brakeman/app_tree.rb:79:in `read'
  /Users/name/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/brakeman-pro-3.5.0/lib/brakeman/app_tree.rb:79:in `read_path'
  /Users/name/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/brakeman-pro-3.5.0/lib/brakeman/file_parser.rb:61:in `read_path'
  /Users/name/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/brakeman-pro-3.5.0/lib/brakeman/file_parser.rb:32:in `block (2 levels) in read_files'
```
As a workaround we could increase the open file limits, but it would even be better when brakeman handles this graciously.

**Comment by presidentbeef** [comment]
Ah, thank you for reporting this issue. It will be fixed in the next release.

Please report Pro issues to support@brakemanpro.com. Thanks!

**Comment by presidentbeef** [comment]
@jjoos this is fixed in the latest release! It is limited to 100 parsing threads, which I trust is below your limit.
