### ISSUE TITLE
False positive - LinkToHref with new record

### ISSUE THREAD

**Issue by JasonBarnabe** [presidentbeef/brakeman#1022]
In this code, `parent` has many `contacts`, and the inverse relation is called `contactable`.
```ruby
  def create
    @contact = parent.contacts.build(params[:contact])
  end
```
```ruby
= link_to "#{@contact.contactable.name} (##{@contact.contactable.id})", @contact.contactable
```
> Unsafe parameter value in link_to href near line 31: link_to("#{parent.contacts.build(params[:contact]).contactable.name} (##{parent.contacts.build(params[:contact]).contactable.id})", parent.contacts.build(params[:contact]).contactable)

**Comment by presidentbeef** [comment]
Hi Jason,

Unfortunately Brakeman doesn't know what `parent.contacts.build` does. However, even if it did, Brakeman isn't going to know what `contactable` is so it would still warn. Sadly you will need to just ignore this one.
