### ISSUE TITLE
NoMethodError exception using --compare flag

### ISSUE THREAD

**Issue by anthlam** [presidentbeef/brakeman#1023]
version = 3.6.0

When using the `--compare FILE` option, the following exception occurs (included some of the debug output that preceded the exception for context)

```
Checking users/setup for XSS
Checks finished, collecting results...
Filtering warnings...
[Notice] Using '/Users/anthlam/Projects/TTM/apangea/config/brakeman.ignore' to filter warnings
Generating report...
Comparison saved in 'brakeman-diff-output.json'
/Users/anthlam/.rvm/gems/ruby-2.2.4@apangea/gems/brakeman-3.6.0/bin/brakeman:95:in `<top (required)>': undefined method `options' for nil:NilClass (NoMethodError)
        from /Users/anthlam/.rvm/gems/ruby-2.2.4@apangea/bin/brakeman:22:in `load'
        from /Users/anthlam/.rvm/gems/ruby-2.2.4@apangea/bin/brakeman:22:in `<main>'
        from /Users/anthlam/.rvm/gems/ruby-2.2.4@apangea/bin/ruby_executable_hooks:15:in `eval'
        from /Users/anthlam/.rvm/gems/ruby-2.2.4@apangea/bin/ruby_executable_hooks:15:in `<main>'

```

steps taken:
1. run `brakeman -o brakeman-output.json`
2. run `brakeman --compare brakeman-output.json -o brakeman-diff-output.json`

The compare scan still completes, and the compare output file is successfully generated.

I think this might be caused by the additions for `--exit-on-error`.  The `--compare` flag causes brakeman to enter the `if` block of [this conditional](https://github.com/presidentbeef/brakeman/blob/master/bin/brakeman#L67). `tracker`, which is being used [here](https://github.com/presidentbeef/brakeman/blob/master/bin/brakeman#L95), outside of that conditional, is only set on the `else` block.

**Comment by anthlam** [comment]
Awesome! Thanks for the quick fix!

**Comment by chazchandler** [comment]
can you release a fix as v3.6.1?

**Comment by presidentbeef** [comment]
@chazchandler sure, probably tomorrow.

**Comment by presidentbeef** [comment]
@chazchandler http://brakemanscanner.org/blog/2017/03/24/brakeman-3-dot-6-1-released/

**Comment by chazchandler** [comment]
Thanks!
