### ISSUE TITLE
do not ship bundle folder ?

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#1026]
this seems odd ... is that intentional ? ... basically shipping 1M worth of other gems along ...
```
gem unpack vendor/cache/brakeman-3.6.1.gem
du -skx brakeman-3.6.1/bundle/*
4	brakeman-3.6.1/bundle/load.rb
10632	brakeman-3.6.1/bundle/ruby
```

**Comment by presidentbeef** [comment]
Yes, it is intentional. See http://blog.presidentbeef.com/blog/2016/08/09/bundling-gem-dependencies-inside-ruby-gems/

If you don't want the bundled gems, use `brakeman-lib` or `brakeman-min`.
