### ISSUE TITLE
False positive - unprotected redirect on model attribute

### ISSUE THREAD

**Issue by JasonBarnabe** [presidentbeef/brakeman#1027]
```ruby
@company = Company.find_by(permalink: params[:company_id])
@sales_order = @company.company_sales_orders.find(params[:company_sales_order_id])
@document = @sales_order.line_items[params[:id].to_i-1].document
redirect_to @document.url
```
> Possible unprotected redirect near line 12: redirect_to(Company.find_by(:permalink => params[:company_id]).company_sales_orders.find(params[:company_sales_order_id]).line_items[(params[:id].to_i - 1)].document.url)

I assume this complains because it thinks I'm redirecting to a request parameter.

**Comment by presidentbeef** [comment]
Hi Jason,

Apologies for the delay.

Brakeman is warning about the `.url` call which appears to return a database value (as the warning says: `model attribute`). Brakeman treats the database with suspicion, since the values could come from anywhere.
