### ISSUE TITLE
False positive - Redirect using to_unsafe_hash method

### ISSUE THREAD

**Issue by mario-areias** [presidentbeef/brakeman#1028]
`redirect_to(params.to_unsafe_hash.merge(:only_path => true, :display => nil))`

Brakeman is flagging this as a vulnerability: `Possible unprotected redirect`.
 
I believe this a false positive though, due to the `:only_path` parameter. I have a PR with a possible fix for that. Feel free to close both issue and PR if they do not apply (I am not very proficient with Ruby).

**Comment by presidentbeef** [comment]
Hi Mário,

Thank you for reporting/addressing this. I apologize for the delay in responding. Things are a little busy on my end but I'll try to review this soon.

**Comment by mario-areias** [comment]
Hi @presidentbeef,

No problem at all. Just let me know if I am in the right direction, since this is my first PR to brakeman :smile:

**Comment by mario-areias** [comment]
Hi @presidentbeef,

Have you had the chance to look at that? Let me know if there is something else I need to fix to get that PR done :)
