### ISSUE TITLE
.exists? SQL Injection fixed by .to_i but not .to_s

### ISSUE THREAD

**Issue by oehlschl** [presidentbeef/brakeman#1045]
https://rails-sqli.org/rails4#exists states that "[converting] user input to a string or integer if using it as the primary key in `.exists?`" is an injection-safe solution to the following pattern: 

```
# bad
User.exists? params[:id] 
```

Brakeman expects either hash conditions or integer conversion to escape this:

```
# good
User.exists? params[:id].to_i
```

Although converting to an integer is the right answer for most cases, `.to_s` is required in other equally valid cases, for example if `.find` has been overridden by a slugging gem or if the primary key is a string. Currently, however, Brakeman still fails with the `.to_s` version but should pass in that case as well.

```
# should also be good
User.exists? params[:id].to_s
```

UPDATE:
rails 4.2.8
brakeman 3.6.1

**Comment by presidentbeef** [comment]
Haha, using my own words against me :sweat_smile:

**Comment by oehlschl** [comment]
Haha, I had no idea. Thanks for the quick fix! 👍
