### ISSUE TITLE
Brakeman reports an exception during CheckSessionSettings

### ISSUE THREAD

**Issue by halostatue** [presidentbeef/brakeman#1046]
During `CheckSessionSettings`, an exception is thrown while checking my application’s `config/secrets.yml`:

`(<unknown>): could not find expected ':' while scanning a simple key at line 20 column 1	
…/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `parse'`

This is specifically because of the structure of my `config/secrets.yml`:

```yaml
development:
  secret_key_base: VALUE
test:
  secret_key_base: VALUE

# This must not be indented for it to work.
<% if Rails.root.join('config/ansible/secrets.yml').exist? %>
<%= Rails.root.join('config/ansible/secrets.yml').read %>
<% end %>
<% if Rails.root.join('config/local/secrets.yml').exist? %>
<%= Rails.root.join('config/local/secrets.yml').read %>
<% end %>
```

Basically, I use install-time generated files in `config/ansible/secrets.yml` and `config/local/secrets.yml` (both directories excluded from git) and use the fact that Rails loads `config/*.yml` through ERB pretty much by default to paste the included files into the default file.

YAML doesn’t have includes as a concept (this is probably good; it’s got enough insecurity in design as it is), and Brakeman doesn’t parse ERB by default (this is also probably a good thing as it’s a static analyzer). However, this *crashes* the `CheckSessionSettings` code (because it’s not a complete YAML file until the ERB is parsed), and that’s probably not good, either. (This probably doesn’t matter when ERB is used by people who have to build Heroku-factor applications as YAML doesn’t care whether a key is `foo` or `<%= ENV['foo'] %>`.)

For the moment, I’m skipping `CheckSessionSettings` in my code, but this should be on the radar as an oddity.

[Edit: Originally reported against `CheckYAMLParsing`; that’s wrong.]

**Comment by presidentbeef** [comment]
Hi Austin,

Thank you for bringing this up. A similar issue has come up before (in that case SafeYAML was being strict and rejecting unsafe YAML). The exception should definitely be handled.
