### ISSUE TITLE
False positive dangerous send when using white list

### ISSUE THREAD

**Issue by obfuscoder** [presidentbeef/brakeman#1057]
I use an early exit clause in my method whenever a parameter is not in the allowed whitelist before I try to use it in a method send call:

```ruby
  def login
    goto = params[:goto]
    event = params[:event]
    return redirect_to user_path unless %w[comment subscribe].include?(goto)
    # additionally check event
    redirect_to send("#{goto}_event_path", event)
  end
```

This is still reported by brakeman as dangerous send. PR #640 does not cover this.

I know that I can use an if statement to let brakeman detect the white list exception. However as I do need to check the event additionally, this is not covered:

```ruby
  def login
    goto = params[:goto]
    event = params[:event]
    if %w[comment subscribe].include?(goto) && event.present?
      redirect_to send("#{goto}_event_path", event)
    else
      redirect_to user_path
    end
  end
```

To let brakeman detect the whitelist, I would need to separate the conditions for white list and event checks:

```ruby
  def login
    goto = params[:goto]
    event = params[:event]
    if %w[comment subscribe].include?(goto)
      if event.present?
        return redirect_to send("#{goto}_event_path", event)
      end
    end
    redirect_to user_path
  end
```

This is pretty ugly. So I would like to ask to let brakeman detecting early exit whitelisting.

**Comment by presidentbeef** [comment]
I agree...I have an idea of how to do this.
