### ISSUE TITLE
Unprotected redirect not detected if model variable is set outside method

### ISSUE THREAD

**Issue by oboxodo** [presidentbeef/brakeman#1058]
I have a few different controllers which end up redirecting to download a PDF file from AWS S3. These files were uploaded to S3 using Carrierwave with the Fog adapter.

The problem is Brakeman would detect a "Possible unprotected redirect" error in some of them but not all of them. Ultimately I noticed that the model variable was being set from the same method in those where Brakeman was detecting the issue.

So I came up with this minimal example which shows the issue:

```ruby
# Brakeman complains about "Possible unprotected redirect" with this.
class DocumentsController < ApplicationController
  def show
    @document = Document.find(params[:id])
    redirect_to @document.flyer_pdf.url
  end
end

# Brakeman does NOT complain in this example.
class DocumentsController < ApplicationController
  def show
    set_document
    redirect_to @document.flyer_pdf.url
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end
end
```

Is this expected behavior?

**Comment by oboxodo** [comment]
I should add that if instead of calling `set_document` from the `show` method I set it as a `before_action`, then Brakeman DOES complain. So it will detect the variable being a model instance if set on a `before_action`, but not if it's set on a method called directly.

**Comment by presidentbeef** [comment]
Hi Diego,

Yes, this is expected due to the way Brakeman works. In general, Brakeman does not do full interprocedural analysis, but it does go through `before_action`s.

**Comment by oboxodo** [comment]
I guess I can use this as a "trick" to avoid false positives without having to explicitly add it to the ignores file. 😕
