### ISSUE TITLE
Parse error with rails4 option

### ISSUE THREAD

**Issue by kaizencodes** [presidentbeef/brakeman#1059]
Using the rails4 option results in `parse error on value ":" (tCOLON)` for every `<%= form_for :something do %>`

I've tested out with `erubis -x file_name.html.erb | ruby -c`
```
-:19: syntax error, unexpected ')'
...for model do |f| ).to_s; _buf << '
```

Seems to be a problem with erb. What is strange however, that leaving out the `rails4` option makes Brakeman pass.

**Comment by presidentbeef** [comment]
Yes, Rails does its own ERB stuff and Brakeman tries to match it. Is it actually a Rails 4 application you are scanning?

**Comment by kaizencodes** [comment]
Yes it is 4.2.8.

Are there any difference in how brakeman runs with rails4 option vs auto detect?

**Comment by presidentbeef** [comment]
You saw this in Brakeman's output?

```
[Notice] Detected Rails 4 application
```

and what was the version reported as in the Brakeman report?

**Comment by kaizencodes** [comment]
`[Notice] Detected Rails 4 application` yes

`"rails_version": "4.2.8",`

**Comment by presidentbeef** [comment]
Pretty weird... I'm not seeing any reason why that would happen. As far as I can tell there is no difference between using `--rails4` or the auto-detect (and there shouldn't be).

You are also seeing

```
[Notice] Escaping HTML by default
```

right?

I can't reproduce the issue, either. Can you provide a more complete ERB template to reproduce?

I don't suppose this is an open source application?

**Comment by kaizencodes** [comment]
It's closed source yes. but here is a simple reproduction on the same rails version [repo](https://github.com/kaizencodes/brakeman_test). 

I do see `[Notice] Escaping HTML by default` when it's autodetecting, however not when `:rails4: true`

**Comment by presidentbeef** [comment]
AH okay. The key bit of information was the option was set in a configuration file.
