### ISSUE TITLE
Document what types of errors Brakeman can catch

### ISSUE THREAD

**Issue by kevinburke** [presidentbeef/brakeman#1061]
I'm trying to find out what Brakeman actually _does_, e.g. the types of errors it can catch. I went to the homepage:

> Brakeman 3.6.2 Released

This is useful for learning what's new in 3.6.2 but not so helpful for figuring out what Brakeman does.

I went to the Documentation > Introduction:

```
Brakeman is a security scanner for Ruby on Rails applications.

Unlike many web security scanners, Brakeman looks at the source code of your application. This means you do not need to set up your whole application stack to use it.

Once Brakeman scans the application code, it produces a report of all security issues it has found.
```

This doesn't describe the actual checks done by Brakeman (nor does the rest of the page)

Running Brakeman:

```
The simplest way to get started with Brakeman is to just run it with no options in the root directory of your Rails application:

$ cd your_rails_app/
$ brakeman

This will scan the application in the current directory and output a report to the command line.

Alternatively, you can supply a path as an option to Brakeman:
```

Nothing on "Confidence Levels", "FAQ", either...

**Comment by kevinburke** [comment]
Ah, yes, that's it. Would be good if that page was easier to find!

**Comment by presidentbeef** [comment]
It's on http://brakemanscanner.org/docs/, must have just glanced over it.

**Comment by kevinburke** [comment]
Yes - I would argue that's a usability problem. The evidence is I tried to find the page and missed it; it's likely others did as well.

It would be great if there were more links to that page, probably from the homepage, the Github README or from the introduction.

https://www.nngroup.com/articles/information-scent/
https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/
