### ISSUE TITLE
brakeman -z not resulting in an error in bash script

### ISSUE THREAD

**Issue by greggawatt** [presidentbeef/brakeman#1071]
I'm attempting to setup brakeman on CircleCI with the following command:
`test:
  pre: 
    - case $CIRCLE_NODE_INDEX in 0) ./circle_scripts/security_scanning ;; esac:
        parallel: true`

which runs a script that contains: 
`bundle exec brakeman -z --ensure-latest --table-width 300 -w3`

but it doesn't produce an error when the script runs with errors or warnings. According to CircleCI it's still green.

Any ideas?

**Comment by presidentbeef** [comment]
Hi Greg,

Is `brakeman` the last line in your script? Have you tried simplifying your configuration to narrow down the problem?

Maybe just:

```
test:
  pre:
    -  ./circle_scripts/security_scanning
```
or even
```
test:
  pre:
    -  bundle exec brakeman -z --ensure-latest --table-width 300 -w3
```

`-z` is only for warnings. To change the exit code on errors, use `--exit-on-error`.

**Comment by greggawatt** [comment]
I got this working by simplifying my script. Thanks for the help!
