### ISSUE TITLE
Single instance line comments

### ISSUE THREAD

**Issue by pachonk** [presidentbeef/brakeman#1072]
Both a question and if the answer is no, a feature issue:
Does brakeman have the ability to do single line ignores like Rubocop has `# rubocop:disable LineLength`?

Use case:
I have a project that intentionally allows for a redirect from an admin submitted URI to an external server, but it's a "Possible unprotected redirect near"

I'd like to inline that ignore if it's possible, basically.

**Comment by pachonk** [comment]
I'd like to inline that ignore if it's possible, basically.

**Comment by presidentbeef** [comment]
Hi Alex,

You can use an "ignore file" to ignore false positives. Easiest way is to run `brakeman -I`.

See http://brakemanscanner.org/docs/ignoring_false_positives/ for more information.

Brakeman does not and will not support ignoring warnings via inline comments, sorry.

**Comment by pachonk** [comment]
Sounds good, thanks!

**Comment by pachonk** [comment]
@presidentbeef Is there a very particular reason Brakeman won't support it? Is it security implications? Is it the work to make it happen? If it's the work, I would be willing to do the legwork on making it happen.

**Comment by presidentbeef** [comment]
It's not the work. It's a mostly philosophical and somewhat technical decision.

If you want to read past discussion, [you can start here](https://github.com/presidentbeef/brakeman/pull/73#issuecomment-10527686).
