### ISSUE TITLE
False positive dangerous send when early-returning in unless block

### ISSUE THREAD

**Issue by saifulwebid** [presidentbeef/brakeman#1073]
This is an extension from #1057, but I early-return like this:

```ruby
bank_name = params_filename.first
unless Statistics::AdminWithdrawal::BANK_LIST.include?(bank_name)
  flash[:alert] = 'Invalid filename'
  redirect_to :back
  return
end

Statistics::AdminWithdrawal.send("export_#{bank_name}_inc!")
```

Brakeman reports this as a dangerous send, even if the `send()` method will only be called if it passes the `unless` block (because there's a `return` there as a final statement).

**Comment by presidentbeef** [comment]
Yes...it is possible to support this case (assuming Brakeman can find `Statistics::AdminWithdrawal::BANK_LIST`).

However, I do want to point out for future people looking at these issues that Brakeman is not going to support all possible instances of early returns.
