### ISSUE TITLE
encourage action_name and controller_name useage

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#1078]
using `params[:action]` or `params[:controller]` can be used to trick the app into doing something silly since they can be set via params, but developers often treat it as it it means 'current action' / 'current controller'

for example mentioned in http://guides.rubyonrails.org/action_controller_overview.html#routing-parameters

**Comment by presidentbeef** [comment]
I'm not sure what the danger is? When this came up before (#536) it was clear that it's not possible to set `params[:action]` or `params[:controller]` via query parameters.

**Comment by grosser** [comment]
yep ... never mind ... I though I saw this but unable to reproduce ... either on an older rails version or because I was messing with raw request.parameters ...
