### ISSUE TITLE
Dynamic render path false positive?

### ISSUE THREAD

**Issue by saifulwebid** [presidentbeef/brakeman#1082]
I got a code like this:

```ruby
allowed_pages = some_values_from_redis
view = params[:slug]

return redirect_to home_path, alert: 'Not allowed' unless allowed_pages.include?(view)
render view
```

Brakeman alerts me with high confidence that the render path contains parameter value. It's true, but I think because it is already guarded in line 4 above, it shouldn't complain.

**Comment by presidentbeef** [comment]
Hi saifulwebid,

Unfortunately, Brakeman can't know that `some_values_from_redis` is safe. I'm afraid you will just have to ignore this one.

Thanks!
