### ISSUE TITLE
Doesn't exit with non-zero error code on error by default

### ISSUE THREAD

**Issue by follmann** [presidentbeef/brakeman#1083]
Hi, I was wondering why brakeman doesn't exit with a non-zero exit code on errors by default. The documentation actually suggests that it should (brakeman options on the -z flag):

> Brakeman returns 0 as an exit code unless something went very wrong. To return an error code when warnings were found

Only when you use the recently introduced `--exit-on-error` it does, I thought very wrong means an error 😸 

Also vote for the -z flag as default (see #852)

Tested and verified on both v3.7.2 and v3.2.1

Thanks!

**Comment by presidentbeef** [comment]
"very wrong" was intended to mean "errors from which Brakeman does not recover."

I don't have a strong feeling on this one way or another, so I guess it can be the default to match `--exit-on-warn`.

**Comment by follmann** [comment]
Ah I see!

I think for all uses in scripts that rely on a meaningful exit code (which I guess is a 100% match e.g. in continuous integration setups) it would be the better default. People that just run brakeman to see the report won't be negatively affected by the change either.
