### ISSUE TITLE
Render dangerous cookies

### ISSUE THREAD

**Issue by slayer** [presidentbeef/brakeman#1090]
I have found serious vulnerability in my unreleased code:

```
   render inline: request.cookies["somecookie"]
```
It will be great to add checking for that case.
Thanks

**Comment by presidentbeef** [comment]
Hi Vlad,

Brakeman does check for this type of vulnerability, but it doesn't currently recognize `request.cookies`. If you changed it to

```ruby
   render inline: cookies["somecookie"]
```

you would see a warning.

**Comment by slayer** [comment]
Thanks
