### ISSUE TITLE
no block given (yield) While processing /path/to/file.rb

### ISSUE THREAD

**Issue by tsujigiri** [presidentbeef/brakeman#1092]
Hi,
I'm trying to run brakeman on one of our Rails apps after upgrading to the latest version (3.6.2). I get several parsing errors that say:
```
no block given (yield) While processing /path/to/file.rb
```
The location column points to:
```
/home/helge/.gem/ruby/2.3.0/gems/brakeman-min-3.6.2/lib/ruby_parser/bm_sexp.rb:127
```

One example of a file this happens with:
```rb
# frozen_string_literal: true

module HasMonthParam
  def month
    @month ||= begin
      Date.parse(params[:month])
    rescue
      Time.zone.today
    end.beginning_of_month
  end
end
```

**Comment by presidentbeef** [comment]
Hi Helge,

The latest version is actually 3.7.2.

I think you are seeing a conflict with one of the versions of ruby_parser/sexp_processor. Please upgrade to the latest version of Brakeman and see if that resolves the issue.

**Comment by tsujigiri** [comment]
Works! :+1:
