### ISSUE TITLE
`symbolize_keys` check gets confused on safe (?) model lookup

### ISSUE THREAD

**Issue by AndrewRayCode** [presidentbeef/brakeman#1096]
A line like this:

    Model.find(safe_params[:id]).attributes.symbolize_keys

Seems to confuse brakeman. It's creating keys out of model attributes, not user input.

I tried to make a one-off test case file for this but I realized brakeman looks for a whole Rails application.

**Comment by presidentbeef** [comment]
I agree. Will fix...my first attempt didn't work out.
