### ISSUE TITLE
Document --no-pager in 4.0.0 changes

### ISSUE THREAD

**Issue by bquorning** [presidentbeef/brakeman#1100]
Perhaps add a bit of documentation on the `--no-pager` option. When running Brakeman on CI, versions < 4 would exit with a status code, while version 4 will show its output in a pager (`less`?) and never exit.

The Pager was added in #1098.

**Comment by bquorning** [comment]
Perhaps update https://github.com/presidentbeef/brakeman/blob/master/OPTIONS.md as well.

**Comment by libo** [comment]
It looks like the breaking change is here:
https://github.com/presidentbeef/brakeman/blob/30c7e1cd108efeea2ee2a98f1af5d32954d182f8/lib/brakeman/options.rb#L243

And as @bquorning mention there is no mention of `--[no-]pager` in `OPTIONS.md` :-)

**Comment by presidentbeef** [comment]
@bquorning what CI are you using? I want to make sure it's supported with some changes I'm making.

**Comment by bquorning** [comment]
I’m using Travis.

**Comment by presidentbeef** [comment]
Thanks @bquorning.

I've released 4.0.1 with #1101 to automatically disable the pager for most popular CIs and tested on Travis.
[OPTIONS.md](https://github.com/presidentbeef/brakeman/blob/master/OPTIONS.md) was updated by @nikolalsvk. The website has been updated as well: https://brakemanscanner.org/docs/options/

Of course the release post has this info, too, but you beat me to it: https://brakemanscanner.org/blog/2017/09/25/brakeman-4-dot-0-released/

**Comment by daaain** [comment]
Just wanted to say I had this problem and adding `CI=true` to the command helped!

It took me a while to find the issue though, so leaving the error message here for search purposes: `press enter/return to continue or q to stop`.
