### ISSUE TITLE
"parse error on value" with brakeman 4.0

### ISSUE THREAD

**Issue by gravis** [presidentbeef/brakeman#1102]
Hi, 

After upgrading brakeman to 4.0.1 (from 3.7.2), I have 3 `parse error on value`, preventing from generating the final report.
The `Could not parse error`s are located:

https://github.com/gravis/active_admin/blob/master/app/views/active_admin/devise/passwords/edit.html.erb#L2
https://github.com/gravis/active_admin/blob/master/app/views/active_admin/devise/unlocks/new.html.erb#L3
https://github.com/gravis/active_admin/blob/master/app/views/active_admin/devise/shared/_links.erb#L4

<img width="1713" alt="screenshot 2017-09-26 08 25 59" src="https://user-images.githubusercontent.com/12752/30860205-589e4ea4-a294-11e7-8691-206d70efe99c.png">

Do I have to install an additional gem now, or something like that?

Thanks

**Comment by presidentbeef** [comment]
Hi Philippe,

This is actually not a new issue, I am seeing exactly the same errors with older version of Brakeman.

It appears to be linked to Brakeman not knowing what version of Rails is in use, so it's falling back on Rails 2.x behavior. If you pass any version number (e.g. `-3`, `-4`, `-5`) you should see those parse errors go away.

**Comment by gravis** [comment]
Thanks for your reply. I guess there's an issue with the rails detection code then.
If I pass `-3`, `-4`, or even `-5`, the parsing doesn't fail (like the 3.7 behaviour).
I have compared the output with these 3 variants, and there are exactly the same.
Is there a way to avoid passing an arbitrary rails version? I don't want to "hardcode" this in our scripts, it will lead to unexpected results in the future.
Thanks

**Comment by presidentbeef** [comment]
I don't know how we can detect the Rails version in use when your code does not depend on a specific version of Rails.

Here is the code where Brakeman attempts to guess the Rails version: https://github.com/presidentbeef/brakeman/blob/87e52206d725038c3cb2f34384241b6a7979d93c/lib/brakeman/scanner.rb#L154-L171

Open to suggestions.

From my testing this behavior did not change with the 4.0 release. I checked 3.7.2, 3.7.1, 3.7.0...all the same.

**Comment by gravis** [comment]
Ok, my bad, the errors were there with 3.7.x. They are just collapsed in the report, but now I have the same behaviour. I need to pass `--no-exit-on-error --no-exit-on-warn` as these are enabled by default in 4.0.
Now I have a different issue. Brakeman 4.0 is reporting less warnings than 3.7:

With 4.0.1:

```
== Warnings ==

Confidence: High
Category: Denial of Service
Check: SymbolDoS
Message: Symbol conversion from unsafe string (parameter value)
Code: request.query_parameters.except(:commit, :format).symbolize_keys
File: lib/active_admin/views/components/paginated_collection.rb
Line: 77
```

With 3.7.1:

```
+SECURITY WARNINGS+

+------------+-----------------------------------------+-----------------------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Confidence | Class                                   | Method                      | Warning Type         | Message                                                                                                                                                            |
+------------+-----------------------------------------+-----------------------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High       | ActiveAdmin::Views::PaginatedCollection | build_pagination            | Denial of Service    | Symbol conversion from unsafe string (parameter value) near line 77: +request.query_parameters.except(:commit, :format)+.symbolize_keys                            |
| Medium     | ActiveAdmin::Views::Pages::Index        | build_download_format_links | Cross Site Scripting | Unsafe parameter value in link_to href near line 61: link_to(format.to_s.upcase, { :format => format }.merge(+request.query_parameters+.except(:commit, :format))) |
| Medium     | ActiveAdmin::Views::PaginatedCollection | build_download_format_links | Cross Site Scripting | Unsafe parameter value in link_to href near line 83: link_to(format.to_s.upcase, { :format => format }.merge(+request.query_parameters+.except(:commit, :format))) |
+------------+-----------------------------------------+-----------------------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Is there a reason for that? Maybe a false positive being fixed in the latest version? 
Thanks

**Comment by presidentbeef** [comment]
Yes, those two are removed with #1093.

See https://github.com/presidentbeef/brakeman/releases for our release notes.
