### ISSUE TITLE
Link to Cross-Site Scripting does not work in HTML output

### ISSUE THREAD

**Issue by no-trick-pony** [presidentbeef/brakeman#1104]
The reason for this is that the link generated sends the browser to https://brakemanscanner.org/docs/warning_types/cross-site_scripting/ which is an unknown address. The correct address would be https://brakemanscanner.org/docs/warning_types/cross_site_scripting/

This issue was likely introduced in commit 1c4538dac323b03e29fc38be1449c54f5900b005 when all instances of "cross site scripting" were replaced by "cross-site scripting".
This might either be fixed in code, sending users to the correct address or by changing the web address to the new format (cross-site_scripting) and redirecting calls to the old cross_site_scripting (by all previous versions) to the new page.

**Comment by presidentbeef** [comment]
Fixed, thanks!
