### ISSUE TITLE
False positive - Unsafe reflection method constantize

### ISSUE THREAD

**Issue by mlh758** [presidentbeef/brakeman#1115]
I originally commented in #943 but it sounds like this might be slightly different so I opened a new issue as requested:

```
class Api::V0::SearchController < Api::V0::BaseController
  SEARCH_MODELS = Dir["#{Rails.root}/app/presenters/*.rb"]
                  .map { |f| f.split('/').last.chomp('_search_presenter.rb').classify }
                  .reject { |f| f == 'Base' }.freeze
  def search
    type = params[:type].classify
    raise NameError unless SEARCH_MODELS.include? type
    presenter = "#{type.pluralize}SearchPresenter".constantize
...
end
```

We have a white list of accepted models before triggering the `constantize` and we raise an exception if it isn't in the list.

**Comment by presidentbeef** [comment]
Thank you for opening a separate issue.

This code shouldn't warn (assuming you are using the latest version of Brakeman). It may be the case that Brakeman can't find the definition of `SEARCH_MODELS`.

I would need to see a more complete code example to figure out what's going wrong.

**Comment by mlh758** [comment]
I updated my original comment with the class declaration and the constant that is being referenced. It gets declared within the same class.

**Comment by presidentbeef** [comment]
Hi Michael,

Unfortunately there is no way for Brakeman to know that's a safe whitelist. I am afraid you need to [ignore it](https://brakemanscanner.org/docs/ignoring_false_positives/).
