### ISSUE TITLE
_faq_type_list.html.haml:4 :: parse error on value ")" (tRPAREN)

### ISSUE THREAD

**Issue by greggawatt** [presidentbeef/brakeman#1116]
Not sure what's going on here but brakeman is saying that it can't parse the following

```
.container
  = f.fields_for :insights do |i|
    = i.fields_for :faq_type do |ft|
    
```

**Comment by presidentbeef** [comment]
Hi Gregg,

There is nothing inside the second `do` block? What version of Haml are you using?

**Comment by presidentbeef** [comment]
Any further information here? I can't reproduce the issue, since the code provided is invalid AFAICT.
