### ISSUE TITLE
parse error on value ":" (tCOLON)

### ISSUE THREAD

**Issue by suryateja619** [presidentbeef/brakeman#1125]
Brakeman version: 4.0.1
Rails version: 4.2.8
Ruby version: 2.4.1

### Issue

I originally [posted](https://github.com/seattlerb/ruby_parser/issues/256) this out in ruby_parser but it doesn't seem like an issue with it. So, opening this issue in here.

I get an error from brakeman when I'm using the following code in a modal file.

```
enum view_level: [ :associates, :clients, :not_tracked ]
belongs_to :manager, class_name: 'Employee'
has_many :patients, through: :appointments
```

I have several errors in this file with similar syntax.

When I run `bundle exec brakeman` I get the following error.

` :: parse error on value ":" (tCOLON)`

**Comment by suryateja619** [comment]
Hi @presidentbeef,

The line number where the error was occurring was wrong. The actual code where it breaks is below.

```
searchable do
  text :venue { venues.pluck(:name) }
end
```

When I change this to actual `do end` block it doesn't throw the error.

```
searchable do
  text :venue do
    venues.pluck(:name)
  end
end
```

**Comment by presidentbeef** [comment]
Ah, okay. I think you are running into a syntax issue which existed briefly in Ruby 2.4.x: https://bugs.ruby-lang.org/issues/13939

I recommend not using this syntax, as it only works with a few specific versions of Ruby.

```
2.3.4 :001 > searchable do
2.3.4 :002 >       text :venue { venues.pluck(:name) }
2.3.4 :003?>   end
SyntaxError: (irb):2: syntax error, unexpected '{', expecting keyword_end
  text :venue { venues.pluck(:name) }
               ^
(irb):2: syntax error, unexpected '}', expecting keyword_end
	from /home/justin/.rvm/rubies/ruby-2.3.4/bin/irb:11:in `<main>'
2.3.4 :004 > 
```
```
2.5.0-preview1 :001 > searchable do
2.5.0-preview1 :002 >       text :venue { venues.pluck(:name) }
2.5.0-preview1 :003?>   end
SyntaxError: (irb):2: syntax error, unexpected '{', expecting keyword_end
  text :venue { venues.pluck(:name) }
              ^
(irb):2: syntax error, unexpected '}', expecting end-of-input
... :venue { venues.pluck(:name) }
...                              ^
	from /home/justin/.rvm/rubies/ruby-2.5.0-preview1/bin/irb:11:in `<main>'
```
```
2.4.0 :001 > searchable do
2.4.0 :002 >       text :venue { venues.pluck(:name) }
2.4.0 :003?>   end
NoMethodError: undefined method `searchable' for main:Object
	from (irb):1
	from /home/justin/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```
