### ISSUE TITLE
-:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input ...cal/rvm/gems/ruby-2.3.0@saasapp/gems/figaro-1.1.1/lib/figaro...

### ISSUE THREAD

**Issue by Zacstar** [presidentbeef/brakeman#1131]
// Instructions:
// 
// - Please read carefully
// - Please delete anything in this template that is irrelevant to your issue
//   (including these directions)

### Background

Brakeman version: ?
Rails version: ?
Ruby version: ?

Link to Rails application code: ?

### Issue

// What problem are you seeing? Consult the relevant section below if possible.

#### False Positive

*Full* warning from Brakeman: `?`

Relevant code:

```ruby
?
```

_Why might this be a false positive?_

#### Parse Error

// Consult https://brakemanscanner.org/docs/troubleshooting/parse_errors/ first
// Note that (most) parsing errors are from the ruby_parser library, not Brakeman itself

Minimal example that does not parse:

```ruby
?
```

#### Other Error

// Please run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
when i tried to run command   rails generate migration AddStripeCustomerTokenToUsers 
```

#### Hanging or **Slowness**

// Consult https://brakemanscanner.org/docs/troubleshooting/hanging/ first

// Please run Brakeman with `--debug` to see the file that is causing the issue.

Link to relevant code: ?

Code example:

```ruby
?
``` 

#### My Issue is Completely Different

// Okay! Please provide as much detail as possible

[](url)

**Comment by presidentbeef** [comment]
Please open a proper issue, I have no idea what you are trying to say. Brakeman doesn't run when you run `rails generate ...`
