### ISSUE TITLE
XSS False Positive: Incorrectly identifying class as a Model

### ISSUE THREAD

**Issue by mltsy** [presidentbeef/brakeman#1154]
### Background

Brakeman version: 4.0.1
Rails version: 5.1.4
Ruby version: 2.4.1

#### False Positive

*Full* warning from Brakeman:
```
Confidence: Weak
Category: Cross-Site Scripting
Check: LinkToHref
Message: Potentially unsafe model attribute in link_to href
Code: link_to((Unresolved Model).new.primary_link_text, (Unresolved Model).new.primary_url, :class => "project-url", :target => "_blank")
File: app/views/projects/_project_card.html.erb
Line: 16
```

Relevant code:

```ruby
# In Controller:
@presenters = cloud.projects.map { |p| ProjectPresenter.new p }
# In View: 
render partial: 'project_card', collection: @presenters, as: :project
# In Partial:
link_to project.primary_link_text, project.primary_url, class: 'project-url', target: '_blank'
```

_Why might this be a false positive?_

ProjectPresenter has a method that grabs `project.domain` and prepends the correct protocol.  It seems that Brakeman is incorrectly identifying ProjectPresenter as a model, when it's not (it's in the `presenters` directory, not under `models`) - is there any way to mark this as not a model?

**Comment by presidentbeef** [comment]
Unfortunately, Brakeman isn't even seeing `ProjectPresenter` in this case (hard to tell why from the code you've provided), that's why it shows `Unresolved Model`.

Given this is a `weak` confidence warning, I suggest [ignoring it](https://brakemanscanner.org/docs/ignoring_false_positives/).
