### ISSUE TITLE
Wrong warning filename/line format

### ISSUE THREAD

**Issue by Frexuz** [presidentbeef/brakeman#1166]
### Background

Brakeman version: 3.6.2
Rails version: 5.1.1
Ruby version: 2.4.1

### Issue

Warning outputs
```
14:23:36 - INFO - Medium - Some warning - Warning near line XX in /Users/123/www/123/app/controllers/application_controllerrb: ....
```

The file extension is missing a dot, which makes it non-clickable to open the file in your editor (supported in most terminals).

It also says `line 110 in FILE_PATH` rather than the correct colon format `FILEPATH:LINENUMBER`

Terminal example with file links, holding down ctrl/cmd:
![screen shot 2018-02-27 at 14 30 33](https://user-images.githubusercontent.com/49692/36713924-d21bcacc-1bca-11e8-9363-7cb1b8f83cf4.png)

A little annoying :D

**Comment by presidentbeef** [comment]
Hi Kristian,

This does not appear to be Brakeman output..?

**Comment by Frexuz** [comment]
```
> [#] ------ brakeman warnings --------
> [#]
23:59:25 - INFO - 1 previous warning
23:59:25 - INFO - Medium - SQL Injection - Possible SQL injection near line 114 in /Users/kristiangerardsson/www/flatelycom/app/controllers/application_controllerrb: ::Locale.from(cookies[:locale])
```

**Comment by presidentbeef** [comment]
You appear to be using https://github.com/guard/guard-brakeman. Unless you see this issue with regular Brakeman output, I suggest filing an issue there.

**Comment by Frexuz** [comment]
oh, sorry about that :P i thought guard would just wrap brakeman

**Comment by Frexuz** [comment]
This is the brakeman output

```

Controller Warnings:

+------------+-----------------------+----------------------------+------------------------------------------------------------------------------+
| Confidence | Controller            | Warning Type               | Message                                                                      |
+------------+-----------------------+----------------------------+------------------------------------------------------------------------------+
| High       | ApplicationController | Cross-Site Request Forgery | 'protect_from_forgery' should be called in ApplicationController near line 1 |
+------------+-----------------------+----------------------------+------------------------------------------------------------------------------+
```

same issue .. it would be nice to have clickable links

**Comment by presidentbeef** [comment]
If you use any of the 4.0+ versions, the default output looks like this:

```
Confidence: High
Category: Attribute Restriction
Check: ModelAttributes
Message: Mass assignment is not restricted using attr_accessible
File: app/models/recording_like.rb
Line: 1
```

which may work for you.
