### ISSUE TITLE
False positive or just confusion about attributes= and strong params

### ISSUE THREAD

**Issue by ruralocity** [presidentbeef/brakeman#1174]
### Background

Brakeman version: 4.2.1
Rails version: 4.2.7.1
Ruby version: 2.3.5p376

### Issue

Hi, thanks for the work you do on Brakeman. I have a question about a strong params-related warning I was attempting to fix. I'm not sure if it's a false positive, or there's a better solution than what I have so far.

#### False Positive?

*Full* warning from Brakeman:

```
Check: MassAssignment
Message: Unprotected mass assignment
Code: Notification.new(:event => (@event), :recipient => ((current_user.received_notifications.find_by_id(params[:reply]).sender or User.find(params[:id]))), :sender => current_user).attributes = notification_params
```

Relevant code:

I simplified this some, but the gist is, I've got a controller method that does double duty and handles both GET and POST requests, doing extra database work on POST, as was the fashion before Rails embraced REST. It sets some default attributes on a `@notification`, and in the case of a POST, overrides some of those with user-provided params that have been filtered with strong params.

```ruby
def big_crufty_action
  # lots of code omitted ...

  @notification = Notification.new({event: @event,
    recipient: @user, sender: current_user })

  if @reply_to and @notification.subject.blank?
    # override some of the defaults on @notification ...
  end

  if request.post?
    # this approach is flagged:
    @notification.attributes = notification_params

    # this approach is not:
    @notification.subject = notification_params[:subject]
    @notification.body = notification_params[:body]

    if @notification.save
      # code code code ...
    end
  end
  # more code ...
end

private

def notification_params
  params[:notification].permit(:subject, :body)
end
```

_Why might this be a false positive?_

I'm confused whether `attributes=` on an Active Record object should behave the same way as other Active Record methods, relative to strong params and Brakeman, or if there's a different way I should approach fixing this warning (short of rewriting this controller action to split it up, which I'd love to do but is out of scope at the moment).

Thanks very much!

**Comment by presidentbeef** [comment]
Hi Aaron,

Strangely, I cannot reproduce this issue. I don't think Brakeman should be warning about this kind of mass assignment in Rails 4.2 at all.

Do you happen to have either the `protected_attributes` gem in your Gemfile or `config.active_record.whitelist_attributes = false` somewhere?

**Comment by ruralocity** [comment]
Thanks Justin, looks like `protected_attributes` is the culprit. Removing it clears up the warning. We won't be able to drop it for a little awhile, but it's good to understand what's going on. Thanks again for your help!
