### ISSUE TITLE
--color option does not force color output

### ISSUE THREAD

**Issue by liamwhite** [presidentbeef/brakeman#1175]
### Background

Brakeman version: 4.2.1
Rails version: 5.1.5
Ruby version: 2.5.1

#### My Issue is Completely Different

Brakeman always checks if the output is a tty regardless of whether the --color option is passed.

For example, `brakeman --color | less -r` does not output any color codes to less.

Brakeman should use the --color option to override its heuristic of whether it should output color based on the output file being a tty.

**Comment by presidentbeef** [comment]
Hi Liam,

Sure, seems like a reasonable thing to do.

The `--color` option was originally only introduced for people to set `--no-color`, which is why it does not currently work the way you would like.
