### ISSUE TITLE
False positive - Unescaped model attribute

### ISSUE THREAD

**Issue by NARKOZ** [presidentbeef/brakeman#1177]
### Background

Brakeman version: 4.2.1
Rails version: 5.2.0
Ruby version: 2.5.1

#### False Positive

*Full* warning from Brakeman: 

```
Confidence: Medium
Category: Cross-Site Scripting
Check: CrossSiteScripting
Message: Unescaped model attribute
Code: Page.find_by!(:permalink => params[:permalink]).body
File: app/views/pages/show.html.slim
Line: 17
```

Relevant code:

```ruby
@page = Page.find_by!(permalink: params[:permalink])
```

**Comment by presidentbeef** [comment]
Hi Nihad,

It's not clear to me how this is a false positive. If `Page.find_by!(:permalink => params[:permalink]).body` is not escaped then it is an unescaped model attribute and it is a potential cross-site scripting vulnerability.

Now, guessing by the names of things, you are pulling a page of HTML out of the database and rendering it. In your case that may be totally safe. But there is no way for Brakeman to know that you think that is safe. In general, it is not safe.

Let me know if I'm interpreting this wrong, but I think this is not a false positive that Brakeman can or should avoid warning about.

**Comment by NARKOZ** [comment]
Sorry, I somehow mistook it for sql injection warning.
