### ISSUE TITLE
Possible strong params false positive

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1180]
### Background

Brakeman version: 4.2.1
Rails version: 5.1.6
Ruby version: 2.5.1

#### False Positive

I believe this might be a false positive (but I could definitely be missing some nuance!). If we have this in a controller:

```
def index
  # Using Sequel, though don't think it matters.
  render json: Person.where(index_params).qualify.all
end

private

def index_params
  # The `to_hash` is necessary for Sequel's `where` method.
  params.permit(:name, friend_names: []).to_hash
end
```

Brakeman gives us:

```
Confidence: Medium
Category: SQL Injection
Check: SQL
Message: Possible SQL injection
Code: Person.where(params.permit(:name, friend_names: []).to_hash)
File: app/controllers/people_controller.rb
Line: 4
```

I believe this is a false positive because we've already used the strong params API to whitelist the query arguments, and because Sequel will sanitize inputs passed in as a hash. I could be missing something though!

**Comment by presidentbeef** [comment]
Yes, it is a false positive. Support for not warning on `permit` was added but I suppose it should check for `to_h` and `to_hash` as well.

**Comment by JacobEvelyn** [comment]
Glad my read was correct. Is this something you'd like to implement or would you prefer I take a stab at it?
