### ISSUE TITLE
Reviving old proposal: Add check for config.force_ssl = true

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1181]
I noticed that brakeman doesn't warn when `config.force_ssl = true` is not set in the production configuration (e.g. `production.rb`). I also noticed that this check was proposed six years ago in #202 and the ultimate decision there was to not add the check.

I want to humbly propose that we revisit that decision, for a few reasons:

1. Brakeman's [stated policy](https://brakemanscanner.org/docs/reducing_false_positives/) is to errs on the side of reporting _too much_ rather than not reporting actual vulnerabilities.
2. As of #368, brakeman now has a robust mechanism for marking warnings to be ignored, so this warning shouldn't cause any real headache for users who want to ignore it.

Thoughts?

**Comment by presidentbeef** [comment]
As far as (1), that still has to be balanced against people's tolerance of false positives 😄(which is generally low).

I don't mind adding a check for this setting...but I wonder if it should be optional? Blindly turning it on can be dangerous.

**Comment by presidentbeef** [comment]
Oops, referenced the wrong issue again. Please ignore.

I am working on this next.

**Comment by JacobEvelyn** [comment]
Just noticed this is still open. Anything I can do to help, @presidentbeef ?
