### ISSUE TITLE
Command injection across methods?

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1184]
### Background

Brakeman version: 4.2.1
Rails version: 5.1.4
Ruby version: 2.5.1

### Issue

Brakeman is able to catch this command injection vulnerability:

```ruby
def dangerous(path)
  system("echo #{path}")
end
```

but not this one, even with `brakeman --interprocedural --branch-limit -1`:

```ruby
def dangerous(path)
  system(cmd(path))
end

def cmd(path)
  "echo #{path}"
end
```

Is that level of indirection something that brakeman should be able to catch? I confess I'm not exactly sure what the `--interprocedural` and `--branch-limit -1` flags actually change, though I've read the documentation on them.

**Comment by presidentbeef** [comment]
No, Brakeman doesn't do this kind of interprocedural dataflow analysis, even with `--interprocedural`.

The `--interprocedural` flag is/was experimental and not really maintained at this point. It was revamped in Brakeman Pro, which _will_ find this vulnerability (if the code is in a controller or model...should expand that to libraries soon, too).

`--branch-limit` takes some explanation. When Brakeman sees something like this

```ruby
if something
  x = 1
else
  x = 2
end

puts x
```
It will join the two values of `x`. The result looks like

```ruby
if something
  x = 1
else
  x = 2
end

puts (1 or 2)
```
In real-world applications, the number of "joined" elements can become really large, causing Brakeman to be very slow and use a lot of memory. So `--branch-limit` was introduced. It essentially controls how many `or`s are allowed in the "joined" values.

**Comment by JacobEvelyn** [comment]
Gotcha, thanks for the explanation! Re: `--interprocedural`, is there any harm to us continuing to use it with OSS `brakeman`? (Especially as this gives us less to change if/when we switch to Pro.) Or would you recommend we stop using it?
