### ISSUE TITLE
Consider adding `:foreign_key` to `IGNORE_METHODS_IN_SQL`?

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1202]
### Background

Brakeman version: 4.2.1
Rails version: 5.2.0
Ruby version: 2.3.4

#### False Positive

Brakeman's warning us about a dynamic query we build up that uses an ActiveRecord association reflection to build a query. The code looks something like this:

```ruby
assoc_reflection = reflect_on_association(:foos)
foreign_key = assoc_reflection.foreign_key

Bar.joins("INNER JOIN <complex join involving custom SQL and #{foreign_key} interpolation>")
```

I believe this is a false positive akin to the `primary_key` that Brakeman [ignores](https://github.com/presidentbeef/brakeman/blob/6158b1055385b0a94f9fe528c7d49527437e8129/lib/brakeman/checks/check_sql.rb#L574), but of course any additional exceptions for false positives run the risk of missing actual vulnerabilities (for instance, when a user-defined method shares that name but generates the value using unsafe user input). It's not a big deal for us either way; we can just use `ApplicationRecord.connection.quote_column_name`, but I'm wondering what you think about this sort of thing more generally.

**Comment by presidentbeef** [comment]
I think it's fine.
