### ISSUE TITLE
Missing SQL injection/params vulnerability

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1204]
### Background

Brakeman version: 4.3.0
Rails version: 5.1.6
Ruby version: 2.5.1

### Issue

It looks like Brakeman doesn't catch SQL injection vulnerabilities when arguments are splatted into ORM methods. Compare:

```ruby
# Using Sequel, though don't think it matters.

def brakeman_catches_this
  render json: Person.where(params[:foo]).qualify.all
end

def brakeman_does_not_catch_this
  render json: Person.where(*params[:foo]).qualify.all
end

def brakeman_does_not_catch_this_either
  render json: Person.where(**params[:foo]).qualify.all
end
```

Does that make sense?

I suspect this issue might be relevant to many checks, not just the SQL injection one. Or am I missing something?

**Comment by presidentbeef** [comment]
Might be hard to avoid false positives, but I think the simplest way to handle this is to ignore the splat and treat the argument as as regular argument.
