### ISSUE TITLE
NoMethodError - using Code Climate with upgrade to 4.3.0

### ISSUE THREAD

**Issue by efueger** [presidentbeef/brakeman#1210]
### Error

Code Climate user running into an error, starting May 15. 

```
engine brakeman failed with status 1 and stderr 
/usr/src/app/lib/brakeman/processors/controller_alias_processor.rb:183:in `process_template': undefined method `+' for nil:NilClass (NoMethodError)
	from /usr/src/app/lib/brakeman/processors/controller_alias_processor.rb:173:in `process_default_render'
	from /usr/src/app/lib/brakeman/processors/controller_alias_processor.rb:100:in `block in process_defn'
	from /usr/src/app/lib/brakeman/processors/alias_processor.rb:432:in `block in meth_env'
	from /usr/local/bundle/gems/sexp_processor-4.11.0/lib/sexp_processor.rb:452:in `scope'...
```

### Background
- Code Climate upgraded the builder for Brakeman's new 4.3.0 version on May 15.
- Repo was running Brakeman analysis before with no probs :ok_hand: 
- reach out to @efueger (Support at Code Climate) if you need more details from the logs!

**Comment by presidentbeef** [comment]
Hi Emily,

Thank you for reporting this. I am a little mystified currently as to why the version change would have had any effect.

I will see if I can reproduce the issue.

**Comment by presidentbeef** [comment]
@efueger can you please try 91591c6817628833f924ee85ea706f105b1148d9 and see if that resolves the issue?

**Comment by efueger** [comment]
Thanks @presidentbeef! I'll loop in my dev colleagues to try that out.

**Comment by pirvudoru** [comment]
@efueger Did your colleagues have the chance to look over this patch ?

**Comment by larkinscott** [comment]
Hey @presidentbeef - thanks for the quick patch! This looks good to me.
