### ISSUE TITLE
False positive with whitelisted strings in constant

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1211]
### Background

Brakeman version: 4.3.0
Rails version: 5.1.6
Ruby version: 2.3.4

#### False Positive

This is somewhat similar to #1208 but based on the behavior I think they're different enough for this to be a separate issue.

I noticed that with Brakeman correctly does not warn about SQL/command injection in this case:

```ruby
def safe(foo)
  unless [:bar, :baz].include? foo
    raise ArgumentError, "Unexpected foo: #{foo}"
  end

  Person.where("#{foo} >= 1")
end
```

but Brakeman _does_ produce a warning in this equally safe scenario:

```ruby
ALLOWED_FOOS = [:bar, :baz].freeze
def safe(foo)
  unless ALLOWED_FOOS.include? foo
    raise ArgumentError, "Unexpected foo: #{foo}"
  end

  Person.where("#{foo} >= 1")
end
```

**Comment by presidentbeef** [comment]
I'm going to guess it's the `freeze` call causing problems again.

**Comment by JacobEvelyn** [comment]
Ah yes, you're right. I forgot to test that with the constant but not `.freeze`.

**Comment by presidentbeef** [comment]
I was wrong, here. Freezing a constant was already handled.

I'm not 100% sure what exactly fixed this, but I can't reproduce the issue on master.

**Comment by JacobEvelyn** [comment]
Hmm, I can reproduce this on `master`. If I go to `brakeman/test/apps/rails5.2/app/controllers/users_controller.rb` and add this:

```ruby
ALLOWED_FOOS = [:bar, :baz].freeze
def delete(foo)
  unless ALLOWED_FOOS.include? foo
    raise ArgumentError, "Unexpected foo: #{foo}"
  end

  Person.where("#{foo} >= 1")
end
```

I see the warning.
