### ISSUE TITLE
Support simple, derived whitelist constants?

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1213]
### Background

Brakeman version: 4.3.0
Rails version: 5.1.6
Ruby version: 2.5.1

### Issue

We've got some code that produces somewhat complex SQL queries, and Brakeman produces a SQL injection warning. For clarify, I'll demonstrate the issue with a (very contrived) command injection example though:

```ruby
COMMANDS = { foo: "echo", bar: "cat" }
MORE_COMMANDS = { foo: "touch" }

def safe(arg)
  command = if Date.today.tuesday? # Some condition.
    COMMANDS[arg]
  else
    MORE_COMMANDS[arg]
  end

  `#{command} file1.txt`
end
```

We're trying to get Brakeman to stop warning us about this, and it's a bit tricky to use sanitization here given the SQL we're producing, so we were thinking of going for a whitelist approach, like so:

```ruby
COMMANDS = { foo: "echo", bar: "cat" }
MORE_COMMANDS = { foo: "touch" }
WHITELIST = COMMANDS.values + MORE_COMMANDS.values

def safe(arg)
  command = if Date.today.tuesday?
    COMMANDS[arg]
  else
    MORE_COMMANDS[arg]
  end

  raise "STOP!" unless WHITELIST.include?(command)

  `#{command} file1.txt`
end
```

However, Brakeman doesn't seem to be able to understand whitelists unless they're literals rather than anything derived. It might be that it's just too difficult to support this, but I wonder if for some narrow defined cases (like expanding `keys` and `values` on constant Hash literals into array literals) it could be supported. I don't know what sort of maintenance burden that would be, however.

Thoughts?

**Comment by presidentbeef** [comment]
I fixed the top example...not sure if it addresses your specific issue though.
