### ISSUE TITLE
Output File is empty and errors are surpressed for Ruby 2.5 Syntax

### ISSUE THREAD

**Issue by acid** [presidentbeef/brakeman#1221]
### Background

Brakeman version: 4.3
Rails version: 5.1.4
Ruby version: ruby 2.5.1

### Issue

If we have a parser error as described in #1173 and we add the `--output` option to the command brakeman didn't print the error messages, keeps the output file empty and finishes with exit code 7.

Without output parameter the errors are reported as expected.

#### Other Error

Even though this is a known bug in `ruby_parser` we should pass the errors which are happening and still write to the output file.

Debug option produces no interesting Stack trace:

```
> bundle exec brakeman --debug --output brakeman-output.tabs
...
Checks finished, collecting results...
Filtering warnings...
[Notice] Using '.../config/brakeman.ignore' to filter warnings
Generating report...
Report saved in 'brakeman-output.tabs' #this one consists of 2 or 3 empty lines
```

**Comment by presidentbeef** [comment]
Hi Daniel,

I think I understand the confusion here.

The `tabs` output format does not output errors, only security warnings. It's strictly intended for consumption by the Brakeman plugin for Jenkins. At this point, even that is not recommended. Please use the latest Jenkins plugin which supports `json` reports instead.
