### ISSUE TITLE
Command injection false positive in enumeration

### ISSUE THREAD

**Issue by bannable** [presidentbeef/brakeman#1224]
### Background

Brakeman version: 4.3.0
Rails version: 3.2.22.8
Ruby version: 2.3.7p456

#### False Positive

*Full* warning from Brakeman:
```
Confidence: Medium
Category: Command Injection
Check: Execute
Code: `echo #{table}`
```

Relevant code:

```ruby
  def safe
    tables = %w(one two)
    tables.each { |table| `echo #{table}` }
  end
```

**Comment by presidentbeef** [comment]
Fixed by #1227 (and actually a duplicate of #1208).
