### ISSUE TITLE
Command injection false positive - "unless test" is treated differently than "if !test"

### ISSUE THREAD

**Issue by bannable** [presidentbeef/brakeman#1225]
### Background

Brakeman version: 4.3.0
Rails version: 3.2.22.8
Ruby version: 2.3.7p456

### Issue

I noticed that brakeman is returning a false positive depending on how a conditional whitelist is constructed. 

#### False Positive

*Full* warning from Brakeman:
```
Confidence: Medium
Category: Command Injection
Check: Execute
Code: `echo #{foo}`
File: lib/hello.rb
Line: 16

Confidence: Medium
Category: Command Injection
Check: Execute
Code: `echo #{foo}`
File: lib/hello.rb
Line: 6
```

Relevant code:

```ruby
module HelloWorld
  ALLOWED_FOOS = [:bar, :gaz]
  FROZEN_FOOS = [:qux, :quz].freeze
  def safe_one(foo)
    return if !ALLOWED_FOOS.include?(foo)
    `echo #{foo}`
  end

  def safe_two(foo)
    return unless ALLOWED_FOOS.include?(foo)
    `echo #{foo}`
  end

  def safe_three(foo)
    return if !FROZEN_FOOS.include?(foo)
    `echo #{foo}`
  end

  def safe_four(foo)
    return unless FROZEN_FOOS.include?(foo)
    `echo #{foo}`
  end
end
```

At first I thought this was the same as #1211, but then I noticed that `.freeze` doesn't change the behavior as suggested in that issue. It seems like brakeman is failing to recognize the negative conditional test of the form `if !test`, but it does correctly recognize `unless test`.

**Comment by presidentbeef** [comment]
True, because `if !test` and `unless test` are not exactly the same semantically and therefore look very different :disappointed:
