### ISSUE TITLE
Suspected false positive on DangerousEval / User input in eval

### ISSUE THREAD

**Issue by stringsn88keys** [presidentbeef/brakeman#1236]
### Background

Brakeman version: 3.7.2
Rails version: 4.2.10
Ruby version: 2.4.3p205

Link to Rails application code: ?

### Issue

Input used to select a value from a whitelist that is sent to `instance_eval` is being interpreted as being sent directly to `instance_eval`.

#### False Positive

*Full* warning from Brakeman: `?`
``` text
Category: Dangerous Eval
Check: Evaluation
Message: User input in eval
Code: instance_eval(&Whitelist.select(params[:apparent_user_input]).attached_block)
File: app/controllers/not_a_real_controller.rb
Line: 21
```

Relevant code:

```ruby
class Whitelist
  class << self
    def whitelist
      @@whitelist ||= []
    end

    def select(param_value)
      whitelist.each do |whitelist_item|
        return whitelist if param_value == whitelist_item.to_s
      end
      raise "Not in the whitelist"
    end
  end
end

class NotARealController < ApplicationController
  def whitelisted_action
    param_value = params[:apparent_user_input]
    whitelisted_item = Whitelist.select(param_value)
    if plugin.attached_block
      instance_eval &whitelisted_item.attached_block
    end
  end
end
```

_Why might this be a false positive?_

The `Whitelist` class returns a value from the whitelist or raises an exception via the `select` method, but the collapsed code used in evaluations of the vulnerability appears to interpret the `params[:apparent_user_input]` as being passed directly to the `instance_eval`.

**Comment by presidentbeef** [comment]
Hi Thomas, thank you for reporting this issue.

I agree perhaps the confidence on the warning could be lowered. However, Brakeman is not going to know what `Whitelist.select` does. Even if it looked into the method definition, it's too complicated to figure out in the general case.

I suggest using `brakeman -I` and ignoring this one.
