### ISSUE TITLE
querying raw sql with something like WRERE .. IN got sql injected report

### ISSUE THREAD

**Issue by mnosuk** [presidentbeef/brakeman#1255]
### Background

Brakeman version: 4.3.1
Rails version: 4.2.1.7

i have to write code below
```
   #  params[:quotation_type] is an array, i try to quote each of them to prevent injection
   quotation_type = params[:quotation_type].map { |qt| ActiveRecord::Base.connection.quote(qt)}.join(',')

    ActiveRecord::Base.connection.execute(
       ### SOME SQL 
        FROM sometables  WHERE u.quotation_type IN (#{quotation_type})  
    )
```

look like brakeman  want me to quote all of quotation_type but result will go wrong

  
![screen shot 2561-08-30 at 18 29 18](https://user-images.githubusercontent.com/12839963/44849027-fae77980-ac82-11e8-943c-6d463ba872b9.png)

hope you understand my english, it's not my native language
thanks in advance :)

**Comment by presidentbeef** [comment]
Hi @mnosuk - sorry for the delay.

It is difficult to detect whether or not this is safe, so for now you may need to ignore it. Brakeman is overly cautious about values being passed to `ActiveRecord::Base.connection.execute` since it is easy to introduce a vulnerabilitiy.
