### ISSUE TITLE
App tree scanner missing some views.

### ISSUE THREAD

**Issue by matthewtuck** [presidentbeef/brakeman#1275]
For an app that has multiple view paths, Brakeman's app_tree.rb (as of 4.3.1), only looks for views in ````app/**/views````. However it doesn't allow matching other paths, such as ````app/views*````. It would be nice if it could pick these up, be configurable, or just find views wherever they live.

**Comment by presidentbeef** [comment]
Hi Matthew,

I agree an option to add search paths for views might be useful, but view paths have some semantics attached to them in Rails so I'm a little confused how to treat views in paths that don't correspond to controllers. Can you elaborate on what kind of directory structure you have?

**Comment by matthewtuck** [comment]
Right. We have a multi-tenanted application that has various overrides, such as for specific sites, brands and countries. For example:

````app/views_for_brands/brandX```` overrides ````app/views````.

Each of these is essentially a root unto itself and is set up with ````prepend_view_path```` dynamically.

I'm guessing that the special handling is because you need to determine what the relevant view is for a controller action when done by config by convention, in which case allowing a proc or such to override this might be useful.

However in our case, there are actually multiple alternatives and we'd want all checked. We could set up multiple configurations of view path lists, though I guess that's more complicated than I'd hoped.

**Comment by presidentbeef** [comment]
I honestly don't know how to handle this 😕

**Comment by presidentbeef** [comment]
Templates should be found almost anywhere now: #1520
