### ISSUE TITLE
Documentation missing for few warning types in site

### ISSUE THREAD

**Issue by harish-pendyala** [presidentbeef/brakeman#1283]
Documentation is missing for the following checks/warning_types in the [site](http://brakemanscanner.org/docs/warning_types/)
1. Divide By Zero
2. Nested Attributes
3. Path Traversal
4. Response Splitting
5. Timing Attack
6. Weak Hash

**Comment by presidentbeef** [comment]
Hi Harish, thank you for compiling this list. I will take a look.

**Comment by presidentbeef** [comment]
"Nested Attributes", "Path Traversal", "Response Splitting", and "Timing Attack" are only used in the context of CVEs and the warnings are linked to the relevant security bulletins. Therefore I do not think it is strictly necessary to document them on the website at this time. Maybe in the future.

"[Divide By Zero](https://brakemanscanner.org/docs/warning_types/divide_by_zero/)" and "[Weak Hash](https://brakemanscanner.org/docs/warning_types/weak_hash/)" have been added.
