### ISSUE TITLE
Support coloured output on STDOUT but still HTML to file

### ISSUE THREAD

**Issue by f3ndot** [presidentbeef/brakeman#1289]
**Is your feature request related to a problem? Please describe.**

Running 

```
$ bundle exec brakeman -o brakeman/report.html
Loading scanner...
...
Checks finished, collecting results...
Generating report...
Report saved in 'brakeman/report.html'
```

No longer prints the report in `text` to STDOUT.

**Describe the solution you'd like**

I would like to have my cake and eat it too. I still want an HTML-formatted report stored as a file, but I still want the default behaviour of colourized text output to STDOUT:

```
$ bundle exec brakeman -o brakeman/report.html
Loading scanner...
...
Checks finished, collecting results...
Generating report...
Report saved in 'brakeman/report.html'

== Brakeman Report ==

Application Path: /Users/justinbull/Code/foobar
Rails Version: 5.1.6.1
Brakeman Version: 4.3.1
...
No warnings found
```

If this isn't desirable default behaviour, we could make it an optional flag

```
bundle exec brakeman -o brakeman/report.html --keep-text-stdout
```

Or even support multiple output & format tuples like rspec:

```
bundle exec brakeman -f html -o brakeman/report.html -f text -o stdout
```

**Describe alternatives you've considered**

I am able to get around this by doing:

```
$ bundle exec brakeman -o brakeman/report.html -o brakeman/report.txt
...
$ cat report.txt
```

But that creates two files and I lose my coloured output.

**Additional context**

This is a desirable feature so in CircleCI I can:

1. Have a coloured output in the job step, which a lot of our engineers use to look at failures
2. But also have a beautiful HTML report that can be stored as an artifact later.

**Comment by presidentbeef** [comment]
Hi Justin,

You are the first person to ever refer to the Brakeman HTML report as "beautiful", so thanks for that. 😉 

Anyhow, you should be able to get exactly what you want like this:

```
$ bundle exec brakeman -o brakeman/report.html -o /dev/stdout --color
```

You will probably need `--color` to force the color output.

**Comment by f3ndot** [comment]
Thank you!
