### ISSUE TITLE
brake show high vulnerablity on order raw sql , how to resolve 

### ISSUE THREAD

**Issue by navkumar2245** [presidentbeef/brakeman#1292]
### Background

Brakeman version: 4.3.1 
Rails version: 5.0.7
Ruby version: 2.5.1

records ar e comming from multiple joins 
 contacts = contacts.order("contacts.#{field} #{sort} ,contacts.first_name #{sort}, contacts.id asc").paginate(page: params[:page], per_page: 25)

**Comment by presidentbeef** [comment]
Hi,

Best way to deal with this is to have a whitelist of `field` and `sort` values, if possible. Rails does not provide a safe way of calling `order`, unfortunately.
