### ISSUE TITLE
Please consider relaxing sass dependency

### ISSUE THREAD

**Issue by monfresh** [presidentbeef/brakeman#1295]
Hello. The dependency on `sass` was last set to <3.5.0 over a year ago, and released in version 4.3.1.  This is preventing us from upgrading brakeman because we use `scss_lint`, which depends on sass version `~> 3.5.5`. From the commit message, it looks like the reason for the version constraint was to support Ruby 1.9. Would it be possible to add some logic so that folks using the latest version of Ruby can use the latest version of Sass? 

Perhaps would it make sense to stop supporting 1.9? Support for 1.9.3 ended in February 2015: https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by presidentbeef** [comment]
![image](https://user-images.githubusercontent.com/75613/50708482-420ebe00-1019-11e9-8089-c5b3f63892fb.png)

Looks like dropping 1.9.3 support should be okay. Won't be in the next release (4.4.0) but I expect to do so in 4.5.0.
