### ISSUE TITLE
[False Positive] on explicitly untainted data

### ISSUE THREAD

**Issue by renaud-durand** [presidentbeef/brakeman#1296]
### Background

Brakeman version: 4.3.1
Rails version: 5.2.1
Ruby version: 2.3.7p456

Link to Rails application code: _not public_

*Full* warning from Brakeman: 
```
Confidence: High
Category: Dangerous Send
Check: Send
Message: User controlled method execution
Code: orga.public_send(params[:item_type].to_sym)
File: **** messages_controller.rb
Line: 157
```

Relevant code:

```ruby
148 model_name = params[:item_type]&.to_sym
149 model_configuration = EXTERNAL_MODELS[model_name]
150
151 unless model_configuration
152      redirect_to some_path, flash: { error: "Invalid item_type: '#{params[:item_type]}'" }
153     return
154 end
155 model_name.untaint!
156
157 items_scope = orga.public_send(model_name).not_trashed
```
_Why might this be a false positive?_

We do explicitely untaint the object and brakeman still considering the public_send as a *Dangerous Send* after raising an exception if `model_name` was not part of our whitelist.

**Comment by presidentbeef** [comment]
Hi Renaud,

I agree this is a false positive. Brakeman is a little limited in how well it can detect things like guard conditions with early returns, and this is a bit of a complicated case.
