### ISSUE TITLE
Please provide proper license in RubyGems

### ISSUE THREAD

**Issue by mensfeld** [presidentbeef/brakeman#1303]
Could you please use `Brakeman Public Use License` instead of `NonStandard` as a rubygems licence. I can't whitelist the `NonStandard` in the reports as it is really, really general.

![zrzut ekranu z 2019-01-18 13-50-57](https://user-images.githubusercontent.com/392754/51387969-56c67800-1b28-11e9-8bfc-64e2f6ba52d6.png)

**Comment by presidentbeef** [comment]
Sure, makes sense.

I was just following RubyGem's advice but I can see how that's a problem :)

**Comment by mensfeld** [comment]
Thank you! :heart:
