### ISSUE TITLE
Railroader - OSS fork of Brakeman

### ISSUE THREAD

**Issue by david-a-wheeler** [presidentbeef/brakeman#1312]
Hi, I just wanted to let you know that I've created a fork of Brakeman called "Railroader".  Brakeman is no longer [open source software (OSS)](https://opensource.org/osd-annotated), so I've created Railroader as an OSS fork under the original Brakeman licenses.   I have forked from Brakeman version 4.3.1, which was the last OSS version.

Railroader is a project fork, but hopefully not a *hostile* fork.  We will not accept software licensed only under CC-BY-NC-SA-4.0, since that is not an OSS license.  But we'll gladly accept good contributions from anyone if they are released under the original OSS licenses (MIT for software, CC-BY-3.0 for website content).

We assume that "Brakeman" is now a trademarked by Synopsys, Inc, so we've tried to rename everything so that the projects are clearly distinct. If we've missed something, please let us know and we'll fix it.  The term "Railroader" is a play on the word Rails, but it is obviously a completely different word.  Railroader shares a common code base historically with Brakeman, and that's important to explain, but they are not the same projects and we are expressly trying to *not* infringe on any Brakeman trademark.  It's obviously legal to copy and modify materials licensed under the MIT and CC-BY-3.0 (that's the purpose of these licenses), but if there are other legal issues please let me know.

If the Brakeman project wants to cooperate in some way, we'd love to talk!  We are all united in our desire to squash out vulnerabilities *before* they are deployed. In addition, we're grateful for all the work that you've done.

Key URLs:

- https://railroader.org/
- https://github.com/david-a-wheeler/railroader

Take care!

**Comment by presidentbeef** [comment]
Sorry to see this, although not unexpected.

> We will not accept software licensed only under CC-BY-NC-SA-4.0, since that is not an OSS license

For clarity, Brakeman is released under the [Brakeman Public Use License](https://github.com/presidentbeef/brakeman/blob/master/LICENSE.md).

> We assume that "Brakeman" is now a trademarked by Synopsys, Inc

A fair assumption, but it is not owned by Synopsys. You could argue the trademark is owned by Brakeman, Inc. or by myself.

**Comment by david-a-wheeler** [comment]
Thanks for the clarification!

I just wanted to make sure you knew.

Take care.
