### ISSUE TITLE
Parsing error on enums after upgrading to 4.4.0

### ISSUE THREAD

**Issue by mberlanda** [presidentbeef/brakeman#1322]
### Background

Brakeman version: 4.4.0
Rails version: 5.2.2
Ruby version: 2.5.3

Link to Rails application code:

```rb
  enum migration_state: { not_started: 0,
                          error: -1,
                          pending: 1,
                          success: 2 },
       _prefix: 'migration'
```

#### Parse Error

(Consult https://brakemanscanner.org/docs/troubleshooting/parse_errors/ first. Note that (most) parsing errors are from the ruby_parser library, not Brakeman itself.)

Minimal example that does not parse:

Before upgrading the gem:

```
$ ruby_parse app/models/account.rb
# ...
s(:call,
  nil,
  :enum,
  s(:hash,
   s(:lit, :migration_state),
   s(:hash,
    s(:lit, :not_started),
    s(:lit, 0),
    s(:lit, :error),
    s(:lit, -1),
    s(:lit, :pending),
    s(:lit, 1),
    s(:lit, :success),
    s(:lit, 2)),
   s(:lit, :_prefix),
   s(:str, "migration"))),
```

After upgrading the gem:

```
ruby_parse app/models/account.rb
# file = app/models/account.rb loc = 349
~/.rbenv/versions/2.5.3/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error' #<Racc::ParseError: app/models/account.rb:15 :: parse error on value ":" (tCOLON)> for app/models/account.rb
```

**Comment by mberlanda** [comment]
Somehow related to #1306 but using different versions

**Comment by mberlanda** [comment]
```
$ ruby-parse -v
ruby-parse based on parser version 2.5.3.0
```

**Comment by presidentbeef** [comment]
Hi @mberlanda,

I cannot reproduce this issue with the code you've provided above.

Please note the error messages can be misleading, something I have attempted to address with #1320.

Also, `ruby-parse` must be from the [parser](https://rubygems.org/gems/parser) gem, not [ruby_parser](https://rubygems.org/gems/ruby_parser).

**Comment by mberlanda** [comment]
hi @presidentbeef , thank you very much for your quick reply!

Actually the breaking code was not at line 15 but around 40.
The minimal code snippet to reproduce is:

```rb
class Test < ApplicationRecord
  validates_each :logo_url, allow_blank: true do |record, attribute_name, attribute_value|
    URI.parse(attribute_value)
  rescue URI::InvalidURIError => error
    record.errors.add(attribute_name, 'is an invalid url')
  end
end
```

Re-introducing redundant begin blocks will fix the parsing error:

```rb
class Test < ApplicationRecord
  validates_each :logo_url, allow_blank: true do |record, attribute_name, attribute_value|
    begin
      URI.parse(attribute_value)
    rescue URI::InvalidURIError => error
      record.errors.add(attribute_name, 'is an invalid url')
    end
  end
end
```

**Comment by victorlcampos** [comment]
Yes, I'm getting the same error:

     `<%= render 'layouts/vprocessmanager/progressbar', process_instance: @acceptance_term.process_instance, max_size: 4, cache: true %>
`
