### ISSUE TITLE
Command injection false positive when code is in different files

### ISSUE THREAD

**Issue by mo-nathan** [presidentbeef/brakeman#1323]
### Background

Brakeman version: 4.4.0
Rails version: 5.2.2
Ruby version: 2.6.1 (or 2.4.1)

Link to Rails application code: https://github.com/mo-nathan/brakeman-bug (isolated cases that demonstrates issue)
#### False Positive

*Full* warning from Brakeman: `Possible command injection`

Relevant code:

```ruby
  def a_cmd
    a = A.new
    result, status = Open3.capture2e("ls",
                                     Shellwords.escape(a.z))
  end
```

_Why might this be a false positive?_
As I understand it, the use of `Shellwords.escape` should resolve the issue regardless of where the function `z` is defined.  However, it only does when it is defined in the same file.  When it is coming from another file the false positive happens.

**Comment by presidentbeef** [comment]
Hi Nathan,

Thank you for providing a nice full example to reproduce the problem.

What's happening is that `A` is being considered a model (because its in `app/models`) and for some reason that is causing a difference. I'll take a look.

Thanks!

**Comment by mo-nathan** [comment]
Thanks for looking into it and for such a great tool!  Is there a reason why actually being a model should make a difference?  In the real case the 'A' object is a model.

**Comment by presidentbeef** [comment]
The only reason it makes a difference is because the code for the command injection check is a bit messy and so shell escaping isn't handling properly everywhere.
