### ISSUE TITLE
warning type question(confidence level)

### ISSUE THREAD

**Issue by naoto-koyama-uhuru** [presidentbeef/brakeman#1328]
## Background
  - Rails 5.1.6.1
  - ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  - Just created a new project and added brakeman

## Do
```
$ brakeman -w3
$ brakeman -w2
$ brakeman -w1
```

## Result
- The following waring types to check with Weak to High are same.

```
 - CheckBasicAuth
 - CheckBasicAuthTimingAttack
 - CheckCrossSiteScripting
 - CheckContentTag
 - CheckCreateWith
 - CheckDefaultRoutes
 - CheckDeserialize
 - CheckDetailedExceptions
 - CheckDigestDoS
 - CheckDynamicFinders
 - CheckEscapeFunction
 - CheckEvaluation
 - CheckExecute
 - CheckFileAccess
 - CheckFileDisclosure
 - CheckFilterSkipping
 - CheckForgerySetting
 - CheckHeaderDoS
 - CheckI18nXSS
 - CheckJRubyXML
 - CheckJSONEncoding
 - CheckJSONParsing
 - CheckLinkTo
 - CheckLinkToHref
 - CheckMailTo
 - CheckMassAssignment
 - CheckMimeTypeDoS
 - CheckModelAttrAccessible
 - CheckModelAttributes
 - CheckModelSerialize
 - CheckNestedAttributes
 - CheckNestedAttributesBypass
 - CheckNumberToCurrency
 - CheckPermitAttributes
 - CheckQuoteTableName
 - CheckRedirect
 - CheckRegexDoS
 - CheckRender
 - CheckRenderDoS
 - CheckRenderInline
 - CheckResponseSplitting
 - CheckRouteDoS
 - CheckSafeBufferManipulation
 - CheckSanitizeMethods
 - CheckSelectTag
 - CheckSelectVulnerability
 - CheckSend
 - CheckSendFile
 - CheckSessionManipulation
 - CheckSessionSettings
 - CheckSimpleFormat
 - CheckSingleQuotes
 - CheckSkipBeforeFilter
 - CheckSprocketsPathTraversal
 - CheckSQL
 - CheckSQLCVEs
 - CheckSSLVerify
 - CheckStripTags
 - CheckSymbolDoSCVE
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckValidationRegex
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
```

## Expect
- I think as the Confidence levels increase, number of waning types increase.
- Please add confidence levels details to REAMDE.

**Comment by presidentbeef** [comment]
Hi @naokikimura,

Thank you for your question.

> I think as the Confidence levels increase, number of waning types increase.

This is not a correct assumption and may be the root of your confusion. Setting the confidence level filters individual warnings (not types) from the report, based on the confidence level of the specific warning.

Confidence levels are not connected to warning types or checks (which are what you have listed).

Setting the confidence level *higher* raises the filter to reduce the number of warnings reported.

> Please add confidence levels details to REAMDE.

As you know, details are already present in the README: https://github.com/presidentbeef/brakeman#confidence-levels.

If you have suggestions for making the information clearer, please let me know.

**Comment by naoto-koyama-uhuru** [comment]
Hi

Thank you for replay.

I understand from below!

> This is not a correct assumption and may be the root of your confusion. Setting the confidence level filters individual warnings (not types) from the report, based on the confidence level of the specific warning.
> Confidence levels are not connected to warning types or checks (which are what you have listed).
> Setting the confidence level higher raises the filter to reduce the number of warnings reported.

It closes this issue.
