### ISSUE TITLE
Check link_to false negative when passing only one parameter

### ISSUE THREAD

**Issue by swallenfriedman** [presidentbeef/brakeman#1339]
### Background

Brakeman version: 4.5.0
Rails version: 5.2.2.1
Ruby version: Using brakeman docker image

### Issue

Here's a code snipped that produces an xss vulnerability that isn't getting flagged by brakeman. I believe it's because the brakeman code is only running this check for rails versions '2.0.0' to '2.9.9.' It seems that link_to escaped its first argument in Rails 3, but I don't believe it does so in Rails 4 or 5.

```
<%= link_to params[:some_param] do %>
  <span>Link Text</span>
<% end %>
```

**Comment by presidentbeef** [comment]
Hi @swallenfriedman -

Thank you for reporting this.

I was confused at first, but I see the issue is that you are calling `link_to` with a block. That version makes the first argument the URL...which as you point out can lead to XSS.

Should be no problem to rectify this.

**Comment by presidentbeef** [comment]
Just to clarify a little bit...

There are two checks for `link_to` - `LinkTo` and `LinkToHref`. The former is more for older versions of Rails, the latter is for newer versions where `link_to` HTML escapes its inputs but doesn't prevent the `javascript:` schema.

What's a little crazy is that [I added `link_to` with a block as a test case in 2012](https://github.com/presidentbeef/brakeman/blob/80202eb26d0632bf685fc2af86e9e396d121f979/test/apps/rails2/app/views/home/test_link_to.html.erb#L3-L5) but... either I thought it was safe then or I forgot to actually test it. I am not going to try to go back to Rails 2.3 and see if that's a true positive or not.

**Comment by presidentbeef** [comment]
@JacobEvelyn I don't think so. If you pass in a single argument to `link_to` with no block it will treat that argument as the body of the tag and escape the content properly, even if you pass in a hash or array. At least with Rails 5.2/6.0.

**Comment by JacobEvelyn** [comment]
Ah yes, @presidentbeef @swallenfriedman you're both correct—`link_to` with a single argument and no block sets the current location as the `href` location. Ignore me!

**Comment by swallenfriedman** [comment]
Good to know the single argument escapes properly! @presidentbeef thanks for getting on this so quickly, appreciate both the tool and the quick turnaround.
