### ISSUE TITLE
Negating a parameter still triggers 'Unescaped parameter value'

### ISSUE THREAD

**Issue by mikecmpbll** [presidentbeef/brakeman#1343]
### Background

Brakeman version: 4.5.0
Rails version: 5.1.6.2
Ruby version: 2.6.2p47

Link to Rails application code: 

#### False Positive

*Full* warning from Brakeman:

```
Confidence: Weak
Category: Cross-Site Scripting
Check: CrossSiteScripting
Message: Unescaped parameter value
Code: [ManualCSVImport.new(:header_row => ((not (not params[:header_row]))), :archive => ((not (not params[:archive])))).results[:invalid_info], ManualCSVImport.new(:header_row => ((not (not params[:header_row]))), :archive => ((not (not params[:archive])))).results[:ignored_info]].flatten.join("<br/>")
File: app/views/student_imports/new.html.erb
Line: 5
```

Relevant code:

```ruby
si = ManualCSVImport.new(header_row: !!params[:header_row], archive: !!params[:archive])
@errors = [si.results[:invalid_info], si.results[:ignored_info]].flatten
```

```erb
<%= @errors.join("<br/>").html_safe %>
```

By negating it we're ensuring it must be either true or false, so shouldn't trigger unescaped parameter value check. If I change the code to `params[:header_row] ? true : false` it passes.

**Comment by mikecmpbll** [comment]
(i wasn't sure if i should create this issue as i'm not sure whether this is in scope, perhaps this is just an 'ignore' situation?)

**Comment by presidentbeef** [comment]
Hi @mikecmpbll -

This can definitely be handled in Brakeman. Thanks for reporting!
