### ISSUE TITLE
Check for 'no opener/no referrer'

### ISSUE THREAD

**Issue by taylom2** [presidentbeef/brakeman#1346]
A JavaScript linter identified a 'no opener/no referrer' issue, however this was not identified by brakeman.

If window.opener is set, a page can trigger a navigation in the opener regardless of security origin. This could be used to redirect users to a phishing page, designed to look like the real thing. This form of attack requires JavaScript to be enabled in the browser.

To fix on most browsers rel="noopener noreferrer" can be added where target=_blank is used. 

More info here - https://mathiasbynens.github.io/rel-noopener/

Is this something that can be added?
Thanks

**Comment by presidentbeef** [comment]
Hi!

Do you mean checking calls to `link_to` that set `target`?

**Comment by taylom2** [comment]
Hello!

Yes, so that it will alert if 'no opener/no referrer' has not been added

**Comment by presidentbeef** [comment]
Addressed by optional check added in #1367
