### ISSUE TITLE
ActiveStorage::Filename#sanitized false positive for File Access category

### ISSUE THREAD

**Issue by santiagodoldan** [presidentbeef/brakeman#1348]
### Background

Brakeman version: 4.4.0
Rails version: 2.3.18
Ruby version: 2.3.7

#### False Positive

```
Confidence: Weak
Category: File Access
Check: SendFile
Message: Parameter value used in file name
Code: send_file("path/to/csv/#{ActiveStorage::Filename.new(params[:test]).sanitized}.csv", :disposition => "attachment", :encoding => "utf8", :filename => ("#{ActiveStorage::Filename.new(params[:test]).sanitized}.csv"))
```

Relevant code:

`ActiveStorage::Filename.new(params[:test]).sanitized`

_Why might this be a false positive?_

I copied `ActiveStorage::Filename` implementation to prevent `File Access` attacks (https://edgeapi.rubyonrails.org/classes/ActiveStorage/Filename.html#method-i-sanitized), I was expecting that this change was going to fix all File Access brakeman errors, but they are still there.

Not sure if this is something because I'm not running Rails 5 or if it is something that we can change in Brakeman to not report File Access errors when `sanitized` method is used.

Thanks for the great gem 🙌

**Comment by presidentbeef** [comment]
Hi @santiagodoldan - thank you for reporting this issue.

I was not aware of `ActiveStorage::Filename#sanitized`, so Brakeman does not currently handle it.

Also - Rails 2.3.18?? And it works on Ruby 2.3???

**Comment by presidentbeef** [comment]
> And it works on Ruby 2.3???

I guess probably you are just running Brakeman with that version, not your Rails app :D

**Comment by santiagodoldan** [comment]
@presidentbeef to be more precise, I'm using 2.3.18.24 (https://makandracards.com/railslts/23706-rails-2-3-lts-changelog), this one has support for even ruby 2.5.

I'm glad that this is something that could be added to brakeman then, if you think this is something not that hard to implement, please let me know what pieces should I take care of and I will create a PR.

**Comment by presidentbeef** [comment]
This shouldn't be too difficult, actually. It's actually very similar to https://github.com/presidentbeef/brakeman/pull/1244 and you can use that as a template.

The change should be made in `CheckFileAccess`.

I believe any value from `ActiveStorage::Filename.new` should be safe, since `to_js` and `to_s` also call `sanitized`.

**Comment by tejasbubane** [comment]
I have raised a PR to fix this.
