### ISSUE TITLE
UnscopedFind doesn't work when used with --only-files

### ISSUE THREAD

**Issue by Intrepidd** [presidentbeef/brakeman#1366]
### Background

Brakeman version: 4.5.0
Rails version: 5.2.2.1
Ruby version: 2.5.3p105

### Issue

When using `CheckUnscopedFind` in relation with `--only-files` (pronto-brakeman), the unscoped finds are not reported.

Is this because the models are not found in this context ?

Could we maybe have an option to preload model definitions but not report errors on them ?

The use case is simple : I'd like to have unscoped finds show up in the pronto-brakeman check.

Thanks !

**Comment by presidentbeef** [comment]
Yet another example of why `--only-files` was a bad decision. 😞 

> Is this because the models are not found in this context ?

Yes, exactly.

> Could we maybe have an option to preload model definitions but not report errors on them ?

This doesn't sound like the right solution to me...

> The use case is simple : I'd like to have unscoped finds show up in the pronto-brakeman check.

Many checks vary in their results if Brakeman doesn't get a global view of the application.

These seem to be the desired behaviors for git hooks, etc:

1. Don't spend time scanning the entire application
2. Don't report warnings from unchanged files
3. Report same results as a full scan

(Note Brakeman *does* support incremental scans but they require keeping Brakeman alive in a running process - e.g. guard-brakeman.).

1 and 3 are fundamentally incompatible for Brakeman. (See https://github.com/w0rp/ale/pull/2182 as well).

However, 2 and 3 could be accomplished by filtering the results after doing a full scan. This could be a new option.

**Comment by Intrepidd** [comment]
> However, 2 and 3 could be accomplished by filtering the results after doing a full scan. This could be a new option.

sounds great ! It could also be done straight from `pronto-brakeman`, in any case `pronto-brakeman` will have to be patched for this behaviour to work.

I might open a PR there to handle that

**Comment by presidentbeef** [comment]
This reminded me that I had done some work to allow incremental *re*scans but never followed through. It looks to me like this might be a viable path.

In essence:

- Do initial scan
- Serialize relevant information to a file
- Subsequent scans can utilize that information to do incremental scans

The one part that I'm not sure about is managing that serialized file. Seems like a security risk to have it sitting around.

**Comment by presidentbeef** [comment]
Closing because any future work would be for #1368
