### ISSUE TITLE
Using Brakeman to analyse a single file

### ISSUE THREAD

**Issue by TomasBarry** [presidentbeef/brakeman#1380]
I would like to be able to run Brakeman on a single file instead of having to wait for the entire process to run so that I can more quickly know whether I have fixed the issue reported by Brakeman. Being able to run:

```bash
brakeman /path/to/file.rb
```

To run Brakeman on a single file would be very useful.

Is this at all possible?

**Comment by presidentbeef** [comment]
Hi @TomasBarry -

I think it's best to point you at https://github.com/presidentbeef/brakeman/issues/1368 for an explanation.
