### ISSUE TITLE
Add release dates to CHANGES.md

### ISSUE THREAD

**Issue by presidentbeef** [presidentbeef/brakeman#1385]
It's common to put the release date next to the release version (e.g. 
https://keepachangelog.com/en/1.0.0/).

Canonical release dates are available at https://rubygems.org/gems/brakeman/versions/

https://github.com/presidentbeef/brakeman/releases is not 100% accurate.

**Comment by sabrinaleeW** [comment]
Hey - new to open-source contribution and would like to help you out with this

**Comment by presidentbeef** [comment]
@sabrinaleeW Great!

**Comment by presidentbeef** [comment]
Looks like this is still available for anyone who wants an easy contribution.

**Comment by presidentbeef** [comment]
Closed by #1418
