### ISSUE TITLE
Brakeman's Docker image is not updated with each gem release

### ISSUE THREAD

**Issue by JacobEvelyn** [presidentbeef/brakeman#1413]
We use Brakeman in our CI system and run it via Docker (we used to just `gem install` the latest but ran into issues with various parts of our CI machines supporting only older versions of Ruby, and Docker was much easier for us).

We recently noticed that the Brakeman Docker image hasn't been updated for the last four Brakeman releases. In addition to updating it this once, I'm wondering if you can incorporate this into your gem release process so it doesn't happen again each time. (I didn't see any "releasing instructions" or build tools in this repo—`build.rb` didn't have many of the gem release steps I'd expected—or I would've made a PR.)

Thanks!

**Comment by presidentbeef** [comment]
Docker images are supposed to be built automatically... however it seems that a while back DockerHub changed what GitHub permissions they want (to be way more intrusive, of course) and I wasn't aware that builds were failing.

Anyway, builds should happen automatically again and I set up email notifications for failures.
