### ISSUE TITLE
Version 4.7.1 not released

### ISSUE THREAD

**Issue by plribeiro3000** [presidentbeef/brakeman#1422]
Looking to solve a issue i have in one of my projects i've found #1132 

It states the issue was fixed and was released under `4.7.1` tag bug this version is not on rubygems.

Could you please release it to rubygems?

Thanks!

**Comment by presidentbeef** [comment]
4.7.1 is definitely released: https://rubygems.org/gems/brakeman/versions/4.7.1

But the issue you reference was fixed two years ago in Brakeman 4.1.0: https://brakemanscanner.org/blog/2017/12/12/brakeman-4-dot-1-0-released

**Comment by plribeiro3000** [comment]
Ouch! Thanks!
