### ISSUE TITLE
Unicode warnings when running the brakeman and rubocop rake tasks together

### ISSUE THREAD

**Issue by dylnclrk** [presidentbeef/brakeman#1424]
⚠️ *Note: I filed this as an issue on the Rubocop project (https://github.com/rubocop-hq/rubocop/issues/7475)*

### Background

Brakeman version: 4.7.1
Rails version: 6.0.0
Ruby version: 2.6.2

Link to demo Rails application code: https://github.com/dylnclrk/rubocop-brakeman-warning-reproduciton

### Issue

My project has [`rubocop`](https://github.com/dylnclrk/rubocop-brakeman-warning-reproduciton/blob/af15455b30a32827c9b72d7341a68fe572ed73d2/lib/tasks/rubocop.rake) and [`brakeman`](https://github.com/dylnclrk/rubocop-brakeman-warning-reproduciton/blob/af15455b30a32827c9b72d7341a68fe572ed73d2/lib/tasks/brakeman.rake) rake tasks. And the default rake task is set up to run them both. When I set it to run rubocop first, brakeman prints a bunch of warnings like: `warning: already initialized constant Unicode::DisplayWidth::VERSION`

However, when I run them in the other order, I don't see any of this output.

I'm not sure why this is happening, but it makes the rake task output slightly harder to visually parse, and other errors harder to see. Does anyone know what's going on here? Thanks!

#### Output below...

```
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:3: warning: already initialized constant Unicode::DisplayWidth::VERSION
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:3: warning: previous definition of VERSION was here
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:4: warning: already initialized constant Unicode::DisplayWidth::UNICODE_VERSION
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:4: warning: previous definition of UNICODE_VERSION was here
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:5: warning: already initialized constant Unicode::DisplayWidth::DATA_DIRECTORY
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:5: warning: previous definition of DATA_DIRECTORY was here
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:6: warning: already initialized constant Unicode::DisplayWidth::INDEX_FILENAME
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/constants.rb:6: warning: previous definition of INDEX_FILENAME was here
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/index.rb:9: warning: already initialized constant Unicode::DisplayWidth::INDEX
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width/index.rb:9: warning: previous definition of INDEX was here
/…/lib/ruby/gems/2.6.0/gems/brakeman-4.7.1/bundle/ruby/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width.rb:6: warning: already initialized constant Unicode::DisplayWidth::DEPTHS
/…/lib/ruby/gems/2.6.0/gems/unicode-display_width-1.6.0/lib/unicode/display_width.rb:6: warning: previous definition of DEPTHS was here
```

**Comment by dylnclrk** [comment]
I just took a look at the suggested way to add brakeman and rubocop rake tasks, from the docs, and realized I was not following conventions. Here are the [brakeman docs](https://brakemanscanner.org/docs/rake/), and [rubocop docs](https://docs.rubocop.org/en/stable/integration_with_other_tools/#rake-integration) on setting up rake tasks. 

I updated the sample project's Rakefile to follow the suggestions (https://github.com/dylnclrk/rubocop-brakeman-warning-reproduciton/commit/b3013e0e85c28a397e85dc0f75c17add27413f6e). And I'm still seeing the warnings.

**Comment by presidentbeef** [comment]
This is because Brakeman vendors its dependencies and then Rubocop is probably also loading the same libraries. If Brakeman goes first, no problem. But if Rubocop goes first, then Brakeman will load its own version of `unicode-display_width` and the namespaces clash.

Running Brakeman from Rake is not really recommended, but if you do you might have better luck with the `brakeman-lib` gem which does not bundle its dependencies.

**Comment by dylnclrk** [comment]
Ahh, thank you for explaining. I totally missed the note at the top of the docs when I was implementing the rake task.

I’ll try using brakeman-lib or running brakeman in a different way.

Thanks for maintaining such a great project.
