### ISSUE TITLE
Instances of `params.permit!` not always being caught.

### ISSUE THREAD

**Issue by jsgarvin** [presidentbeef/brakeman#1426]
### Background

Brakeman version: 4.6.1
Rails version: 5.1.7
Ruby version: 2.6.3

### Issue

What problem are you seeing?

After adding Brakeman to a large legacy app, we discovered a few instances where Brakeman's MassAssignment check is not always catching instances of `params.permit!`.   The following scenarios seem to get missed.

```
 # The call to .instance_method seems to be what trips Brakeman up here.
SomeService.new(params: params.permit!).instance_method 

# .merge and apparently any other valid method call here also trips up Brakeman.
params.permit!.merge({ some: 'hash' })

**Comment by presidentbeef** [comment]
Yep - thank you for reporting!
