### ISSUE TITLE
Broken ruby_parser version

### ISSUE THREAD

**Issue by epoberezhny** [presidentbeef/brakeman#1429]
### Background

Brakeman version: 4.7.1
Rails version: 5.2.2.1
Ruby version: 2.6.5

#### Parse Error

Could you please rebuild brakeman with the 13.4.1 version of `ruby_parser`, because the 13.4.0 version is broken? I can not use brakeman due to https://github.com/seattlerb/ruby_parser/issues/299

**Comment by presidentbeef** [comment]
Hi @epoberezhny. I don't know when I will do another release. In the meantime, I suggest using the [`brakeman-lib`](https://rubygems.org/gems/brakeman-lib) gem and then you can install the version of `ruby_parser` that works for you.

**Comment by epoberezhny** [comment]
Hi @presidentbeef ! Thanks for the quick answer. I look forward to a new release

**Comment by presidentbeef** [comment]
Brakeman 4.7.2 vendors the latest `ruby_parser` 3.14.1.

**Comment by epoberezhny** [comment]
Awesome, thanks!
