### ISSUE TITLE
False Negative - UnsafeReflection

### ISSUE THREAD

**Issue by aclemons** [presidentbeef/brakeman#1438]
### Background

Brakeman version: 4.7.2
Rails version: 5.2.2
Ruby version: 2.6.3

#### False negative

Relevant code (simplified):

```ruby
  def create
    lookup_type(params[:type]).new
  end

  private

  def lookup_type(type_name)
    type_name.constantize
  end
```

_Why might this be a false negative?_

This code is directly reflecting on user input without a whitelist, but is not being flagged by brakeman.

Adding this code to widget_controller.rb does not get flagged in the minitest suite.

We've attempted to walk back through the code and identify the root cause here, but were unsuccessful. The code for `CheckRender` does flag code of this sort when the parameter is indirected, i.e. (with weak confidence):

```ruby
  def create
    render :partial => lookup_partial(params[:partial_name])
  end

  private

  def lookup_partial(partial_name)
    partial_name
  end
```

We ended up in call_index.rb, find_call. The paths for the two checks are different - in UnsafeReflection params is not part of the call:

UnsafeReflection:
`{:target=>:type_name, :method=>:constantize, :call=>s(:call, s(:lvar, :type_name), :constantize), :nested=>false, :chain=>[:type_name, :constantize], :location=>{:type=>:class, :class=>:"ThingController", :method=>:channel_type_from_name, :file=>#<Brakeman::FilePath:0x000055bb40415860 @absolute="/home/app/code/app/controllers/thing_controller.rb", @relative="app/controllers/thing_controller.rb", @hash=1444716249268233294>}, :parent=>nil}`

CheckRender:
`{:target=>nil, :method=>:render, :call=>s(:render, :partial, s(:call, nil, :select_form_partial, s(:call, s(:call, s(:params), :[], s(:lit, :site_service_request)), :[], s(:lit, :type))), s(:hash)), :nested=>false, :location=>{:type=>:class, :class=>:"ThingController", :method=>:form, :file=>#<Brakeman::FilePath:0x0000563d950b1ae8 @absolute="/home/app/code/app/controllers/thing_controller.rb", @relative="controllers/thing_controller.rb", @hash=2535063532765
245519>}, :parent=>nil}`

Should brakeman be flagging this usage of constantize?

**Comment by aclemons** [comment]
And just to clarify, brakeman does of course flag this unsafe reflection if there is no method call between.

```
def create
    params[:type].constantize.new
  end
```

**Comment by presidentbeef** [comment]
Hi @aclemons - I appreciate you digging in here.

This behavior is expected in Brakeman. Brakeman does not have general interprocedural analysis (only specific controller->view stuff), so it does not know what the call to `lookup_partial` is doing.

There is an implementation of more general (but still limited) interprocedural analysis for Brakeman but I sold it to Synopsys with Brakeman Pro :(
