### ISSUE TITLE
https://brakemanscanner.org/docs/options/ still documents --rake

### ISSUE THREAD

**Issue by kwerle** [presidentbeef/brakeman#1444]
https://brakemanscanner.org/docs/options/

```
To generate a Rake task to run Brakeman:

brakeman --rake
Note this is not recommended, since Rake will load your entire Rails app, which is not necessary for Brakeman and may cause library conflicts.
```

Looks like this is no longer an option.

**Comment by presidentbeef** [comment]
Correct, the option was removed in Brakeman 3.6.2: https://brakemanscanner.org/blog/2017/05/19/brakeman-3-dot-6-2-released

I have removed it from the documentation on the site, thanks!

You can refer to https://brakemanscanner.org/docs/rake/ if this approach is desired.
