### ISSUE TITLE
issue mitgations

### ISSUE THREAD

**Issue by JStyle21** [presidentbeef/brakeman#1445]
Hi,

Does brakeman currently provide mitigations for found issues?

**Comment by presidentbeef** [comment]
I am assuming you mean remediation information?

The best we have at the moment is on https://brakemanscanner.org/docs/warning_types/. I will admit it's not the most verbose/complete information at the moment.

Warnings are linked to relevant documentation in the HTML, Markdown, and JSON report formats.
