### ISSUE TITLE
Markdown report is missing "Confidence" column

### ISSUE THREAD

**Issue by MatheusRich** [presidentbeef/brakeman#1446]
### Background

Brakeman version: brakeman 4.7.2
Rails version: Rails 5.2.2.1
Ruby version: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]

### Issue
When I generate a markdown output, all "Confidence" columns are empty. Generating a .txt or .html output does not show this behavior.

**Comment by presidentbeef** [comment]
Yes, thank you for reporting!
