### ISSUE TITLE
False positive when interpolating hash key in `.where`

### ISSUE THREAD

**Issue by harrylewis** [presidentbeef/brakeman#1447]
### Background

Brakeman version: 4.7.2
Rails version: 4.2.11.1
Ruby version: 2.5.7

#### False Positive

*Full* warning from Brakeman:

```
Confidence: Medium
Category: SQL Injection
Check: SQL
Message: Possible SQL injection
Code: where("is_#{day}" => true)
File: app/models/account.rb
Line: 2
```

Relevant code:

```ruby
class Account < ActiveRecord::Base
  scope scheduled_on, ->(day) { where("is_#{day}" => true) }
```

_Why might this be a false positive?_

I believe this is a false positive because as mentioned in the [Securing Rails Applications](https://guides.rubyonrails.org/security.html#sql-injection-countermeasures) documentation, one countermeasure to preventing SQL injection by string interpolation using the `.where` method is to use a hash-based input. When this is done, the keys/columns and values are automatically escaped.

In this case, the argument to `.where` is a hash, despite string interpolation happening straight in the main argument. Interestingly, modifying this to include a call to `#to_sym` suppresses the warning, as shown below.

```ruby
scope scheduled_on, ->(day) { where("is_#{day}".to_sym => true) }
```

I'm curious to hear your thoughts about this, and whether this is indeed a false positive or not, and if so, whether anything can be done about this.

Note this may be similar to #1273. Please advise if this is the case and I can follow up on your answer there.

**Comment by presidentbeef** [comment]
I think #933 is actually more related. I don't _love_ the idea of dynamic column names but it's not really SQL injection, either.

**Comment by harrylewis** [comment]
Thanks for the quick response, Justin. I tried to find a similar question before posting, but it seems I didn't go far enough back into the archives.

I agree with the idea that despite not incurring a possible SQL injection vulnerability, it is potentially unsafe because it allows user-input to change the column that is used in the query. This seems like it warrants more of a case-based assessment.
