### ISSUE TITLE
Invalid email address for the commercial license

### ISSUE THREAD

**Issue by ybiquitous** [presidentbeef/brakeman#1456]
Hi,

I'd like to purchase the commercial license, but the email address `sig-sales-ww@synopsys.com` on the [LICENSE.md](https://github.com/presidentbeef/brakeman/blob/17c526b17e3b51765af134fe3134ab65d2258d95/LICENSE.md) seems invalid.

I've got the following error when I sent a message to it:

> (reason: 550 5.1.1 <sig-sales-ww@synopsys.com>: Recipient address rejected: undeliverable address: Address lookup failed)

Is there a communication way else to contact about the purchase of the commercial license?

**Comment by presidentbeef** [comment]
Hi @ybiquitous, please contact Daniel.Ogburn@synopsys.com or Andreas.Kuehlmann@synopsys.com. Good luck.

**Comment by ybiquitous** [comment]
@presidentbeef Thank you!

**Comment by Lackoftactics** [comment]
@presidentbeef can I still use it to scan commercial application? I understand you can't use it for a feature in `Brekman-as-Service`
