### ISSUE TITLE
Scanning app/services folder

### ISSUE THREAD

**Issue by sean-yeoh** [presidentbeef/brakeman#1458]
Hi, my rails app has a app/services folder, but brakeman doesn't seem to scan the files inside it. Is there an option to scan files in app/services?

**Comment by presidentbeef** [comment]
Hi @sean-yeoh! Are the files in that directory "libraries" or more like Rails engines?

You can try `--add-libs-path app/services` for libraries or `--add-engines-path app/services` for engines.
