### ISSUE TITLE
False negative: Command Injection in render call

### ISSUE THREAD

**Issue by marekciupak** [presidentbeef/brakeman#1459]
### Background

Brakeman version: 4.8.0
Rails version: 6.0.2.1
Ruby version: 2.7.0p0

##### Actual behaviour:

These two command injections remain undetected:

```ruby
# action in a controller
def show
  render text: `#{params.require('name')} some optional text`
  render json: `#{params.require('name')} some optional text`
end
```

It remains undetected when I place it as a value of `text` or `json` argument of `render` method. It allows arbitrary shell code execution with application permissions by sending an appropriate HTTP request, for ex:

```
GET /users/1?name=some%20shell%command;
```

The result of the command is not visible in the HTTP response, but the code is executed.

##### Expected behavior:

The scanner should alert users about potential vulnerabilities:

```
== Warnings ==

Confidence: High
Category: Command Injection
Check: Execute
Message: Possible command injection
Code: `#{params.require("name")} some optional text`
File: app/controllers/users_controller.rb
Line: 15
```

**Comment by presidentbeef** [comment]
@marekciupak Thank you for reporting! :clap:
