### ISSUE TITLE
Allow to output to console and file at the same time

### ISSUE THREAD

**Issue by lumaxis** [presidentbeef/brakeman#1462]
It seems that today, `brakeman` stops outputting warnings or errors to the console as soon as any output file is specified.

Instead, it would be nice to be able to specify both at the same time, `-f text -o report.junit` for example, which would output a plain text version to the console and the XML JUnit format to the `report.junit` file at the same time.

**Comment by presidentbeef** [comment]
Hi @lumaxis - you can do so with `-o /dev/stdout`.

For example:

`brakeman -o /dev/stdout -o report.junit`

You probably want color, too:

`brakeman --color -o /dev/stdout -o report.junit`

**Comment by lumaxis** [comment]
Oh, sweet! I took a super brief look at the code that handles the output but hadn't realized that just specifying `stdout` would work, too.
I'll update #1461 to include this as well, would be a great addition to the docs.

**Comment by lumaxis** [comment]
Ah, bummer. Turns out, our CI server doesn't have `/dev/stdout` available. I guess I'll stick with `cat`ing a plain text file then 🙂
