### ISSUE TITLE
Suppress (or adjust) status output when running in CI

### ISSUE THREAD

**Issue by ianfixes** [presidentbeef/brakeman#1466]
## Problem
The console logs of this program when running in a terminal are great.  But when running in a CI environment (like Jenkins), the output is overwhelmed by status lines:

```
325/337 templates processed
 326/337 templates processed
 327/337 templates processed
 328/337 templates processed
 329/337 templates processed
 330/337 templates processed
 331/337 templates processed
 332/337 templates processed
 333/337 templates processed
 334/337 templates processed
 335/337 templates processed
 336/337 templates processed
Processing models...          
 0/74 files processed
 1/74 files processed
 2/74 files processed
 3/74 files processed
 4/74 files processed
 5/74 files processed
 6/74 files processed
 7/74 files processed
```

## Feature Request

I would like a way to either disable the printing of every single file/controller/etc found, or have some ability to render it as a stream of `.` characters on a single line instead.

## Alternatives considered
These arguments don't have any effect on the status line generation:

* `--no-pager`
* `--summary`
* `-q` (suppresses EVERYTHING)

**Comment by presidentbeef** [comment]
Hi @ianfixes - I believe `--no-progress` is the option you are looking for.

More information on the Brakeman Jenkins plugin (if that's what you are using): https://plugins.jenkins.io/brakeman/

**Comment by ianfixes** [comment]
Aah, my fault.  I missed this line at the top of https://brakemanscanner.org/docs/options/
> This page may or may not be entirely up-to-date. For best results but less information, run `brakeman --help`.
