### ISSUE TITLE
False negative SQLi with the `String#squish` method.

### ISSUE THREAD

**Issue by BuonOmo** [presidentbeef/brakeman#1469]
### Background

Brakeman version: 4.8.0
Rails version: 4.X
Ruby version: 2.7.0preview3

<details open>
<summary>
Whole rails application code:
</summary>

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  def dangerous(user_input)
    ActiveRecord::Base.connection.execute "SELECT * FROM #{user_input}"
  end

  def dangerous_but_squished(user_input)
    ActiveRecord::Base.connection.execute "SELECT * FROM #{user_input}".squish
  end
end
```
</details>

### Issue

Both methods are exposed to SQLi. However, the `User#dangerous_but_squished` isn't reported by Brakeman.

**Comment by presidentbeef** [comment]
Thank you for reporting!

**Comment by BuonOmo** [comment]
Thank you for reactivity! Do you have any idea of when you will push the new version?

**Comment by presidentbeef** [comment]
No date planned but since the last release was February, I'll probably do a small release in the next couple weeks.
