### ISSUE TITLE
[LinkToHref]: No warning is thrown when iterating over array

### ISSUE THREAD

**Issue by linosgian** [presidentbeef/brakeman#1475]
### Background

Brakeman version: master branch
Rails version: 5.X
Ruby version: 2.5.1

### Issue

What problem are you seeing?

I've been using Brakeman for our codebase for a while and I've stumbled upon an issue that concerns the LinkToHref check but might be applicable to other checks too. 

To demonstrate the issue I've added the following diff and then ran the tests:

```
diff --git a/test/apps/rails5/app/controllers/users_controller.rb b/test/apps/rails5/app/controllers/users_controller.rb
index 0e6b9759b..3b7652716 100644
--- a/test/apps/rails5/app/controllers/users_controller.rb
+++ b/test/apps/rails5/app/controllers/users_controller.rb
@@ -10,6 +10,7 @@ class UsersController < ApplicationController
   # GET /users/1
   # GET /users/1.json
   def show
+    @users = User.limit(5)
   end

   # GET /users/new
diff --git a/test/apps/rails5/app/views/users/show.html.erb b/test/apps/rails5/app/views/users/show.html.erb
index 8e0eb0e55..5e5fa3f72 100644
--- a/test/apps/rails5/app/views/users/show.html.erb
+++ b/test/apps/rails5/app/views/users/show.html.erb
@@ -7,6 +7,10 @@
 <%= link_to("xss", url_for(params[:bad])) %>

 <%= link_to(image_tag("icons/twitter-gray.svg"), sanitize(@user.home_page), target: "_blank") %>
+<% @users.each do |user| %>
+  <%= link_to "", user.url %>
+<% end %>
+<%= link_to "", @users.last.url %>

 <%= link_to '', 'something_static', target: '_blank' %> No warning
 <%= link_to '', some_url, target: '_blank' %> Warn
```

If we directly render model parameters a warning is thrown as dictated by the LinkToHref check 
https://github.com/presidentbeef/brakeman/blob/f960e4eadd9899cb27085e5939c88d44576c2671/lib/brakeman/checks/check_link_to_href.rb#L61-L75

False negatives appear when we iterate over the array (`@users`) and refer to the aliased parameter (`user`). It seems that this is related to https://github.com/presidentbeef/brakeman/issues/1272

**Comment by presidentbeef** [comment]
Yes, it's basically the same issue :disappointed:

**Comment by linosgian** [comment]
Alright, I'll close this in favor of #1272 :+1:
