### ISSUE TITLE
Tiny COPYING.md buglet (broken link)

### ISSUE THREAD

**Issue by philmuldoon** [presidentbeef/brakeman#1487]
### Issue

The link in COPYING.md https://github.com/presidentbeef/brakeman/blob/master/LICENSE.md for the Brakeman Public License links (2) are point to `master`. With the github rename, they should point to
https://github.com/presidentbeef/brakeman/blob/main/LICENSE.md

**Comment by presidentbeef** [comment]
Thanks!
