### ISSUE TITLE
Create a check for `method`

### ISSUE THREAD

**Issue by gavingmiller** [presidentbeef/brakeman#1488]
**Is your feature request related to a problem? Please describe.**

The following code does not get flagged as a vulnerability by Brakeman:

```
def show
  (params[:klass].to_s).method(params[:method]).(params[:argument])
end
```

While this minimal example seems overly obvious that it shouldn't be written, Brakeman doesn't flag it at all 😢 (using brakeman 4.8.2)

**Describe the solution you'd like**

It would be great if this got caught by Brakeman! 😁 I believe the main issue here is `method` is dangerous if given user controlled input.

**Comment by presidentbeef** [comment]
:neutral_face: 

Agree, this should be flagged and it is not difficult to do so.
