### ISSUE TITLE
Slim parsing error - valid slim - slashes

### ISSUE THREAD

**Issue by JeremiahChurch** [presidentbeef/brakeman#1490]
### Background

Brakeman version: 4.8.2
Rails version: 6.0.3.2
Ruby version: 2.6.6
Slim 4.1.0

example slim code that is valid and works in-app but not when brakeman is run:
`.pr-2.w-1/2`

slash support was recently added to slim [here](https://github.com/slim-template/slim/pull/841)

change it to `.pr-2 class='w-1/2'` and brakeman will succeed

#### Parse Error

```
== Errors ==

Error: Unexpected text after closed tag   /home/jchurch/project/app/views/user_account_links/show.html.slim, Line 14, Column 13     .w-1/2.pr-2          ^ 
Location: /home/jchurch/project/app/views/user_account_links/show.html.slim:14
```

Minimal example that does not parse:

```slim
.w-1/2
  | example
```

If there is a better place to I should raise this to please point me in the right direction - I saw haml and erb on the parser error page but not slim.

Thank you so much!

**Comment by presidentbeef** [comment]
Hi @JeremiahChurch - thank you for reporting this! Brakeman is [pinned to Slim `<= 4.0.1`](https://github.com/presidentbeef/brakeman/blob/218c1103a3d6eec5e33a3470402a0118269e3909/gem_common.rb#L23). There doesn't appear to be a big difference between `4.0.1` and `4.1.0`, so it is probably okay to bump the version. I will need to test to confirm.
