### ISSUE TITLE
Brakeman does not understand enums

### ISSUE THREAD

**Issue by obromios** [presidentbeef/brakeman#1492]
### Background

Brakeman version: 4.8.2
Rails version: 6.0.3.2
Ruby version: 2.6.6

### Rails application code

Consider a User model

```
    # app/models/user.rb
    class User
       enum status: [:sad, :bored, :happy]
    end
```

In a controller, I want to receive ```params[:status]``` and return all users with that status

i.e.

```
    # app/controllers/users_controller.rb
    class UsersController << ApplicationController
       def index_status
          status = "#{params[:status]}"
          if User.statuses.include? status
             @status = status.to_sym
             @countries = User.send(@status)
          else
            redirect_to root_path, notice: 'Invalid status'
        end
    end
```
*** What problem are you seeing?

The code works, but ```Brakeman``` gives me a ```dangerous send - User controlled method execution ``` warning for the line

    @countries = User.send(@status)

This was asked as a question on [SO](https://stackoverflow.com/questions/62809047/how-to-safely-use-a-param-variable-to-execute-an-enum-search), and [Justin](https://stackoverflow.com/users/194084/justin) posted a comment that Brakeman does not understand enums

**Comment by presidentbeef** [comment]
Fixed by #1618
