### ISSUE TITLE
Catching version when using `ActiveRecord` without rails!

### ISSUE THREAD

**Issue by BuonOmo** [presidentbeef/brakeman#1494]
Hi,

And thanks for the great work 🎸

We've been working with brakeman a lot in our team. However, we're mostly using sinatra with activerecord and there are some issues with the rails version we are using.

This lead us to having report for issues that are no longer present since rails 4.

Since activerecord and rails share their versions, i'd suggest appending `gem_version(:activerecord)` to the next line:

https://github.com/presidentbeef/brakeman/blob/d6421d4878ba7b13b5c52dca051360d8b4d1e3eb/lib/brakeman/tracker/config.rb#L82

This would be a great benefit for all activerecord users IMHO.

What do you think?

**Comment by presidentbeef** [comment]
Hi @BuonOmo - Are you running Brakeman on non-Rails applications? I'm not sure I want to further encourage that, since it's not a well-supported use case. (I mean, it's fine as long as you know that :grinning:)

**Comment by BuonOmo** [comment]
@presidentbeef yes we've been using brakeman on a Sinatra + ActiveRecord stack for a while with production applications!

It's working pretty well since a lot of security vulnerabilities we may introduce directly come from ActiveRecord. Moreover, there are similarities in the structure, and we still use an `app/models` directory for instance.

The only issue we've encountered yet is the one mentioned here: Brakeman thinks we're using Rails when we're using ActiveRecord 5.

Maybe another alternative would be to default to Rails 5 versions since lower versions [are not supported anymore](https://guides.rubyonrails.org/maintenance_policy.html). However, I still think grepping ActiveRecord's version would be nice since if one wants to use it in an ActiveRecord non Rails app, one expects it to still detect the most correct version!

**Comment by presidentbeef** [comment]
> Maybe another alternative would be to default to Rails 5 versions since lower versions are not supported anymore.

I know it's a little crazy, but the older the Rails app, the less likely it is to have a detectable Rails version. It's not a bad idea, but not sure I want to change the default behavior on that.

That being said, I don't think there is much harm in also checking the ActiveRecord version, especially since some of the SQL injection code depends on the version.

**Comment by BuonOmo** [comment]
> I know it's a little crazy, but the older the Rails app, the less likely it is to have a detectable Rails version. It's not a bad idea, but not sure I want to change the default behavior on that.

Sadly, it makes a lot of sense.

> That being said, I don't think there is much harm in also checking the ActiveRecord version, especially since some of the SQL injection code depends on the version.

Does it mean you are welcoming a PR? I'd be glad to do it by the end of the week!

**Comment by presidentbeef** [comment]
> Does it mean you are welcoming a PR?

Yep!
