### ISSUE TITLE
False Positive SQL Inject for Arel.sql

### ISSUE THREAD

**Issue by uxxman** [presidentbeef/brakeman#1504]
### Background

Brakeman version: 4.9.0
Rails version: 6.0.3.2
Ruby version: 2.7.1

### *Full* warning from Brakeman:
```json
{
      "warning_type": "SQL Injection",
      "warning_code": 0,
      "fingerprint": "74097da14ccb97a3aa3773cc63b1630e44f7abf5a72843dbb585fe4c58352fe1",
      "check_name": "SQL",
      "message": "Possible SQL injection",
      "file": "app/models/category.rb",
      "line": 2,
      "link": "https://brakemanscanner.org/docs/warning_types/sql_injection/",
      "code": "Arel.sql(\"name #{direction}\")",
      "render_path": null,
      "location": {
        "type": "method",
        "class": "Category",
        "method": null
      },
      "user_input": "direction",
      "confidence": "Medium",
      "note": ""
}
```

### Relevant code:

```ruby
class Category < ApplicationRecord
  scope :order_name, -> (direction) { order(Arel.sql("name #{direction}")) }
end
```

**Comment by presidentbeef** [comment]
Hi @uxxman,

`Arel.sql` allows any SQL. So if an attacker can control `direction`, then they can inject SQL into this query in the `order` clause. On top of that, `order` also allows any SQL string!

Brakeman doesn't know where `order_name` might be called from and what `direction` might be, so it generates a warning to be safe.

A safe approach would be:

```ruby
order(name: direction)
```

Rails will ensure `direction` is only `asc` or `desc` and therefore prevent injection.

**Comment by uxxman** [comment]
Hi @presidentbeef Thank you responding. I understand that **order(name: direction)** is the preferred way for a normal column, but my issue is that I have a JSONB column. So, the scope is like this; 

```ruby
scope :order_name, -> (direction) { order(Arel.sql("name->'#{I18n.locale}' #{direction}")) }
```

Now, all variables involved are local not passed in by an end user.
