### ISSUE TITLE
Create check for `to_proc`

### ISSUE THREAD

**Issue by gavingmiller** [presidentbeef/brakeman#1508]
Again referencing the blog post on the [12 ways to call a method in Ruby](https://www.notonlycode.org/12-ways-to-call-a-method-in-ruby/). The method `to_proc` does not get caught by brakeman as well: (way # 9 in the reference post):

```
params[:method].to_sym.to_proc.call(Kernel)
```

The above when called with `method=gets` will DOS the application and does not currently get caught by brakeman.

Related issue: https://github.com/presidentbeef/brakeman/issues/1507

**Comment by presidentbeef** [comment]
Hi @gavingmiller - thank you for suggesting these!
