### ISSUE TITLE
`latest` brakeman image in docker hub is older then `4.9.0` image

### ISSUE THREAD

**Issue by yevgeniypopov** [presidentbeef/brakeman#1510]
### Background

Brakeman version: v4.9.0

### Issue

According to github, latest version of brakeman is 4.9.0 but when I pull latest brakeman via docker it shows 4.8.2 version:
```
eugene-work@eugene-desktop:~/test$ docker pull presidentbeef/brakeman
eugene-work@eugene-desktop:~/test$ docker run -v "$(pwd)":/code presidentbeef/brakeman
...
== Brakeman Report ==

Application Path: /code
Rails Version: 5.2.3
Brakeman Version: 4.8.2
Scan Date: 2020-08-24 12:03:19 +0000
```
It looks like `latest` tag in docker hub is older then `4.9.0` tag - https://hub.docker.com/r/presidentbeef/brakeman/tags

Also it has different digest and size then 4.8.2 tag
![Screenshot from 2020-08-24 15-57-44](https://user-images.githubusercontent.com/7941027/91047375-9b7a9500-e622-11ea-897e-e61c3e353f76.png)

**Comment by presidentbeef** [comment]
@yevgeniypopov Fixed! Thank you for letting me know.
