### ISSUE TITLE
Allow errors to be ignored like warnings

### ISSUE THREAD

**Issue by mashedkeyboard** [presidentbeef/brakeman#1514]
**Is your feature request related to a problem? Please describe.**
I've reported [a bug in ruby-parser](https://github.com/seattlerb/ruby_parser/issues/309) to do with date ranges, which should hopefully get sorted soon enough. However, while that's there, unlike a warning from Brakeman which I can add to the `brakeman.ignore` file, there's no way to prevent a Brakeman run from failing. This means I can either have all my tests showing as failing, or I need to take Brakeman out of my CI pipeline temporarily - neither of which is a great solution.

**Describe the solution you'd like**
Having the ability to mark specific errors in specific files as acceptable would help to resolve this issue, although it would need to be caveated clearly with warnings that the file may not be scanned as a consequence.

**Describe alternatives you've considered**
I can't see any obvious alternatives here that would attack the problem in the same way - very open to ideas, though!

**Comment by presidentbeef** [comment]
Hi @mashedkeyboard!

For parse errors, the best approach is probably to skip the file (Brakeman can't process a partial file). You can use the `--skip-files` option to do so.

Alternatively, you can use `--no-exit-on-error` to avoid failing builds on Brakeman errors, but still fail on vulnerability warnings.
