### ISSUE TITLE
Pagy: UnescapedOutputs

### ISSUE THREAD

**Issue by joshRpowell** [presidentbeef/brakeman#1519]
Hello! Thanks for the great tool! 
We started using [Pagy](https://github.com/ddnexus/pagy) recently and had to add this to our `brakeman.ignore`.

### Background

Brakeman version: 4.5.1.1 (pro)
Rails version: 6.0.3.3
Ruby version: 2.7.1

Link to Rails application code: ?
per Pagy docs, anywhere we call:

```erb
<%== pagy_nav(@pagy) %>
```
https://github.com/ddnexus/pagy/blame/f09a80a40e238e18272f4b7703c607a1a902aea5/README.md#L96

#### False Positive

*Full* warning from Brakeman: `?`

https://github.com/ddnexus/pagy/issues/243#issue-626057678

Relevant code:

https://github.com/ddnexus/pagy/blob/f09a80a40e238e18272f4b7703c607a1a902aea5/lib/pagy/frontend.rb#L36

```ruby
    def pagy_nav(pagy)
      link, p_prev, p_next = pagy_link_proc(pagy), pagy.prev, pagy.next

      html = EMPTY + (p_prev ? %(<span class="page prev">#{link.call p_prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"'}</span> )
                             : %(<span class="page prev disabled">#{pagy_t('pagy.nav.prev')}</span> ))
      pagy.series.each do |item|  # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
        html << if    item.is_a?(Integer); %(<span class="page">#{link.call item}</span> )               # page link
                elsif item.is_a?(String) ; %(<span class="page active">#{item}</span> )                  # current page
                elsif item == :gap       ; %(<span class="page gap">#{pagy_t('pagy.nav.gap')}</span> )   # page gap
                end
      end
      html << (p_next ? %(<span class="page next">#{link.call p_next, pagy_t('pagy.nav.next'), 'aria-label="next"'}</span>)
                      : %(<span class="page next disabled">#{pagy_t('pagy.nav.next')}</span>))
      %(<nav class="pagy-nav pagination" role="navigation" aria-label="pager">#{html}</nav>)
    end
```

_Why might this be a false positive?_

https://github.com/ddnexus/pagy/issues/243#issuecomment-635430483

**Comment by presidentbeef** [comment]
Hi @joshRpowell,

To be clear, Brakeman doesn't know what `pagy_nav` does. It just sees the use of `<%==` and warns about it. The `UnescapedOutputs` check is very noisy, hence the "info" level warning. For use with Rails, pagy could call `.html_safe` on strings it returns so you don't have to use `<%==`.

That being said, you can try setting `--safe-methods pagy_nav`. I think `UnescapedOutputs` will ignore it then.
