### ISSUE TITLE
Running brakeman on an engine repo

### ISSUE THREAD

**Issue by mrcasals** [presidentbeef/brakeman#1522]
Hi!

I'm developing for https://github.com/decidim/decidim and I'd like to try brakeman there. Decidim is a repo with a bunch of Rails engines, which get added as a dependency to a barebones Rails app in order to be used. For developing we create a deveelopment Rails app which use the local copy of the project files as dependency.

I tried running `brakeman` in the repo folder, but it fails to load saying it can't find a Rails app. I've also tried using `brakeman` to the development app and then supply an engine path with the `add-engines-path` option, but it doesn't seem to load anything from the project... 

Is there a way to use it with this setup? Or should we wait until #1520 is released?

Thanks!

**Comment by presidentbeef** [comment]
Hi @mrcasals -

It's kind of a hack, but you should be able to use `--force-scan` and `--add-engines-path` with all the paths (note quotes):

```
brakeman --force-scan --add-engines-path 'decdim*'
```

And yes, the next release will address this (although you may still need to use `--force-scan`... haven't thought about this yet).

**Comment by mrcasals** [comment]
Ooooh awesome, thanks!
