### ISSUE TITLE
Rails 6.1 removes parent_name and replaces it with module_parent_name

### ISSUE THREAD

**Issue by skunkworker** [presidentbeef/brakeman#1526]
### Background

Brakeman version: 4.10.0
Rails version: 6.0
Ruby version: 2.5

### Issue

What problem are you seeing?
- There is a deprecation warning in Rails 6.0 that indicates that `Module#parent_name` will be removed in 6.1 and replaced with `Module#module_parent_name`

```
DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. `parent_name` is deprecated and will be removed in Rails 6.1. Called from environment.rb
```

**Comment by presidentbeef** [comment]
Hi @skunkworker - I'm not sure how this is related to Brakeman. Brakeman doesn't depend on any Rails code, so Rails deprecation warnings should have nothing to do with Brakeman.

Brakeman does [define and use a method named `parent_name`](https://github.com/presidentbeef/brakeman/blob/21e2c80fa587833c4d3eddaf87bf107dc1bea820/lib/ruby_parser/bm_sexp.rb#L558) but if Rails is warning about that, it's mistaken.

Also, Brakeman doesn't have any files named `environment.rb`.

Is there any more context you can provide for this message? Thanks!

**Comment by skunkworker** [comment]
I apologize I'm wrong on this. I was going through all of the gems in my gemdir for a rails 6.0 codebase and I jumped the gun too soon.

**Comment by presidentbeef** [comment]
No worries!
