### ISSUE TITLE
Renderables dynamic render path false positive

### ISSUE THREAD

**Issue by bradparker** [presidentbeef/brakeman#1529]
Firstly, thanks so much for this tool. We're ([Five Good Friends](https://github.com/fivegoodfriends/)) grateful to have something like this to help us make sure we're doing all we can to keep the people who use our software safe :).

### Background

Brakeman version: 4.10
Rails version: 6.0.3.4
Ruby version: 2.6.6

Link to Rails application code: Sorry, closed-source. But I've added [a failing spec in a Brakeman fork](https://github.com/bradparker/brakeman/commit/d748f7bf03f0188e4dbc8daad469615fadd3b837)

#### False Positive

*Full* warning from Brakeman:

```json
{
  "warning_type": "Dynamic Render Path",
  "warning_code": 15,
  "fingerprint": "9485294198b3a144dd293dc9f26cc7653da664e5e6d79d15fcac79750a4b0228",
  "check_name": "Render",
  "message": "Render path contains parameter value",
  "file": "/Users/brad.parker/Code/presidentbeef/brakeman/test/apps/rails6/app/controllers/groups_controller.rb",
  "line": 12,
  "link": "https://brakemanscanner.org/docs/warning_types/dynamic_render_path/",
  "code": "render(action => TestRenderer.new(params.require(\"name\")), {})",
  "render_path": null,
  "location": {
    "type": "method",
    "class": "GroupsController",
    "method": "render_commands"
  },
  "user_input": "params.require(\"name\")",
  "confidence": "Weak"
}
```

Relevant code:

```ruby
def render_commands
  render(TestRenderer.new(params.require('name')))
end
```

_Why might this be a false positive?_

[Rails 6.1 now supports passing `Renderable`s to `render`](https://github.com/rails/rails/blob/b5b078cd99b0107fd8e31ff619578e5321182e0a/actionview/lib/action_view/template/renderable.rb). We've started using [Github's ViewComponent gem](https://github.com/github/view_component) which makes use of this new Rails feature.

I'm not sure what changes could be made to `CheckRender` but I'd be happy to take a swing at it with some pointers. It seems like there might be a way to add something similar to the `input.type == :model` check, is this on the right track?

Thanks again :)

**Comment by presidentbeef** [comment]
Hi @bradparker! Thank you for bringing this up.

In this case Brakeman is warning about `params.require`. It's a weak confidence warning because `params` is an argument, not being used directly. And also `TestRenderer` isn't a model, right? So unfortunately just checking the `input.type` won't work here.

My initial thought is just check if the `action` argument is a call to `new` on a class that inherits from ` ViewComponent::Base` or `ActionView::Template::Renderable`.

My second thought is that Brakeman should be less sensitive about query parameters used as arguments like this :smile: but it gets complicated to distinguish this kind of use from e.g. string building which we do want to warn about, since they look the same in the AST.

**Comment by bradparker** [comment]
Thanks for having a look :)

> My initial thought is just check if the `action` argument is a call to `new` on a class that inherits from `ViewComponent::Base` or `ActionView::Template::Renderable`.

Awesome, when we're back in cool-down I'll have another look from this starting point and let you know how I go.

> My second thought is that Brakeman should be less sensitive about query parameters used as arguments like this 😄 but it gets complicated to distinguish this kind of use from e.g. string building which we do want to warn about, since they look the same in the AST.

I can only imagine how complex this could get 😅

**Comment by joelhawksley** [comment]
> My initial thought is just check if the action argument is a call to new on a class that inherits from ViewComponent::Base or ActionView::Template::Renderable.

As a small refinement, the Rails API for this feature simply requires that the _renderable_ object responds to `#render_in`. Perhaps we could check for that?

**Comment by bradparker** [comment]
> ... simply requires that the renderable object responds to #render_in. Perhaps we could check for that?

That's what I'd be keen to try and implement. [The failing example](https://github.com/bradparker/brakeman/commit/d748f7bf03f0188e4dbc8daad469615fadd3b837) has only that constraint. Sorry I haven't had the time to get to this just yet. It might take me a little time to get up to speed enough to traverse the AST to get that info. That's what had me thinking I'd pull at the `input.type == :model` thread, I assumed it might do similar introspection to populate `#type`. But I really haven't looked into it yet, apologies all 😅

**Comment by presidentbeef** [comment]
You don't need to traverse the AST. 

You can use [`tracker.find_class`](https://github.com/presidentbeef/brakeman/blob/09b66b580d423ed146f3ef67e3cfbbaa6537cb2e/lib/brakeman/tracker.rb#L213) to look up the class information and then check [`#get_method`](https://github.com/presidentbeef/brakeman/blob/09b66b580d423ed146f3ef67e3cfbbaa6537cb2e/lib/brakeman/tracker/collection.rb#L64) on the result to see if the `render_in` method is defined.

I believe that would address the case in the example.

**Comment by bradparker** [comment]
Oh, that all looks awesome! And with `parent` and `includes` ... OK, that looks way easier than what I thought I might have to do 🙏 :D

**Comment by bradparker** [comment]
Whoops! I put a "closes" in that PR but this isn't released yet, so it might want to stay open until then?

**Comment by presidentbeef** [comment]
Issues are closed when PRs are merged, not when releases go out. :+1:
