### ISSUE TITLE
What is the real license of this gem ?

### ISSUE THREAD

**Issue by spuyet** [presidentbeef/brakeman#1550]
Hello,

I see that there is two different license files in this project:
- MIT: https://github.com/presidentbeef/brakeman/blob/main/MIT-LICENSE
- BPUL: https://github.com/presidentbeef/brakeman/blob/main/LICENSE.md

I guess that the second is the right one, could you confirm ?

**Comment by presidentbeef** [comment]
Correct, see https://github.com/presidentbeef/brakeman/blob/main/COPYING.md

Note that "commercial use" means (roughly) selling Brakeman as part of a product. If you are using it for your own purposes, even as an employee of a company on a proprietary code base, that is an acceptable use.
