### ISSUE TITLE
How to detect that a repo is a rails project ?

### ISSUE THREAD

**Issue by nvuillam** [presidentbeef/brakeman#1552]
Hi, I consider integrating Brakeman within [Mega-Linter](https://nvuillam.github.io/mega-linter/), but to do that I need to be able to detect that a repo is a rails project

Is there an easy way to do that ? ( presence of a file with some filename, name of a folder, or even content of json/yml file )

Thanks  :)

**Comment by presidentbeef** [comment]
Hi @nvuillam,

There isn't really a fool-proof way to detect a Rails app. _Usually_ they look pretty standard, with directories called `app`, `config`, `db`, `lib`, `public`, etc., and a `Gemfile` in the root directory. But not always.

A _decent_ way is to check for a `Gemfile` or `Gemfile.lock` with `rails` in it.

Brakeman itself just looks for an `app` directory. If there isn't one, it will quit with exit code `4`.
