### ISSUE TITLE
SQL Injection on sanitize_sql_like

### ISSUE THREAD

**Issue by jkhulme** [presidentbeef/brakeman#1555]
### Background

Brakeman version: 4.10.0
Rails version: 6.0.3.4
Ruby version: 2.7.2

Link to Rails application code: ?
#### False Positive
```
def self.name_contains(search)
  search_sql = Arel.sql("%#{sanitize_sql_like(search)}%")
  order_sql = Arel.sql("#{sanitize_sql(Settings.databases.extensions_schemas.core)}.similarity(name, ?)")
  order_sql = Arel.sql(sanitize_sql_for_order([order_sql, search]))
  where('name ILIKE ?', search_sql).order(order_sql)
end
```

*Full* warning from Brakeman: `?`
```
{
      "warning_type": "SQL Injection",
      "warning_code": 0,
      "fingerprint": "bfeee214036bfb6b50ff4d60de1ebcd0da0d3f855b8f151a6eeea30537eeed66",
      "check_name": "SQL",
      "message": "Possible SQL injection",
      "file": "app/models/list.rb",
      "line": 47,
      "link": "https://brakemanscanner.org/docs/warning_types/sql_injection/",
      "code": "Arel.sql(\"%#{sanitize_sql_like(search)}%\")",
      "render_path": null,
      "location": {
        "type": "method",
        "class": "List",
        "method": "List.name_contains"
      },
      "user_input": "sanitize_sql_like(search)",
      "confidence": "Medium",
      "note": ""
    }
```

Relevant code:
https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/checks/check_sql.rb#L574
https://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_like

_Why might this be a false positive?_
We're using sanitize_sql_like, which is one of the active record sanitization methods which "Sanitizes a string so that it is safe to use within an SQL LIKE statement. This method uses escape_character to escape all occurrences of “", ”_“ and ”%“."
but brakeman is still picking it up as a sql injection risk.  
The method is missing from the ignore list in check_sql.

**Comment by presidentbeef** [comment]
@jkhulme why did you close?
