### ISSUE TITLE
False positive for unsafe send

### ISSUE THREAD

**Issue by obfuscoder** [presidentbeef/brakeman#1561]
### Background

Brakeman version: 5.0.0
Rails version: 5.2
Ruby version: 2.5.5

Link to Rails application code: N/A

#### False Positive

*Full* warning from Brakeman:

Confidence: High
Category: Dangerous Send
Check: Send
Message: User controlled method execution
Code: MyModel.send((params[:scope] or valid_scopes.first))
File: app/controllers/my_controller.rb
Line: 15

Relevant code:

my_controller.rb:

```ruby
      def index
        @scope = params[:scope]
        @scope = valid_scopes.first unless valid_scopes.include?(@scope)

        @result = MyModel.send(@scope).order(id: :desc)
      end
```

scope_helper.rb:

```ruby
def valid_scopes
  @valid_scopes ||= %w[scope1 scope2]
end
```

_Why might this be a false positive?_

The parameter value *scope* is validated against a white list of valid scopes and only used if it is included in the whitelist. Otherwise the first element of the whitelist is used. This should not be reported as vulnerability.

**Comment by baburdick** [comment]
Same issue. Ruby 2.6.6.

**Comment by presidentbeef** [comment]
Yes, unfortunately Brakeman doesn't know what `valid_scopes` does right now. But I hope to address that, maybe in 5.1.

**Comment by baburdick** [comment]
Verified that v5.1.1 no longer exhibits this issue.

**Comment by presidentbeef** [comment]
Really? That's interesting. 🤔

**Comment by dgm** [comment]
Kind of a similar type of thing, 
```
if params[:foo] == 'something'
  Model.send(params[:foo])
end
```

**Comment by presidentbeef** [comment]
@dgm can you open as a separate issue? Thanks!
