### ISSUE TITLE
regex wants \A and \z even though I'm only matching the start

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#1562]
### Background

Brakeman version: 5.0
Rails version: 6.1
Ruby version: 2.7

```
ADDRESS_PATTERN = /\Ahttps?:\/\//.freeze
```

```
== Warnings ==

Confidence: High
Category: Format Validation
Check: ValidationRegex
Message: Insufficient validation for `address` using `/\Ahttps?:\/\//`. Use `\A` and `\z` as anchors
Line: 28
```

**Comment by presidentbeef** [comment]
This is intentional behavior - although I suppose the confidence could be lowered.

The reason Brakeman warns is because anything could come after that pattern - including newlines.

**Comment by grosser** [comment]
so you want it to be `ADDRESS_PATTERN = /\Ahttps?:\/\/.*\z/.freeze` ?

**Comment by presidentbeef** [comment]
Yep.
