### ISSUE TITLE
CheckReverseTabnabbing needs to be more strict.

### ISSUE THREAD

**Issue by Sixeight** [presidentbeef/brakeman#1563]
**Is your feature request related to a problem? Please describe.**

`CheckReverseTabnabbing` checks only method call now. ([here](https://github.com/presidentbeef/brakeman/blob/09b66b580d423ed146f3ef67e3cfbbaa6537cb2e/lib/brakeman/checks/check_reverse_tabnabbing.rb#L30-L36))
Reverse tabnabbing is also common when the user's input is displayed as is. Thus we need to check variable too.

**Describe the solution you'd like**

In addition to strings, variables should also be checked. 
If possible, I would also like to check if it is string-interpolated.

**Describe alternatives you've considered**

Don't be afraid to check String for false positives.

**Comment by presidentbeef** [comment]
@Sixeight thank you for the suggestion... do you have a code example that you'd like Brakeman to warn about?
