### ISSUE TITLE
What's the alternative to HTTP Verb Confusion Check `request.get?`

### ISSUE THREAD

**Issue by vfonic** [presidentbeef/brakeman#1573]
https://brakemanscanner.org/blog/2021/01/26/brakeman-5-dot-0-dot-0-released#http-verb-confusion-check

### Background

Rails Version: 5.2.4.3
Brakeman Version: 5.0.0
Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]

Category: HTTP Verb Confusion
Message: Potential HTTP verb confusion. `HEAD` is routed like `GET` but `request.get?` will return `false`

### Issue

Since upgrading to brakeman 5, I started receiving this warning and brakeman doesn't offer any more information apart from: `request.get?` returns `false`. Fair enough, but what's the alternative?

I've been searching the internet and couldn't find anything useful. I've also been digging through the issue and the PR that introduced this new rule.

I really like how rubocop shows good and bad code example: https://rubystyle.guide/#three-is-the-number-thou-shalt-count

What's the alternative to this kind of code:

```rb
    def assign_submitter
      return render 'admin/records/assign_submitter' if request.get?

    # ... process post request
  end
```

Is this a good alternative:

```rb
    def assign_submitter
      return render 'admin/records/assign_submitter' unless request.post?

    # ... process post request
  end
```

**Comment by presidentbeef** [comment]
Hi @vfonic, yep we need to get the documentation up for this warning.

Yes, your alternative is safer - in the first code snippet the rest of `assign_submitter` will be executed for `HEAD` requests, which you probably don't want.

**Comment by vfonic** [comment]
Thank you, @presidentbeef! And thanks for the amazing work on the gem! 🚀 🤘
