### ISSUE TITLE
Missing docs on how to add brakeman config

### ISSUE THREAD

**Issue by vfonic** [presidentbeef/brakeman#1574]
I need to ignore a directory in my project. I'd like this directory to always be ignore in the default configuration file so that I can run `brakeman` locally, without having to specify `brakeman --skip-files ...`

I have no idea how to write a brakeman config file. I've found in the readme that I can create `config/brakeman.yml`, but no idea on how the contents of that file should look like. It would be much easier to read the documentation than to write some valid YAML hoping I guessed correctly how `--skip-files` translates into YAML.

Did I miss the docs for this somewhere?

Thank you!

EDIT:
After digging through the source code, I managed to get it to work:

```yaml
skip_files:
  - 'plugins/'
```

The keys are underscored and the value (in this case at least) has to be an array. Just passing a single string results in an error.

**Comment by presidentbeef** [comment]
Yes, you are right. The [docs](https://brakemanscanner.org/docs/options/#configuration-files) are a little sparse on this and should be clearer.

The easiest thing to do is run Brakeman with the options you want, plus `-C`:

```
$ brakeman -C --skip-files plugins/
---
:skip_files:
- plugins/
```

This just dumps Brakeman's internal options hash out to YAML. Keys can be strings or symbols, either are accepted.

**Comment by vfonic** [comment]
Ah! Now I understand what it means:
> To simplify the process of writing a configuration file, the `-C` option will output the currently set options.

😄 

I've added a PR to include an example: https://github.com/presidentbeef/brakeman/pull/1575

PS I tried writing this directly to file, but it just didn't work:

```sh
$ brakeman -C --skip-files plugins/ > config/brakeman.yml
---
:skip_files:
- plugins/
$ cat config/brakeman.yml
# empty
$
```

**Comment by presidentbeef** [comment]
> PS I tried writing this directly to file, but it just didn't work:

Yes, that's annoying and should be fixed.
