### ISSUE TITLE
Parse error on ternary operator without space before semicolon

### ISSUE THREAD

**Issue by kreintjes** [presidentbeef/brakeman#1602]
### Background

Brakeman version: 5.0.1
Rails version: 6.0.3.7
Ruby version: 2.7.3

Link to Rails application code: not to be disclosed

#### Parse Error

```
Error: app/helpers/..._helper.rb:NNN :: parse error on value "\"" (tLABEL_END) Could not parse app/helpers/..._helper.rb
Location: /*******/vendor/bundle/ruby/2.7.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
```

(Consult https://brakemanscanner.org/docs/troubleshooting/parse_errors/ first. Note that (most) parsing errors are from the ruby_parser library, not Brakeman itself.)

Minimal example that does not parse:

```ruby
title_key = location_title ? "with_#{location_type}": "without_location"
```

I get a parse error when having a ternary operator without space before the semi-colon (as shown above), although this is valid Ruby (2.7.3) syntax. I can use the code and `ruby -c` doesn't report warnings: `Syntax OK`

It's easily fixed by just putting a space before the semicolon (`:`), which also looks nicer, but wanted to report it anyway in case anybody else runs into this since it is valid Ruby.

Might be related to https://github.com/seattlerb/ruby_parser/issues/191

**Comment by presidentbeef** [comment]
@kreintjes you should report to https://github.com/seattlerb/ruby_parser/
