### ISSUE TITLE
Need 5.0.4 in Releases Tab

### ISSUE THREAD

**Issue by trueheart78** [presidentbeef/brakeman#1614]
`Changes.md` has the most up-to-date stuff, but [RubyGems.org](https://rubygems.org/gems/brakeman) shows a link to the [Release Tab](https://github.com/presidentbeef/brakeman/releases) for the **Changelog** metadata.

**Comment by presidentbeef** [comment]
Added, thanks! https://github.com/presidentbeef/brakeman/releases/tag/v5.0.4
