### ISSUE TITLE
Improve --ensure-latest

### ISSUE THREAD

**Issue by jonathongardner** [presidentbeef/brakeman#1625]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my pipeline fails while using `brakeman --ensure-latest` because Brakeman releases a patch update.

**Describe the solution you'd like**
Would be nice if there was an option to only error on minor (or even major) releases. Maybe something like `brakeman --ensure-latest-major-and-minor` and `brakeman --ensure-latest-major`

**Comment by presidentbeef** [comment]
Thanks for the suggestion.

I don't have any interest in this as a feature, though. Brakeman's versions are kind of arbitrary and these options seem really specific. I'd guess Dependabot or something similar can help you keep Brakeman up-to-date on major.minor versions.
