### ISSUE TITLE
Clarify docs

### ISSUE THREAD

**Issue by mcandre** [presidentbeef/brakeman#1630]
Hi,

I am curious about brakeman and want to make sure I understand it correctly. For example, can brakeman scan arbitrary Ruby projects for security vulnerabilities? Or only Rails applications?

**Comment by presidentbeef** [comment]
> can brakeman scan arbitrary Ruby projects for security vulnerabilities?

Not really. You can try with `--force` but I doubt you'll be happy with the results.

I think the description is fairly clear? "A static analysis security vulnerability scanner for Ruby on Rails applications"?

Also on the website: "Brakeman is a free vulnerability scanner specifically designed for Ruby on Rails applications."
