### ISSUE TITLE
CWE information

### ISSUE THREAD

**Issue by bhuvi11** [presidentbeef/brakeman#1636]
Hello Team,

The internal vulnerability identifiers/issues used by brakeman cannot be mapped to commonly used vulnerability metrics such as CWE. Some environments may require CWEs to be used as a standard for categorizing vulnerabilities. In addition, CWE mappings are very useful to consolidate vulnerability reports produced by different tools.

Describe the solution you'd like
Every vulnerability should get assigned a CWE identifier.

**Comment by presidentbeef** [comment]
Yes... if anyone wants to provide an initial mapping, I'd be happy to merge. I've already done this once but it was in a proprietary context.

**Comment by bhuvi11** [comment]
@presidentbeef , if you have already done it once, can you provide the mapping , so that we can use it . We will do the mapping manually. We just need the CWE associated with the issues
