### ISSUE TITLE
Ruby-3.1 support

### ISSUE THREAD

**Issue by ojab** [presidentbeef/brakeman#1664]
Just a placeholder ticket to track https://github.com/seattlerb/ruby_parser changes

### Background

Brakeman version: 5.2.0
Rails version: n/a
Ruby version: 3.1.0

#### Parse Error

https://github.com/seattlerb/ruby_parser/issues/325
https://github.com/seattlerb/ruby_parser/issues/326
https://github.com/seattlerb/ruby_parser/issues/328
https://github.com/seattlerb/ruby_parser/issues/329
~~more will be added after https://rubyreferences.github.io/rubychanges/ is updated, this two appeared in the project that I updated.~~

**Comment by philipithomas** [comment]
Yeah - seems like Ruby 3.1's shorthand hash syntax isn't supported by Brakeman yet.

**Comment by npverni** [comment]
+ 1 on this

**Comment by presidentbeef** [comment]
Hi folks - appreciate your enthusiasm but Brakeman relies on https://github.com/seattlerb/ruby_parser for supporting new Ruby syntax. When ruby_parser is updated, then Brakeman can be updated.

**Comment by ojab** [comment]
Filed/added missing tickets, feel free to lock the discussion :smile:

**Comment by willfish** [comment]
Have you seen this @presidentbeef  and @ojab https://github.com/seattlerb/ruby_parser/commit/d7f06448e3d9a0fc2a34684f38cb53d6e3d73a6a?

**Comment by schinery** [comment]
There has been a new release of [ruby_parser](https://github.com/seattlerb/ruby_parser) that has “Added tentative 3.1 support” and closed/fixed the 3.1 syntax issues listed by @ojab above. 

Does this potentially unblock brakeman from supporting 3.1 now?

**Comment by ojab** [comment]
I guess could be closed per https://github.com/presidentbeef/brakeman/pull/1695

**Comment by presidentbeef** [comment]
Released with Brakeman 5.2.2.
