### ISSUE TITLE
link_to_href check false positive when interpolation is used, but is not a direct interpolation

### ISSUE THREAD

**Issue by oreoshake** [presidentbeef/brakeman#167]
False positive when the argument isn't a :string_interp node, but resolves to a :string_interp

e.g.

    link_to "", raw("/#{interpolated}")

and

    thing = condition? route_path : "/#{interpolated"
    link_to "", thing

Should be safe.

**Comment by presidentbeef** [comment]
I should look at this again...if you assign an if expression to a variable, the variable should contain just the potential values, not the if expression itself.
