### ISSUE TITLE
Failure parsing Ruby 3.1 hash literal value syntax

### ISSUE THREAD

**Issue by viktorianer** [presidentbeef/brakeman#1675]
### Background

Ruby 3.1 introduced new [hash literal value syntax](https://rubystyle.guide/#hash-literal-values).

Brakeman version: 5.2.1
Rails version: 6.1.4.4
Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]

Link to Rails application code: any new app.

#### Parse Error

(Consult https://brakemanscanner.org/docs/troubleshooting/parse_errors/ first. Note that (most) parsing errors are from the ruby_parser library, not Brakeman itself.)

```bash
ruby -c config/environments/test.rb
Syntax OK
# do not know how ot use `ruby_parse`
```

Minimal example that does not parse:

```ruby
# config/environments/test.rb
host = "localhost:3000"
config.action_mailer.default_url_options = { host:, protocol: "https" }
```

Server starts, tests are running.

**Comment by presidentbeef** [comment]
See https://github.com/presidentbeef/brakeman/issues/1664
