### ISSUE TITLE
`latest` brakeman image in docker hub is older than `5.2.1`

### ISSUE THREAD

**Issue by shamrt** [presidentbeef/brakeman#1680]
As a follow-up to #1510, I thought I'd raise the same issue. Any chance we could get the brakeman image updated on Dockerhub? Thank you!

**Comment by presidentbeef** [comment]
Since Docker has stopped allowing automatic builds for free accounts, I have to find out a new way to automate the Docker builds.

**Comment by prashcr** [comment]
Here's a workaround command that can be used until the docker image is updated

```
docker run -it -v "$(pwd)":/code -w /code ruby:3-alpine sh -c 'gem install brakeman && brakeman'
```

**Comment by katelovescode** [comment]
Commenting to follow; the github action uses the doctor container so we've gotta wait until it's updated.

**Comment by presidentbeef** [comment]
Thanks for the ping @katelovescode. Does the GitHub action you are using reference the `latest` tag?

What I've done for now is push out an image for `v5.2.1` and `latest`, which are the same.

Previously, `latest` was built for every update to the `main` branch...

**Comment by katelovescode** [comment]
[https://github.com/artplan1/brakeman-action/blob/master/action.yml](https://github.com/artplan1/brakeman-action/blob/master/action.yml) looks like it doesn't specify, so I'm assuming it defaults to `latest`?  I'll give this another shot later today, thank you for pushing out an update!

**Comment by ShockwaveNN** [comment]
I've created https://github.com/presidentbeef/brakeman/pull/1729 to automate building image on each pushed tags
