### ISSUE TITLE
EOLRuby false positive

### ISSUE THREAD

**Issue by kdiogenes** [presidentbeef/brakeman#1684]
### Background

Brakeman version: 5.2.1
Rails version: 6.1.4.6
Ruby version: 3.0.1

#### False Positive

*Full* warning from Brakeman:
Confidence: Weak
Category: Unmaintained Dependency
Check: EOLRuby
Message: Support for Ruby 2.6.3 ends on 2022-03-31
File: Gemfile.lock
Line: 295

Relevant code:

```ruby
# line 295 of my Gemfile.lock:
    rails (6.1.4.6)
# line 497 of my Gemfile.lock specifies the ruby version:
RUBY VERSION
   ruby 3.0.1p64
```

_Why might this be a false positive?_
I'm using a newer version of ruby.

**Comment by presidentbeef** [comment]
Hm, I can't reproduce this.

Can you check if there is a reference to `2.6.3` anywhere in your code? Perhaps a different `Gemfile.lock`?

**Comment by kdiogenes** [comment]
Thanks for the reply @presidentbeef. My project had a .ruby-version file, but I'm using asdf, after removing it the warning goes away!
