### ISSUE TITLE
Brakeman integrated in Scanmycode CE (Community Edition)

### ISSUE THREAD

**Issue by marcinguy** [presidentbeef/brakeman#1692]
Hi,

I would like to share information about my Open Source and selfhosted Code Scanning (Quality & Security) solution here. 

We also added your Brakeman for checking Ruby code.

Here is the repository for the Community Edition of the solution (Code & Wiki) 

https://github.com/marcinguy/scanmycode-ce

For transparency, I was involved and am involved in building of it. Took several months with several people.

Thank you for Brakeman being there. 

Feel free to contact my directly or here in case of any questions/comments.

Thanks,

**Comment by presidentbeef** [comment]
👍
