### ISSUE TITLE
I would like brakeman docker image to be cross platform

### ISSUE THREAD

**Issue by kwerle** [presidentbeef/brakeman#1703]
While brakeman amd does work on my shiny new mbp, it's less than optimal.  Building x-platform images is pretty easy.

I'm willing to contribute effort to get this done.

**Comment by presidentbeef** [comment]
> Building x-platform images is pretty easy.

Minor disagree, because it actually seemed like a pain. 😄 

But - yes, go for it. Ideally there would be a GitHub action to build/push the images automatically, e.g. https://github.com/docker/build-push-action

**Comment by kwerle** [comment]
How do you currently push to docker?

**Comment by presidentbeef** [comment]
Manually, when someone reminds me.

**Comment by kwerle** [comment]
While this ticket should probably be closed, it makes me sad that the image used is ruby:2.5-alpine - which ships with bundler 1.x.  When I try to run the docker image on my project it complains:

```
➜  docker run -v $PWD:/code presidentbeef/brakeman:latest --allow-check-paths-in-config true . 
[Notice] Using configuration in /code/config/brakeman.yml
Loading scanner...
You must use Bundler 2 or greater with this lockfile.
```

I'm guessing most folks are using bundler 2.x.  It might be nice to update to 2.7:
```
➜ docker run ruby:2.7-alpine bundle --version
Bundler version 2.1.4
```

**Comment by presidentbeef** [comment]
Okay. #1735
