### ISSUE TITLE
License Request Email Broken

### ISSUE THREAD

**Issue by carltonsmith** [presidentbeef/brakeman#1706]
The email linked in the license is broken. sig-sales-ww@synopsys.com comes back as undeliverable.

**Comment by thewatts** [comment]
Just tried emailing them this morning - also came back undeliverable.

**Comment by presidentbeef** [comment]
Hello - you only need a license if you are building a commercial product that incorporates Brakeman as part of the product. If that's the case, DM me on Twitter or email me justin at presidentbeef dot com.
