### ISSUE TITLE
UnscopedFind check ignore certain models

### ISSUE THREAD

**Issue by Mathiou04** [presidentbeef/brakeman#1707]
### Background

Brakeman version: 5.2.1
Rails version: 6.0.4.1
Ruby version: 2.7.1

### Issue

We noticed that some models unscoped finds are apparently not detected by Brakeman [UnscopedFind check](https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/checks/check_unscoped_find.rb).

Looking at the code of the check, it seems that the culprit is this piece of code that selects only certain models:
```
associated_model_names = active_record_models.keys.select do |name|
  if belongs_to = active_record_models[name].associations[:belongs_to]
    not optional_belongs_to? belongs_to
  else
    false
  end
end
```

The `optional_belongs_to?` code looks like this:
```
def optional_belongs_to? exp
  return false unless exp.is_a? Array

  exp.each do |e|
    if hash? e and true? hash_access(e, :optional)
      return true
    end
  end

  false
end
```

It looks like if the model contains at least one `belongs_to` relation that is flagged as `optional`, then it is ignored.

I am not sure of the rationale behind this selection of model, but we happened to have some models that should have been scoped that had some optional `belongs_to` relations that were legitimate. 
Brakeman was not reporting the scoping errors for those models.

I believe the rationale was to try to exclude the "top level" models from the check (even if I don't completely understand how this helps, that is the only explanation that I could think of for now) but I have the impression it would be "less surprising" to check all models and let users ignore the warning they think are legitimate usage of unscoped find.

As is, the check both creates false positives and false negatives, so you can not trust it to at least help you review all the potential flaws your codebase has regarding this security issue.

If this makes sense, I can create a PR to purely remove this selection code altogether.

**Comment by presidentbeef** [comment]
Hi @Mathiou04 

You can review the reasoning here: #1139

There is no winning with this rule. It will either over-report or under-report no matter what. That's why it's not on by default.
