### ISSUE TITLE
Add checks for weak public-key cryptography

### ISSUE THREAD

**Issue by bdewater** [presidentbeef/brakeman#1736]
**Is your feature request related to a problem? Please describe.**
Similar to [check_weak_hash.rb](https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/checks/check_weak_hash.rb) and inspired by https://github.com/ruby/openssl/pull/546 - it is quite easy to use RSA and other asymmetric algorithms insecurely. Some ideas that can be checked for:

- Small key sizes (eg RSA < 2048 bits = [CWE-326](https://cwe.mitre.org/data/definitions/326.html)) when generating keys
- Insecure padding modes (eg RSA PKCS#1 v1.5 = [CWE-780](https://cwe.mitre.org/data/definitions/780.html)) when doing operations 

**Describe the solution you'd like**
Flag the code like this [blog post](https://shopify.engineering/building-flex-comp) which specifically showcases CWE-780:
```ruby
def encrypt(payload)
  public_key = OpenSSL::PKey::RSA.new("grab the public 4096 bit key")
  Base64.encode64(public_key.public_encrypt(payload.to_json)
end
```

`OpenSSL::PKey::RSA#public_encrypt` defaults to insecure PKCS#1 v1.5 padding. On modern OpenSSL gems (>= 3.0) this is [a wrapper](https://github.com/ruby/openssl/blob/fd5eaa6dfc9e70875505cbe89a854223e7922776/lib/openssl/pkey.rb#L429-L449) for `OpenSSL::PKey::PKey#encrypt`, so effectively the following code is called:
```ruby
public_key.encrypt(payload.to_json, "rsa_padding_mode" => "pkcs1")
```

Both types of calls should be flagged.

**Describe alternatives you've considered**
N/A

**Comment by presidentbeef** [comment]
Nice suggestion!

**Comment by iamjohnford** [comment]
The current checks don't appear to catch the following version of the weak RSA padding mode:

```ruby
public_key.encrypt(payload.to_json, rsa_padding_mode: "pkcs1")
```

Should a check for that be added as well?
