### ISSUE TITLE
Missing tag in git for version 5.3.1

### ISSUE THREAD

**Issue by dentarg** [presidentbeef/brakeman#1739]
https://rubygems.org/gems/brakeman/versions lists `5.3.1 - August 10, 2022 (1.4 MB)` but I see no tag for it at https://github.com/presidentbeef/brakeman/tags

(Link to the diff between 5.3.0 and 5.3.1: https://my.diffend.io/gems/brakeman/5.3.0/5.3.1)

**Comment by presidentbeef** [comment]
Hi @dentarg - thanks for pointing that out. 5.3.1 was a quick bug fix release.

I've added a tag/release here:
https://github.com/presidentbeef/brakeman/releases/tag/v5.3.1
