### ISSUE TITLE
Broken link to Unmaintained Dependency

### ISSUE THREAD

**Issue by davetron5000** [presidentbeef/brakeman#1757]
### Background

Brakeman version: 5.4.0
Rails version: 7.0.4.1
Ruby version: 3.1.3

Link to Rails application code: See below

### Issue

When there is an issue called "Unmaintained Dependency" the HTML output links to `https://brakemanscanner.org/docs/warning_types/unmaintained_dependency/` but this 404s.

This should be reproducible as follows:

* Create a new Rails app using Ruby 3.1.x and install brakeman
* Brakeman should not find issues
* create `.ruby-version` in the root of the app with these contents:

  ```
  ruby-2.7.0
  ```
* Re-run brakeman (you can use Ruby 3.1). Brakeman will see this file and generate the "Unmaintained Dependency" warning.  The HTML will link to the above URL

**Comment by presidentbeef** [comment]
Happy to accept a PR to https://github.com/presidentbeef/brakeman-site to add documentation. I'm a bit behind.

**Comment by presidentbeef** [comment]
Added https://brakemanscanner.org/docs/warning_types/unmaintained_dependency/
