### ISSUE TITLE
False positive for send_file

### ISSUE THREAD

**Issue by daniel-prause** [presidentbeef/brakeman#1766]
### Background

Brakeman version: 5.4.1
Rails version: 7.0.4.3
Ruby version: 3.0.4

Link to Rails application code: -

### Issue

Brakeman has a false positive with this code:

```
  def export
    sequence = authorize(ProductChangeSequence.find(params[:id]))
    zip_file = ReicofilExportService::SequenceExport.call(sequence)
    filename = [['sequence_export', sequence.asset.name, Time.current].join('_').parameterize, '.zip'].join
    send_file(zip_file.path, filename: filename, type: 'application/zip')
  end
```

### Warnings

Confidence: Weak
Category: File Access
Check: SendFile
Message: Model attribute used in file name
Code: send_file(ReicofilExportService::SequenceExport.call(authorize(ProductChangeSequence.find(params[:id]))).path, :filename => "test", :type => "application/zip")
File: app/controllers/product_change_sequences_controller.rb
Line: 109

**Comment by presidentbeef** [comment]
Why would this be a false positive?

Or, put another way, how would Brakeman know that `ReicofilExportService::SequenceExport.call(authorize(ProductChangeSequence.find(params[:id]))).path` is safe?

Also note this is a weak confidence warning.
