### ISSUE TITLE
Is there a flag to show all warnings including the ignored ones?

### ISSUE THREAD

**Issue by bonniesimon** [presidentbeef/brakeman#1767]
Is there a way to see the ignored warnings without removing their entry from the brakeman.ignore file?

I wanted to see the ignored cases in the cli itself. Is that currently possible?

**Comment by presidentbeef** [comment]
Ignored warnings are included in the JSON output (e.g. `brakeman -f json`).

That's the only good way right now.

**Comment by bonniesimon** [comment]
Would love to have a flag that would show all the warning including the ignored warning. I would love to contribute to that feature. Let me look into it. 

But before that just give me your thoughts on such a flag.

**Comment by presidentbeef** [comment]
What's the desired behavior you are looking for?

1. Ignore the ignore file
2. Show all warnings, but ignored warnings are in a separate section or otherwise marked
3. Show all warnings, but only return a non-zero exit code for unignored warnings

**Comment by bonniesimon** [comment]
I think 2. would be good. I'm not sure what 3. means.

**Comment by presidentbeef** [comment]
Works for me. `--show-ignored` or something like that.
