### ISSUE TITLE
Brakeman Is Not Catching SQL Injections in Arel.sql(raw_sql)

### ISSUE THREAD

**Issue by bsheltonfleetio** [presidentbeef/brakeman#1768]
### Background

Brakeman version: 5.4.1
Rails version: 7.0.4
Ruby version: 3.1.2

Link to Rails application code: Private Repository

### Issue

What problem are you seeing?

User supplied input is being passed into Arel.sql(raw_sql). Arel documentation states that user supplied inputs should not be passed into that function -> https://www.rubydoc.info/docs/rails/Arel.sql. However, it is a common thing and Brakeman does not generate an alert when that occurs. 

The raw_sql variable below has model attributes included in the string, that open the code up to SQL injections, but is not being flagged by brakeman. 

```
      result = ActiveRecord::Base.connection.execute(
        Arel::SelectManager.new(
          Arel::Nodes::Grouping.new(Arel.sql(raw_sql)).as("query_value")
        ).project(
          Arel::Nodes::NamedFunction.new("AGGREGATION", [Arel.sql("query_value")])
        ).to_sql
      )
```

**Comment by presidentbeef** [comment]
Hi, thank you for opening a new issue.

But I really need to know what's in the arguments to `Arel.sql` to say why it might not be warning.

**Comment by bsheltonfleetio** [comment]
@presidentbeef here are some examples -> Brakeman catches the last example as a sql injection, but not the prior examples . Does Brakeman only check for interpolation or do you mind explaining why this is happening? 

```
  def brakeman_test(sql)
    # None of these raise a warning
    no_warning_result_1 = ActiveRecord::Base.connection.execute(
      Arel::Nodes::Grouping.new(Arel.sql(sql)).as("query").to_sql
    )

    no_warning_result_2 = ActiveRecord::Base.connection.execute(
      Arel.sql(sql).as("query").to_sql
    )

    no_warning_result_3 = ActiveRecord::Base.connection.execute(
      Arel.sql(sql).to_sql
    )

    no_warning_result_4 = ActiveRecord::Base.connection.execute(
      sql
    )

    no_warning_result_5 = ActiveRecord::Base.connection.execute(
      sql.to_s
    )

    # This raises a Medium SQL injection warning
    warning_result = ActiveRecord::Base.connection.execute(
      "#{sql}"
    )
  end
```

**Comment by presidentbeef** [comment]
Hi @bsheltonfleetio - Since Brakeman doesn't know what the `sql` argument is, it does not raise a warning in those cases.

For the last case, it still doesn't know but does warn generally about (raw) string building in SQL queries.
