### ISSUE TITLE
False Negative: warning on CSRF in Rails 5.2+ with defaults

### ISSUE THREAD

**Issue by joshgoebel** [presidentbeef/brakeman#1773]
### Background

Brakeman version: ? 5.4.0
Rails version: ? 6.0
Ruby version: ? 2.7

Link to Rails application code:  closed-source

#### False Positive

When:

- `load_defaults` is NOT present
- `default_protect_from_forgery` is NOT configured anywhere

*Full* warning from Brakeman: 

No warning, but there should be a security warning generated by `checks/check_forgery_setting.rb`.

Relevant code:

```ruby
# these lines are MISSING from your config
# load_defaults 5.2 
# Rails.application.config.action_controller.default_protect_from_forgery = nil
```

_Why might this be a false negative?_

Because by default a Rails 6 app does NOT have protect for forgery enabled unless `load_defaults 5.2` or higher is used...

```
> Rails.application.config.action_controller.default_protect_from_forgery
=> nil
> ApplicationController.default_protect_from_forgery
=> false
```

The logic for this check assumes that defaults are tied to the Rails version number only... but this is untrue, they are based on the actual underlying defaults of Rails (often nil) PLUS the `load_defaults` one is using - and it's entirely possible (though perhaps ill-advised) not to use load_defaults at all.

**Comment by joshgoebel** [comment]
Related: https://github.com/presidentbeef/brakeman/commit/a7aa17ed6f2ed5af4450fb5aa2447bc8116f577a

**Comment by presidentbeef** [comment]
@joshgoebel Ah looks like this is pretty old code from before Brakeman was looking for `load_defaults` and setting configuration values based on that.

**Comment by presidentbeef** [comment]
I think this is the same issue as https://github.com/presidentbeef/brakeman/pull/1530

**Comment by joshgoebel** [comment]
Indeed, but the claim at the end was a fix has been merged to main - and this is definitely still unfixed.

Should we close this as a duplicate now?

**Comment by presidentbeef** [comment]
The changes in https://github.com/presidentbeef/brakeman/pull/1532 and #1530 are both needed, but the person who opened #1530 never followed up. I'll add the tests and merge.
