### ISSUE TITLE
Relax Rails app structure constraints

### ISSUE THREAD

**Issue by gejustin** [presidentbeef/brakeman#1775]
**Is your feature request related to a problem? Please describe.**
I recently noticed that brakeman was not able to understand the structure of some of the rails engines in my company's monolith. Ultimately what i discovered was that at some point in time, for reasons unknown to me, we deviated slightly from the standard rails convention where controllers, models, views, etc are contained within an `app` directory. Digging a bit deeper, I noticed in the brakeman [source](https://github.com/presidentbeef/brakeman/blob/dd9ba8b0f1638506b0f907dfaf40187eeda29e76/lib/brakeman/app_tree.rb#L110) that brakeman has this app structure hard coded.

**Describe the solution you'd like**
It would be nice to be able to provide an alternative directory or directories that might contain these rails components. I understand that the `app` constraint exists to limit the scope of these wildcard searches since brakeman is run on the root of a rails project. It would be pretty wasteful to scan every directory in the project to try to find rails components.

**Describe alternatives you've considered**
There are some workarounds that we could do internally. I noticed that creating a symlink works or I could potentially try to rename our custom app directory (though this might be pretty disruptive).

**Additional context**
For whatever reason we called our `app` dir `web` in these engines. 🤷

**Comment by presidentbeef** [comment]
There was a change away from using the directory structure in [Brakeman 5.0](https://github.com/presidentbeef/brakeman/releases/tag/v5.0.0). The code you are referencing is dead code now and should probably be removed.

There are hardcoded paths that are excluded, though: https://github.com/presidentbeef/brakeman/blob/a301e6aad87d102f8d4718403f71c65b539bdba3/lib/brakeman/app_tree.rb#L192-L201

Other than that... there's probably something else going on that is causing the behavior you are seeing.

**Comment by gejustin** [comment]
Okay, thank you for clarifying. Indeed I was on 4.10.1 so that must have been why I was still hitting that code path. I will work on updating and close this issue once I get something working.
