### ISSUE TITLE
content_tag no longer considered dangerous

### ISSUE THREAD

**Issue by oreoshake** [presidentbeef/brakeman#1778]
### Background

Brakeman version: 5.1.2
Rails version: 6.1.7.3
Ruby version: 2.7.5

Link to Rails application code: https://github.com/presidentbeef/brakeman/issues/1778

#### False Positive

*Full* warning from Brakeman: 

```
Confidence: High
Category: Cross-Site Scripting
Check: ContentTag
Message: Unescaped parameter value in `content_tag`
Code: content_tag(:tr, foo(mf), params[:foo] => params[:bar])
```

Relevant code:

```ruby
helper.content_tag :p, "<script>alert(1)</script>", "<script>&'\"" => "<script>&'\""
```

_Why might this be a false positive?_

The return value seems to `gsub` out the control characters for `_` in attribute names now. 

```
=> "<p _script____=\"&lt;script&gt;&amp;&#39;&quot;\">&lt;script&gt;alert(1)&lt;/script&gt;</p>"
```

I haven't really tracked down when this changed. I thought I did, but no.

**Comment by presidentbeef** [comment]
I think it was

https://github.com/rails/rails/commit/5c7dae5a410ff49fe4dcf30b97ee0f9148114b66

released in [Rails 6.1.6](https://github.com/rails/rails/releases/tag/v6.1.6)
