### ISSUE TITLE
False positive Send where `send` is inside conditional that prevents arbitrary user input.

### ISSUE THREAD

**Issue by JoeCohen** [presidentbeef/brakeman#1782]
### Background

(Full report attached; run with `brakeman -d -o brakeman.txt --test Send` in order to focus on the warning)
Brakeman version: 6.0.0
Rails version: 6.1.7.3
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

Link to Rails application code: https://github.com/MushroomObserver/mushroom-observer
#### False Positive

*Full* warning from Brakeman: 
```
Confidence: High
Category: Dangerous Send
Check: Send
Message: User controlled method execution
Code: @user.send("email_#{params[:type]}=", false)
File: app/controllers/account/preferences_controller.rb
Line: 34
```

Relevant code:

```ruby
    def no_email
      user = User.safe_find(params[:id])
      type = params[:type]
      if user && check_permission!(user) && EMAIL_TYPES.include?(type)
        method  = "email_#{type}="
        prefix  = "no_email_#{type}"
        success = "#{prefix}_success".to_sym
        @note   = "#{prefix}_note".to_sym
        @user.send(method, false)
...
      end
    end

    EMAIL_TYPES = %w[
      comments_owner
      comments_response
      comments_all

      observations_consensus
      observations_naming
      observations_all

      names_admin
      names_author
      names_editor
      names_reviewer
      names_all

      locations_admin
      locations_author
      locations_editor
      locations_all

      general_feature
      general_commercial
      general_question
    ].freeze
```

_Why might this be a false positive?_
It will not send arbitrary user-selected params because the `send is nested inside the conditional `if user && check_permission!(user) && EMAIL_TYPES.include?(type)`; it will execute the `send` only if `params[:type]` is a listed value. 

[brakeman.txt](https://github.com/presidentbeef/brakeman/files/11655026/brakeman.txt)

**Comment by presidentbeef** [comment]
Ah, it's pretty complicated to deal with logical expressions like that, so right now Brakeman only handles simple conditions.

If you moved `EMAIL_TYPES.include?(type)` to a nested `if` it should work:

```
if user && check_permission!(user)
  if EMAIL_TYPES.include?(type)
    # ...
 ```

Or you could flip the `if` statements - it might be cheaper to do the array check first.

In any case, try it and see if the Brakeman warning goes away. The other issue that might come up is if `EMAIL_TYPES` is defined somewhere Brakeman doesn't pick up properly.

**Comment by JoeCohen** [comment]
Justin:
1. Thanks so much for the speedy response and for Brakeman itself and its
latest improvements.
2. I'm not surprised that this situation is too complicated for Brakeman to
handle perfectly, but I thought I'd try.
3. Thanks also for your suggested work-around.
Another work-around is to grab `type` from the EMAIL_TYPES rather than
directly from user input. For instance:
type = EMAIL_TYPES.binary_search { |t| t == params[:type] }
...
method = "email_#{type}="
...
@user.send(method, false)
And, of course, I can use Brakeman's false positive functionality.
Regards,
- Joe
