### ISSUE TITLE
Unscoped find not alerted for `find_by!`

### ISSUE THREAD

**Issue by rbclark** [presidentbeef/brakeman#1786]
### Background

Brakeman version: 6.0.0
Rails version: 7.0.5.1
Ruby version: 3.2.2

Link to Rails application code:

```
Model.find_by!(public_find: params[:id]
Model.find_by!(id: params[:id])
```

### Issue

 - Brakeman has been updated to include [`find_by`](https://github.com/presidentbeef/brakeman/issues/1626) but it does not include `find_by!`.
 - Brakeman only checks for find_by on `id` and doesn't look for any other attributes. In our project the attribute we use `public_id` instead of `id` as the publicly facing ID of our models. This means we don't get any warnings for unscoped find for most of our models.

**Comment by presidentbeef** [comment]
A year later...

Happy to add `find_by!`, but `public_id` is not a standard column as far as I've found.
