### ISSUE TITLE
Unscoped find does not traverse concerns

### ISSUE THREAD

**Issue by rbclark** [presidentbeef/brakeman#1787]
### Background

Brakeman version: 6.0.0
Rails version: 7.0.5.1
Ruby version: 3.2.2

Link to Rails application code: 
**app/models/concerns/public_id.rb:**
```
module PublicId
	extend ActiveSupport::Concern

    class_methods do
        def public_find(public_id)
            find_by(id: public_id)
        end
    end
end
```

**app/models/user.rb**
```
class User < ApplicationRecord
    include PublicId
end
```

**app/models/users_controller.rb**
```
class UsersController < ApplicationController
	def show
		User.public_find(params[:id])
    end
end
```

### Issue

This code should cause an `unscoped_find` error since the User model is not being scoped, however it currently passes brakeman checks without raising an error.

**Comment by presidentbeef** [comment]
This is... true. Because (in general) Brakeman does not do interprocedural dataflow (tracing through method calls).

I don't see this being fixed any time soon, sorry.
