### ISSUE TITLE
Config in environment files generated by external services are not detected

### ISSUE THREAD

**Issue by tdutreui-solocal** [presidentbeef/brakeman#1794]
### Background

Brakeman version: 6.0.1
Rails version: 7.0.7.2
Ruby version: 3.2.2

Link to Rails application code: commercial app
#### False Positive

*Full* warning from Brakeman: 
```
Security Warnings: 2

== Warning Types ==

Missing Encryption: 1
Weak Hash: 1

== Warnings ==

Confidence: High
Category: Missing Encryption

-- press enter/return to continue or q to stop -- 
Check: ForceSSL
Message: The application does not force use of HTTPS: `config.force_ssl` is not enabled
File: config/environments/production.rb
Line: 1

Confidence: Medium
Category: Weak Hash
Check: WeakHash
Message: Weak hashing algorithm used: MD5
Code: Digest::MD5.hexdigest(input.to_json)
File: lib/string_utils.rb
Line: 3
```

Relevant code:

```ruby
# production.rb
require_relative "./shared_conf"

Rails.application.configure do
  SharedConf.call(config)
end
```

_Why might this be a false positive?_
We are managing an application with 5 different environments, and 3 of these share the same config using this service :

```ruby
# shared_conf.rb
module SharedConf
  def self.call(config)
    ...
    config.force_ssl = true
    ...
  end
end
```
The flag is correctly set inside this shared module, but brakeman is not able to detect it. I guess this is due to the essence of this tool that uses static analysis.
I'm just going to ignore this warning, feel free to either start the conversation or close the issue. And thank you for your amazing job on this gem!

**Comment by presidentbeef** [comment]
This code pattern seems specific to your application, correct?

It _could_ be supported, probably, but it would be just for this specific pattern.
