### ISSUE TITLE
Documentation Missing for Path Traversal

### ISSUE THREAD

**Issue by barnaclebarnes** [presidentbeef/brakeman#1808]
### Background

Previously closed issue: https://github.com/presidentbeef/brakeman/issues/1283

The Brakeman HTML report hyperlinks to https://brakemanscanner.org/docs/warning_types/path_traversal/ when you have a Path Traversal warning. This URL does not exist on the website. 

This leaves the user with no clue as to why this is an issue or how they might fix it.  The previous bug said:

> "Nested Attributes", "Path Traversal", "Response Splitting", and "Timing Attack" are only used in the context of CVEs and the warnings are linked to the relevant security bulletins. Therefore I do not think it is strictly necessary to document them on the website at this time. Maybe in the future.

But there is no link to the CVE when clicking on the link in the report. 

At a minimum the link in the report should go somewhere useful.

Brakeman version: 6.1.0

**Comment by presidentbeef** [comment]
Hard to believe I said that all the way back in 2019. Seems like yesterday.

Happy to accept a PR to https://github.com/presidentbeef/brakeman-site to add documentation. I'm a bit behind.

**Comment by presidentbeef** [comment]
Added
