### ISSUE TITLE
`abbrev` warning for ruby 3.4.0

### ISSUE THREAD

**Issue by chaadow** [presidentbeef/brakeman#1812]
Hi,

FYI:
after running brakeman with ruby 3.3.0 I have the following warning: 
`/Users/xx/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/brakeman-6.1.1/bundle/ruby/3.0.0/gems/highline-2.1.0/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec. Also contact author of brakeman-6.1.1 to add abbrev into its gemspec.`

**Comment by presidentbeef** [comment]
This actually a dependency of highline and was addressed in https://github.com/JEG2/highline/pull/264. Hopefully there will be a new release of highline in the near future, since it's been a while.

**Comment by tisba** [comment]
highline 3.0.0 was released which added `abbrev` as an explicit dependency, see https://github.com/JEG2/highline/blob/master/Changelog.md.

Don't quite understand how dependencies work with brakeman, should I just open a new issue to get this updated?

**Comment by tisba** [comment]
Maybe it's easier if @presidentbeef would consider re-open this issue, as this can be fixed now by bumping the highline dependency.

**Comment by abinoam** [comment]
@zvkemp issued a PR for completely removing abbrev as it was not being used anymore.

https://github.com/JEG2/highline/pull/268

Released already as 3.0.1
