### ISSUE TITLE
Possibility to ignore/skip directories/paths

### ISSUE THREAD

**Issue by djpremier** [presidentbeef/brakeman#1815]
**Is your feature request related to a problem? Please describe.**
Yes. In my project we are using the base level as the Rails directory, that is, in addition to Rails, other files such as Linters, Docker, VS Code configs, etc., are together. With this we also use, for optimization purposes, some `Docker volumes` mapped to a local folder, where for example we have the Bundler folder, with all the gems and other dependencies, as well as a `node_modules` folder for front-end dependencies. Due to these two folders having a large volume, Brakeman "dies" probably due to lack of memory (the output is just "Killed").

**Describe the solution you'd like**
Considering that these folders are usually quite heavy and are external dependencies (which have possibly even undergone individual checks before being published), we understand that they should be ignored. Therefore, the suggestion would be to have a configuration `--skip-paths docker,node_modules` where it is possible to specify the directories that do not need to be checked.

**Describe alternatives you've considered**
Checking the documentation there is `--skip-files`, but according to our tests it made no difference (I continue to check the directories). The other option would be `--only-files`, but as warned in the documentation, it would be more difficult to maintain, given that there are ruby files in the root directory and not everything is a problem to be checked, making this configuration necessary receive a significant amount of parameters to achieve the necessary/expected result.

**Additional context**

```
$ bundle exec brakeman
[...]
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/current_arg_stack.rb
(/app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/current_arg_stack.rb) Duration: 0.001676897 seconds
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/deprecation.rb
(/app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/deprecation.rb) Duration: 0.000301906 seconds
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/diagnostic.rb
(/app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/diagnostic.rb) Duration: 0.007560734 seconds
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/diagnostic/engine.rb
(/app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/diagnostic/engine.rb) Duration: 0.00177325 seconds
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/lexer-F0.rb
(/app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/lexer-F0.rb) Duration: 0.591685236 seconds
Processing /app/docker/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib/parser/lexer-F1.rb
Killed
```

**Comment by presidentbeef** [comment]
Hi @djpremier -

Directories can be skipped with `--skip-files`, just make sure the ends with `/`. Something like

`--skip-files docker/,node_modules/`

Let me know if that works for you.

**Comment by djpremier** [comment]
Thanks @presidentbeef, it really works. I based myself on the example of the `--only-files some_file,some_dir` command and the path is without the `/`, can we update the documentation to include an example in `--skip-files file1,file2,some_dir/,file3` using the directory?

**Comment by djpremier** [comment]
_For future references:_

If `--skip-files docker/` is used, directories with that name will be ignored regardless of their level, for example `app/controllers/docker/docker_controller.rb` would be ignored because it contains `docker/` in the path.

If you want to skip only the root directory, for example, you can do `--skip-files /docker/`

**Comment by presidentbeef** [comment]
I have updated https://brakemanscanner.org/docs/options/

The README and `-h` option have similar (though less-specific) information already.

Thanks!
