### ISSUE TITLE
Brakeman unable to detect Renderables in a Gem?

### ISSUE THREAD

**Issue by gavingmiller** [presidentbeef/brakeman#1819]
Hi @presidentbeef - first off, greatly appreciate all your work on this gem! 

I'm looking to find out if there's an alternative way to accomplish a monkey patch I'm making. The situation is that my company has created a library of custom renderables, which we distribute in a gem across all our projects. When brakeman processes these during a scan, they're not identified as renderables because they haven't been loaded into the `tracker`.

My plan is to monkey patch the `known_renderable_class?` in `lib/brakeman/checks/check_render.rb` and add in the classes that are safe from dynamic rendering, but wanted to touch base first to see if there's a better way - I haven't found anything in the documentation or a way to pre-load a set of known good renderables.

Appreciate any help you can provide!

**Comment by presidentbeef** [comment]
Hmm... The only thing that comes to mind is if you can have the gem contents inside the directory that is being scanned. Otherwise, there isn't a configuration option for this right now.

**Comment by gavingmiller** [comment]
Thanks for the suggestion @presidentbeef that worked much better than monkey patching!

For anyone else looking to solve this problem, I ended up creating a script in `./bin/brakeman` as follows:

```
#!/bin/bash

# This will unpack the gem as a subdirectory appending version number,
# meaning we can upgrade the gem, and not have collisions with the previous version
#
# This is required for properly eliminating renderable false positives that brakeman
# is unable to identify without this step
gem unpack <gem-with-renderables> --target=vendor/cache/gem-with-renderables
bundle exec brakeman $@
```
