### ISSUE TITLE
Command Injection doesn't detect shellescape unless the code is in the same function

### ISSUE THREAD

**Issue by allard** [presidentbeef/brakeman#1824]
### Background

Brakeman version: 6.1.1
Rails version: 7.0.8
Ruby version: 3.0.5

### Issue

I have a case where I'm calling curl and sometimes with a proxy (defined as an option in a Sysconfig class). I've been looking at ways to get around brakemans Command Injection warning and I've come across this issue (I have run into it in other situations as well, and this serves as a good example) where brakeman doesn't look at the content of a variable to see if it's safe unless the variable is defined in the same function.

#### This raises Possible Command Injection for "proxy"

```ruby
module Curl
  extend self
  require 'shellwords'

  def cmd(command)
    %x{curl #{proxy} #{command.shellescape}}
    #       |------| variable that brakeman has issue with
  end

  private

  def proxy
    if sysconfig.http_proxy_string.present?
      "-x #{sysconfig.http_proxy_string.shellescape}"
    end
  end

  def sysconfig
    @sysconfig ||= Sysconfig.first
  end

end
```

#### This is considered safe

```ruby
module Curl
  extend self
  require 'shellwords'

  def cmd(command)
    if sysconfig.http_proxy_string.present?
      proxy = "-x #{sysconfig.http_proxy_string.shellescape}"
    end
    %x{curl #{proxy} #{command.shellescape}}
  end

  private

  def sysconfig
    @sysconfig ||= Sysconfig.first
  end

end
```

With human inspection we can see that this code produces the exact same result and both should be considered safe. Is this a known limitation of the Command Injection function in brakeman?

#### Other things I've tested that doesn't work

I also can't write `%x{curl #{proxy.shellescape} ...}` because when curl has a proxy, it's `-x http://proxy:port` and shellescape then creates `-x\\ http://proxy:port` and that's not a valid proxy statement from curls point of view.

This Curl module is my latest attempt at minimizing warnings, I used to have `%x{curl #{curl_proxy} ...}` throughout the code but couldn't get around having a brakeman having a warning for each occurrence and didn't want to have local definitions of curl_proxy for each instance where curl is called.

**Comment by presidentbeef** [comment]
This is a consequence of how Brakeman works today - in static analysis terms, it does not do general "interprocedural data flow", meaning following data flow paths between functions. (It does some, just not in all cases.)
