### ISSUE TITLE
Undeliverable address sig-sales-ww@synopsys.com in LICENSE.md

### ISSUE THREAD

**Issue by bobby2100** [presidentbeef/brakeman#1829]
Hi,

I tried to contact Synopsys regarding Brakeman's licensing but received the following error:

**sig-sales-ww@synopsys.com: Recipient address rejected: undeliverable address: Address lookup failed.**

What is the current situation with Brakeman's license? Is still necessary to purchase a license for Brakeman if I think my application falls under "Using the Software as a component of a value-added service/product."? Could you give me examples of what this would encompass? I would like to use Brakeman just to scan my application.

Thanks in advance.

**Comment by presidentbeef** [comment]
Using Brakeman to scan your own applications (regardless of the nature of the application) does not require a commercial license.

> "Using the Software as a component of a value-added service/product."? Could you give me examples of what this would encompass?

I think of these as ["Brakeman as a Service" providers](https://github.com/presidentbeef/brakeman/wiki/Brakeman-as-a-Service) where Brakeman is itself part of the service/product.

**Comment by bobby2100** [comment]
Thank you for answering my question!
