### ISSUE TITLE
Controller with "log" in pathname excluded from scan

### ISSUE THREAD

**Issue by scottwillson** [presidentbeef/brakeman#1830]
### Background

Brakeman version: 5.4.1
Rails version: 6.1.7
Ruby version: 2.7.7

### Issue

Some controllers are being skipped and not scanned because they are in a directory ending in "log'. E.g., app/controllers/n/off_catalog/orders_controller.rb is excluded in [AppTree#reject_global_excludes](https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/app_tree.rb#L210-L212) because "log/" is in EXCLUDED_PATHS. 

Changing "log/" to "/log/" in EXCLUDED_PATHS fixes this but I'm unsure if that would cause other issues.

**Comment by presidentbeef** [comment]
:facepalm: 

I think all those paths should be updated with leading forward slashes. I don't _think_ it will cause any issues.
