### ISSUE TITLE
brakeman 6.2.1 ships binaries that are linked against ruby 3.1.0

### ISSUE THREAD

**Issue by kirillrdy** [presidentbeef/brakeman#1869]
### Background

Brakeman version: ?
6.2.1

Rails version: ?
Ruby version: ?
3.3.4

Link to Rails application code: ?

### Issue

What problem are you seeing?

I am using ruby 3.3.4 but brakeman ships with binaries that were linked against ruby 3.1

```
error: auto-patchelf could not satisfy dependency libruby.so.3.1 wanted by /nix/store/wnhsnqh5r6kw0x7l12ccyak7q662nmkd-wrapped-ruby-for-hl-web-3.3.4-dev/ruby/3.3.0/gems/brakeman-6.2.1/bundle/ruby/3.1.0/gems/strscan-3.1.0/lib/strscan.so
error: auto-patchelf could not satisfy dependency libruby.so.3.1 wanted by /nix/store/wnhsnqh5r6kw0x7l12ccyak7q662nmkd-wrapped-ruby-for-hl-web-3.3.4-dev/ruby/3.3.0/gems/brakeman-6.2.1/bundle/ruby/3.1.0/gems/strscan-3.1.0/ext/strscan/strscan.so
error: auto-patchelf could not satisfy dependency libruby.so.3.1 wanted by /nix/store/wnhsnqh5r6kw0x7l12ccyak7q662nmkd-wrapped-ruby-for-hl-web-3.3.4-dev/ruby/3.3.0/gems/brakeman-6.2.1/bundle/ruby/3.1.0/gems/io-console-0.7.2/lib/io/console.so
error: auto-patchelf could not satisfy dependency libruby.so.3.1 wanted by /nix/store/wnhsnqh5r6kw0x7l12ccyak7q662nmkd-wrapped-ruby-for-hl-web-3.3.4-dev/ruby/3.3.0/gems/brakeman-6.2.1/bundle/ruby/3.1.0/gems/io-console-0.7.2/ext/io/console/console.so
```

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
?
```

**Comment by dima4p** [comment]
`/usr/local/rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in 'require': libruby.so.3.1: cannot open shared object file: No such file or directory - /usr/local/rvm/gems/ruby-3.3.5@tv/gems/brakeman-6.2.1/bundle/ruby/3.1.0/gems/io-console-0.7.2/lib/io/console.so (LoadError)
`

**Comment by presidentbeef** [comment]
Hey @kirillrdy - sorry I missed your original message.

Two short term options:
* Use `gem 'brakeman', require: false` so it doesn't interfere with commands like `rails console`
* Switch to using `brakeman-lib` instead so it doesn't come with pre-packaged libraries.

The conversation of standard libraries to gems is killing me 😞

**Comment by dima4p** [comment]
> * gem 'brakeman', require: false

Thanks, adding `gem 'brakeman', require: false` fixes the problem, but adding  `gem 'guard-brakeman' `
returns it.

**Comment by presidentbeef** [comment]
Will be addressed in next release with https://github.com/presidentbeef/brakeman/issues/1869
