### ISSUE TITLE
Rails 6.1.7.9 recognized as EOL

### ISSUE THREAD

**Issue by bradherman** [presidentbeef/brakeman#1874]
### Background

Brakeman version: 6.2.2
Rails version: 6.1.7.9
Ruby version: 3.3.5

### Issue

With update to 6.2.2, Rails is recognized as being EOL at 6.1.7.9, which only came out 3 days ago and appears to still be supported.

**Comment by presidentbeef** [comment]
Understand this is confusing, but it 6.1.x is no longer supported.

See
https://rubyonrails.org/2024/10/15/new-maintenance-policy-and-eol-annouments

> Rails 6.1.x reached its end of maintenance on October 1, 2024.
>While regular maintenance has concluded, we will provide one extra security release for Rails 6.1.x.
> After this additional security release, no further updates will be provided for this version.
> We strongly urge users of Rails 6.1.x to plan their upgrade to a supported version as soon as possible.

https://rubyonrails.org/2024/10/15/Rails-Versions-7-0-8-5-7-1-4-1-and-7-2-1-1-have-been-released

> Rails 6.1 had an anticipated end of maintenance earlier this month, but as we transition to our [new maintenance policy](https://rubyonrails.org/2024/10/15/new-maintenance-policy-and-eol-annouments) we’ve cut an additional release: 6.1.7.9.

https://rubyonrails.org/maintenance

> 7.2.x - Supported until August 9, 2026
> 7.1.x - Supported until October 1, 2025
> 7.0.x - Supported until April 1, 2025
> 6.1.x - Supported until October 1, 2024

**Comment by bradherman** [comment]
Wow, totally missed that.  Thanks!
