### ISSUE TITLE
Check for SSL cert verification

### ISSUE THREAD

**Issue by mccabe615** [presidentbeef/brakeman#250]
Would adding a check for OpenSSL::SSL::VERIFY_NONE to warn when making requests without verifying certs be useful or just noise?

**Comment by gmcnaughton** [comment]
brakeman 3.0.5 warns me about this:
```ruby
Net::HTTP.start(uri.host, uri.port, :use_ssl => true) do |http|
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE # <= bad!
```
But not about this, which should be equivalent:
```ruby
Net::HTTP.start(uri.host, uri.port, :use_ssl => true, :verify_mode => OpenSSL::SSL::VERIFY_NONE) # <= also bad!
```
It would be great to have both!

**Comment by presidentbeef** [comment]
That would be no problem at all.

**Comment by presidentbeef** [comment]
I think this is basically covered now.
