### ISSUE TITLE
False positive on redirect using scrubbed params

### ISSUE THREAD

**Issue by arkadyan** [presidentbeef/brakeman#393]
Here's a commit with an example case:
https://github.com/arkadyan/brakeman/commit/6932423c3a5c350f28836aebabf4bb82a04a4124

Taking in params from the user and using them in a redirect, but first stripping them unless they match a value from a defined whitelist.

**Comment by jeremywadsack** [comment]
I've found the the following causes a false positive on redirect. 

```
# app/models/empty.rb
class Empty
end

# app/controllers/empty_controller.rb
class EmptyController < ApplicationController
  def show
    redirect_to Empty.name
  end
end
```

Basically, any method called on a class in the `models` folder causes this error. 

See [this sample rails application](https://github.com/jeremywadsack/brakeman-false-redirect-sample) for a reproduction of the issue.

**Comment by presidentbeef** [comment]
@jeremywadsack that's kind of unrelated to this issue, but in any case I am working on some changes that will prevent that kind of false positive (and a number of others).

**Comment by presidentbeef** [comment]
Brakeman is probably going to continue to warn about methods on models that look like they return URLs for the foreseeable future.
