### ISSUE TITLE
False positive: unsafe reflection of model attribute

### ISSUE THREAD

**Issue by cainlevy** [presidentbeef/brakeman#453]
```
class User < ActiveRecord::Base
  FOO = ['Baz']
  BAR = 'Qux'

  def variations
    User::FOO.first.constantize
    FOO.first.constantize
    User::BAR.constantize
    BAR.constantize
  end
end
```

Of these four `constantize` calls, Brakeman flags only the first as an unsafe reflection. It appears to be because the array's namespace explicitly includes a model name, which fails [`this check`](https://github.com/presidentbeef/brakeman/blob/5d99f32b7d2f016f97b13430330907b5a14f579d/lib/brakeman/checks/base_check.rb#L85).

I reduced this out of a situation very similar to #376.

**Comment by presidentbeef** [comment]
With #855 and #856 Brakeman will now process this to

```ruby
    class User < ActiveRecord::Base
      FOO = ['Baz']
      BAR = 'Qux'

      def variations
        'Baz'.constantize
        'Baz'.constantize
        'Qux'.constantize
        'Qux'.constantize
      end
    end
```

I suppose it could go one step further and turn those into constants...but not sure that will help any.
