### ISSUE TITLE
False positives with nested models

### ISSUE THREAD

**Issue by mastahyeti** [presidentbeef/brakeman#466]
If you define a model like

``` ruby
module Foo
  class File
  end
end
```

`File` will always be seen as a model, even if the call is outside the scope of `Foo`. I spent a few hours on a fix, but it got messy and I gave up.

**Comment by oliverklee** [comment]
@presidentbeef Yes, I get false positives for XSS.

**Comment by oliverklee** [comment]
Should I create a separate ticket for this?

**Comment by presidentbeef** [comment]
Yes, please. We can discuss there.

**Comment by oliverklee** [comment]
Done: #597

**Comment by mastahyeti** [comment]
Closing as stale.
