### ISSUE TITLE
brakeman should not depend upon rails

### ISSUE THREAD

**Issue by ff-apujari** [presidentbeef/brakeman#522]
This requirement may not sound good for all, but I do have right to mention it :) because it is valid for sure, though it might get cancelled

currently brakeman cannot run without a rails app
given a single controller file it cannot work
given simply app/views folder it cannot work

I do have a project repo where I have few the structure like
- apps
  ... few rails apps
- engines
  --- few rails engines
- gems
  -- few private gems

and I want to see a single brakeman report for this whole project ruby/rails code
given this repo path brakeman wont work

so the requirement is, it should identify controllers as _controller.rb, views as .erb etc
and should be able to work with any given path

-3, -4 options can be added if require else it should be with the latest one which is rails 4

Right now, I am able to generate separate reports for separate apps, but it wont work with engines

**Comment by zr2d2** [comment]
I concur, I would like to use brakeman on a CLI application

**Comment by jrmullins** [comment]
+1

**Comment by presidentbeef** [comment]
If you would like Brakeman to work on non-web applications, please explain what type of vulnerabilities you would expect it to find.

**Comment by presidentbeef** [comment]
My suggestion here is the use a combination of these options:

* `--force-scan` to skip checking for an `app/` directory
* `--add-engines-path` to specify where all the Rails apps/engines live
* `--add-libs-path` to specify paths containing any other Ruby files

Results are absolutely not guaranteed.
