### ISSUE TITLE
Reported "file" doesn't exist.

### ISSUE THREAD

**Issue by dylemma** [presidentbeef/brakeman#548]
*Disclaimer: I'm not a Ruby guy, I'm just working on a tool that uses Brakeman's JSON output as an input. I have no affiliation with Redmine, it's just another data set as far as I'm concerned.*

I ran Brakeman on [Redmine](https://github.com/redmine/redmine) and got some output that caught me off guard:

    {
      "warning_type": "Attribute Restriction",
      "warning_code": 19,
      ...
      "message": "Mass assignment is not restricted using attr_accessible",
      "file": "<omitted>/redmine-master/app/models/anonymous_user, attachment, auth_source, auth_source_ldap, board, change, changeset, comment, custom_field, custom_value, document, document_category, document_category_custom_field, enabled_module, group, group_custom_field, issue, issue_category, issue_custom_field, issue_priority, issue_priority_custom_field, issue_query, issue_status, journal, journal_detail, member, member_role, message, news, principal, project_custom_field, repository, repository/cvs, repository/darcs, setting, time_entry_activity, time_entry_activity_custom_field, time_entry_custom_field, time_entry_query, token, user_custom_field, version, version_custom_field, watcher, wiki, wiki_content, wiki_page, wiki_redirect, workflow_permission, workflow_rule, workflow_transition.rb",
      ...
    }

Of note is the mention of `anonymous_user` in the filename. There is no such file in https://github.com/redmine/redmine/tree/master/app/models. There is an `AnonymousUser` class defined in `user.rb`, so I'm guessing that Brakeman is assuming filenames based on the models it detects.

**Comment by presidentbeef** [comment]
Not going to fix this. `--separate-models` is the default now.
