### ISSUE TITLE
Crash: Brakeman fails to generate report

### ISSUE THREAD

**Issue by elisidir** [presidentbeef/brakeman#554]
Brakeman seemed to run successfully until it failed during report generation.  An empty report file was created.  A companion application was scanned without issue.  Brakeman generated the following stack trace.  Please advise how to repair this.  I have a customer waiting; I'd appreciate your help as soon as you can get to it.  Thanks in advance.

C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_html.rb:185:in `with_context': incompatible character encodings: UTF-8 and IBM437 (Encoding::CompatibilityError)
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_html.rb:72:in`convert_warning'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_base.rb:146:in `block in convert_to_rows'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_base.rb:141:in`map'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_base.rb:141:in `convert_to_rows'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_base.rb:128:in`render_warnings'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_base.rb:83:in `generate_warnings'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report/report_html.rb:25:in`generate_report'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report.rb:73:in `generate'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman/report.rb:42:in`format'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:336:in `block (2 levels) inwrite_report_to_files'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:335:in`open'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:335:in `block in write_report_to_files'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:334:in`each'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:334:in `each_with_index'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:334:in`write_report_to_files'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:323:in `scan'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/lib/brakeman.rb:59:in`run'
        from C:/Program Files (x86)/Ruby193/lib/ruby/gems/1.9.1/gems/brakeman-2.5.0/bin/brakeman:78:in `<top (required)>'
        from C:/Program Files (x86)/Ruby193/bin/brakeman:23:in`load'
        from C:/Program Files (x86)/Ruby193/bin/brakeman:23:in `<main>'

**Comment by bf4** [comment]
I've written a pretty extensive test suite around these kinds of encoding failures that pass on both windows and linux and osx.  They're in RSpec-Support, which I extracted as https://github.com/bf4/encoded_string 

This is a super old issue... but if someone wants to tackle it and confirm it's still an issue, take a look at the test suite there
