### ISSUE TITLE
Text output to file cut long lines. 

### ISSUE THREAD

**Issue by yxhuvud** [presidentbeef/brakeman#562]
Limiting the width of tables that are output to terminal width is not very helpful at all when outputting to file. Long class-, model- and template names will crowd out the message about what actually is wrong.

It would be nice to have a way to actually get all information even when using text..

**Comment by gbirchmeier** [comment]
Why does the output care about screen width anyway?  Why not just let the terminal handle line wraps like every other command-line tool?

**Comment by presidentbeef** [comment]
I don't think it's that odd. If you let the terminal wrap the lines, it would look like this, or worse:
![screen shot 2015-05-04 at 1 38 36 pm](https://cloud.githubusercontent.com/assets/75613/7461984/f6fdb344-f262-11e4-9529-020b39fc50f1.png)

If it bothers you, use the option as mentioned above.

**Comment by gbirchmeier** [comment]
I'd rather see that than have everything but the first 80 characters truncated.  I don't want to *not* see things because I happen to be on a narrow-sized terminal.

I just find it to be a weird default, and can't think of any other command-line utility that does its output like this.

**Comment by instantink-brazil** [comment]
I'm there with @gbirchmeier. UNIX command line tools should not format output or even care about terminal width at all, because you can always pipe them to some other tool which should also not care about that and so on. The optional parameter is OK, but should not be the default behavior.

**Comment by dgsprb** [comment]
I'm there with @gbirchmeier. UNIX tools should not format output or even care about terminal width at all. Because you can always pipe them to some other tools which should also not care about that. The optional parameter is OK, but it should not be the default behavior.

**Comment by presidentbeef** [comment]
We'll be adding a new text output format (#914) which will not be truncated and in 4.0 will be the default format.
