### ISSUE TITLE
Rails 4 Mass Assignment False Positives

### ISSUE THREAD

**Issue by ckhsponge** [presidentbeef/brakeman#579]
I'm seeing security warnings and model warnings in a rails 4 app for mass assignment. I believe mass assignment is prohibited in rails 4 by default, however. Am I doing something wrong or should brakeman not be reporting these warnings? Rails 4 does not support attr_accessible so that text should not appear in the warning.

Rails version: 4.1.7
Brakeman version: 2.6.3

+SECURITY WARNINGS+

+------------+----------------------+--------------------+-----------------+--------------------------------------------------------------------------+
| Confidence | Class                | Method             | Warning Type    | Message                                                                  |
+------------+----------------------+--------------------+-----------------+--------------------------------------------------------------------------+
| Weak       | xxxController | create             | Mass Assignment | Unprotected mass assignment near line...

Model Warnings:

+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------------------------------------+
| Confidence | Model                                                                                                                                                     | Warning Type          | Message                                                 |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------------------------------------+
| High       | xxx | Attribute Restriction | Mass assignment is not restricted using attr_accessible |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------------------------------------+

**Comment by presidentbeef** [comment]
I don't see any way of correctly detecting this, sorry. I'm afraid this corner case is going to be left unhandled.
