### ISSUE TITLE
Slim Requirment lower than Rails 4.2

### ISSUE THREAD

**Issue by ramaboo** [presidentbeef/brakeman#601]
Bundler could not find compatible versions for gem "slim":
  In Gemfile:
    brakeman (~> 3.0.0) ruby depends on
      slim (< 3.0, >= 1.3.6) ruby

    slim-rails (~> 3.0.1) ruby depends on
      slim (3.0.0)

If possible this should be updated to use the latest version of slim which is needed for good Rails 4.2 support.

**Comment by cwest** [comment]
I need this so I'm going to give it a whirl.

**Comment by presidentbeef** [comment]
:-/ right after the release...

The main danger here is the output format changing.

**Comment by cwest** [comment]
I'll admit I'm not entirely clear on the implications, however the interfaces seem to be fairly consistent. The primary motivator for going to 3.0.0 on the slim project appears to be the removal of Ruby 1.8.7 support.

**Comment by presidentbeef** [comment]
In case I wonder in the future, slim-rails prior to 3.0.1 did not have support for Rails 4.2 (or at least the dependencies were restricted to < 4.2).
