### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by beanieboi** [presidentbeef/brakeman#609]
hey guys,

could you cut a new release which includes the support for the lastest slim? it's already on master. had some trouble upgrading to Rails 4.2 with the locked down version.

very much appreciate your work! keep on securing Rails! :)
ben

**Comment by presidentbeef** [comment]
Yes, there will be a new release soon.

Sadly, Bundler is not really a good fit for managing dependencies whose dependencies are not really dependencies for the main application. This is like not being able to install Chrome because Sublime Text has a conflicting dependency.

**Comment by beanieboi** [comment]
before https://github.com/presidentbeef/brakeman/commit/2e44182f5c256233df1cc8860720a8f0c4a1b98f you excluded slim 3.x explicitly. 
`s.add_dependency "slim", ">=1.3.6", "<3.0"`

no tool in the world would dare to install slim 3.x, if you block it :)

**Comment by presidentbeef** [comment]
By adding Brakeman to the Gemfile of a Rails application, you are unnecessarily tying the dependencies of the Rails app to Brakeman's dependencies.

I don't blame users for this, though. There is not a good solution available right now. 

Also, "< 3.0" was added when Slim 2.0 came out in case 3.0 broke anything.

**Comment by beanieboi** [comment]
ok, gotcha! :) yeah makes sense to keep it on 2.0 to prevent accidental upgrades :)

**Comment by presidentbeef** [comment]
New release went out yesterday that addresses this issue.
