### ISSUE TITLE
False positive "Render path contains parameter value" despite its verified using lookup_context.find

### ISSUE THREAD

**Issue by pkuczynski** [presidentbeef/brakeman#614]
I am getting false positive security issue reported for following controller method:

```ruby
def index
    @current_page = params[:page] || 'index'

    url      = "manual/#{@current_page}"
    template = lookup_context.find(url).virtual_path

    render template
  rescue
    redirect_to '/manual/index'
  end
end
```

I don't think thats correct, as lookup_context.find should give me fully secure results...

**Comment by presidentbeef** [comment]
Hi Piotr,

Thanks for reporting this.

However, since it is reported as a weak confidence finding, there *is* dynamic content in the path, and Brakeman couldn't detect that `lookup_context` is a model, I don't think we can do much here, sorry :(

**Comment by pkuczynski** [comment]
lookup_context is actually part of the ActionView class from Rails, so it could be detected. Any suggestion how can I avoid this warning?

**Comment by presidentbeef** [comment]
Ah, I didn't know that.

That actually makes it seem more dangerous to me, not less, right?

What is the difference between this and the code below?

```ruby
render "manual/#{params[:page]}"
```

**Comment by pkuczynski** [comment]
As far as I understand lookup_context.find will throw an exception when template is not found. Give me an example how this can be dangerous? My assumption is that Rails protects from reaching out beyond /app/views folder. And in my case I am limiting this further to /app/views/manual...

**Comment by presidentbeef** [comment]
Hi Piotr,

Sorry for the delay, needed to verify.

I tested with with Rails 3.2.13/4.0.3 (sorry, I'm a little behind) and WEBrick/Puma. Both versions of the code (using `lookup_context` or just the string) will happily render files outside of `app/views`, assuming the file type matched any of `[:html, :text, :js, :css, :ics, :csv, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip]`.

You could match the param against a whitelist, you could strip `..` from the param, you could use https://github.com/rkh/rack-protection, or you could find some other way of safely choosing a template based on user input.

I'm not sure that there is an approach that will prevent Brakeman from warning about this, even if you mitigate the problem, though. That's just a Brakeman limitation right now.
