### ISSUE TITLE
CSV reported format broken

### ISSUE THREAD

**Issue by belt-ascendlearning** [presidentbeef/brakeman#615]
If there are no warnings, lib/brakeman/report/report_base.rb -> generate_warning_overview() yields nil
... which breaks in lib/brakeman/report/report_csv.rb -> generate_report()

<code>
lib/brakeman/util.rb:427:in `table_to_csv': undefined method `headings' for nil:NilClass (NoMethodError)
</code>

**Comment by presidentbeef** [comment]
Hi Paul,

Sorry for the trouble. The CSV format is not very well supported, and is mostly intended for dumping into a spreadsheet program.

This issue should be fixed now, though!

**Comment by belt-ascendlearning** [comment]
If I can get the boss to signoff on it, I'll write a json-report parser for cruisecontrol.rb
See: https://github.com/thoughtworks/cruisecontrol.rb/blob/master/lib/brakeman_charts.rb

**Comment by presidentbeef** [comment]
Oh.

:crying_cat_face:
