### ISSUE TITLE
Denial of Service warning after `slice`

### ISSUE THREAD

**Issue by mockdeep** [presidentbeef/brakeman#622]
I think there's a false positive from the Denial of Service rule. The following code does it for me:

```ruby
params.slice(:doc_id, :group_id).symbolize_keys
```

**Comment by presidentbeef** [comment]
Hi Robert,

Yes, I suppose this is a false positive. There are probably a lot of false positives like this for this rule...but I'm not very motivated to fix them because I think "symbol DoS" is kind of lame. That's why it's an optional check now (not run by default).

**Comment by mockdeep** [comment]
Yeah, and with ruby 2.2 it'll be a non-issue since symbols can be garbage collected.

**Comment by presidentbeef** [comment]
No plans to fix this based on the above.
