### ISSUE TITLE
Invalid Signing certificate

### ISSUE THREAD

**Issue by notgeorge** [presidentbeef/brakeman#642]
Attempting to verify the signed bundler install via instructions at http://brakemanscanner.org/docs/install/

Public cert in the repo is:  /CN=justin/DC=presidentbeef/DC=com

Certificate being used during the gem install with MediumSecurity is:  /CN=ryand-ruby/DC=zenspider/DC=com 

This causes the install to fail with an untrusted root cert error.  Has the certificate changed?

**Comment by presidentbeef** [comment]
Yeah, this is confusing.

What happens is that if any dependency has a certificate, then `gem` will try to verify it even with `-P MediumSecurity`. Several of @zenspider's gems have certifcates (like ruby_parser, sexp_processor), so RubyGems wants you to install his certificate, too. I'm honestly not sure how to get that.

A workaround is to install Brakeman normally (to get all dependencies), then uninstall, then install with `-P MediumSecurity`. Not sure how you would do that with Bundler, though.

**Comment by notgeorge** [comment]
Ah the joys of nested dependency checking.  I'll see if I can track down @zenspider's certificate.  Thanks for the quick reply!

**Comment by zenspider** [comment]
My public cert is here: http://www.zenspider.com/~ryan/gem-public_cert.pem

**Comment by presidentbeef** [comment]
Thanks, Ryan.

All you have to do is...

```
gem cert --add <(curl -Ls https://raw.github.com/presidentbeef/brakeman/master/brakeman-public_cert.pem)
gem cert --add <(curl -Ls http://www.zenspider.com/~ryan/gem-public_cert.pem)
gem cert --add <(curl -Ls https://raw.githubusercontent.com/intridea/multi_json/master/certs/rwz.pem)
```

So easy :sob:

**Comment by bf4** [comment]
http://guides.rubygems.org/security/#building-gems

**Comment by presidentbeef** [comment]
@bf4 not sure how that's relevant? The issue here is that even if one gem has clear instructions for installing the certificate, the user needs to track down and install certificates for every signed dependency as well.

**Comment by bf4** [comment]
Basically just explains how to install with `MediumSecurity` via gem and bundler and why it doesn't really matter.  https://github.com/rubygems/rubygems.org/pull/626 would have fixed it. Oh well. And ref: https://github.com/sferik/twitter/issues/536 https://github.com/sferik/twitter/commit/0291149557b625302ea14b2e61290aff132a64d8 and https://github.com/sferik/twitter/issues/536

**Comment by presidentbeef** [comment]
`MediumSecurity` requires that you trust certificates for every signed dependency, which is what we are discussing. I don't think it's unreasonable for people to want some kind of signed package for a security tool, so I don't mind continuing to support it.

In any case, I have updated the documentation with the additional certificates.
