### ISSUE TITLE
Upgrade dependencies; bump gem

### ISSUE THREAD

**Issue by saizai** [presidentbeef/brakeman#644]
@presidentbeef Gems are out of date, which causes dependency issues:
erubis 2.6 vs 2.7.0
highline 1.6.20 vs 1.7.1
multi_json 1.2 vs 1.11.0
ruby2ruby 2.1.1 vs 2.1.3
ruby_parser 3.6.2 vs 3.6.5
sass 3.0 vs 3.4.13

**Comment by presidentbeef** [comment]
Hi Sai,

This is not how gem dependencies work. Brakeman will not cause a dependency issue with any of those gems except highline. Since highline 1.7.1 dropped support for Ruby 1.8.7, I do not plan to make any changes at this time.

**Comment by zenspider** [comment]
They filed a bunch of these, but haven't detailed a single tangible problem. Are these automated?

**Comment by presidentbeef** [comment]
Not sure, but there seems to be a misunderstanding of how gemspecs and dependencies work.

**Comment by saizai** [comment]
@zenspider No, not automated. Just going through my gem dependency tree and trying to notify projects that have outdated requirements. (E.g. other gems require highline 1.7.1, which makes them incompatible.)
