### ISSUE TITLE
Parse error on value ":" (tCOLON)

### ISSUE THREAD

**Issue by liamdawson** [presidentbeef/brakeman#645]
The following line of code causes an issue in brakeman:

    has_many :security_questions, autosave: false

brakeman 3.0.2, ruby_parser 3.6.5

    ruby -c file.rb
    Syntax OK

Unlike similar bugs (https://github.com/seattlerb/ruby_parser/issues/143), it isn't broken over multiple lines.

**Comment by presidentbeef** [comment]
Hi Liam,

I don't think that's the problem:

```
$ irb
1.9.3-p484 :001 > require 'ruby_parser'
 => true
1.9.3-p484 :002 > RubyParser.new.parse "has_many :security_questions, autosave: false"
 => s(:call, nil, :has_many, s(:lit, :security_questions), s(:hash, s(:lit, :autosave), s(:false)))
```

I can't reproduce any issues via Brakeman either.

**Comment by liamdawson** [comment]
Interesting. I commented all the code after the offending line, and it ran fine. I'll see if I can narrow it down. Guessing I should redirect this to the ruby_parser repo?

**Comment by liamdawson** [comment]
Ah, the issue seems to be some regular expressions later in the file.

**Comment by presidentbeef** [comment]
Going to close this, since it's not really about Brakeman.
