### ISSUE TITLE
Method definition with named param causes parse error

### ISSUE THREAD

**Issue by ncri** [presidentbeef/brakeman#654]
example: 

    def method_name a_param, a_named_param: nil

causes: `parse error on value ":" (tCOLON)`

**Comment by presidentbeef** [comment]
Hi Nico,

This parses fine with ruby_parser 3.6.4. What version are you using?

```
$ irb
1.9.3-p484 :001 > require 'ruby_parser'
 => true
1.9.3-p484 :002 > RubyParser.new.parse "def method_name a_param, a_named_param: nil; end"
 => s(:defn, :method_name, s(:args, :a_param, s(:kwarg, :a_named_param, s(:nil))), s(:nil))
```

**Comment by ncri** [comment]
3.6.6. your line works too for me in erb. But i still get the error in the breakman output in a code line exactly like that.

**Comment by presidentbeef** [comment]
Can you run `ruby_parse` or `ruby_parse_extract_error` on the file?

I can't reproduce this issue with just the code above.

**Comment by ncri** [comment]
How to do that? Where to find those methods?

**Comment by presidentbeef** [comment]
Sorry, they are just command line tools installed with ruby_parser.

`ruby_parse your_file.rb`

**Comment by ncri** [comment]
Yep, I can reproduce the error with that:

    ruby_parse app/models/my_model.rb

    # file = app/models/my_model.rb loc = 256
    .../ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error' #<Racc::ParseError: app/models/admin/my_model.rb:12 :: parse error on value ":" (tCOLON)> for app/models/admin/my_model.rb

In line 12 is exactly that method signature (actually with a "self"):

    def method_name self.a_param, a_named_param: nil

However, so far I cannot reproduce it with an isolated code sample, Only with the whole file.

**Comment by ncri** [comment]
Okay, it seems the error message is inaccurate: the error seems caused by a later method with a slightly different signature. Try this:

````
2.2.0 :007 > RubyParser.new.parse "def self.method_name a_named_param: true; end"
Racc::ParseError: (string):1 :: parse error on value ":" (tCOLON)
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1124:in `on_error'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1036:in `block in process'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/nico/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1024:in `process'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1357:in `block in process'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1355:in `each'
	from /Users/nico/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1355:in `process'
	from (irb):7
	from /Users/nico/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
````

**Comment by presidentbeef** [comment]
I opened a ruby_parser issue for this.

**Comment by ncri** [comment]
Thanks!
