### ISSUE TITLE
CSRF False positive

### ISSUE THREAD

**Issue by phene** [presidentbeef/brakeman#656]
## Error
```
protect_from_forgery should be configured with 'with: :exception' near line 12: protect_from_forgery(:with => :handle_unverified_request)
```

## Code
```ruby
protect_from_forgery :with => :handle_unverified_request
```

Changing to `protect_from_forgery with: :handle_unverified_request` does not appear to resolve the issue.

**Comment by presidentbeef** [comment]
What version of Rails is this? As far as I'm aware, `:handle_unverified_request` is not a valid option.

@oreoshake ^

**Comment by phene** [comment]
Using Rails 4.2.1 and we've implemented our own `handle_unverified_request` that overrides the built-in.

**Comment by presidentbeef** [comment]
How are you not getting this error?

`ArgumentError (Invalid request forgery protection method, use :null_session, :exception, or :reset_session)`

Are you adding something to `ActionController::RequestForgeryProtection::ProtectionMethods`?

**Comment by phene** [comment]
My original code does not pass an argument to `protect_from_forgery`, and I just updated it to the value above in an attempt to get brakeman to pass. I've not tried running with the above argument, so it may very well throw that error.

**Comment by presidentbeef** [comment]
I'm pretty sure the application won't call your custom `handle_unverified_request` method. The default in Rails 4 is to replace the session with a null session if you don't pass in any arguments.

See the code [here](https://github.com/rails/rails/blob/e7feaff70f13b56a0507e9f4dfaf3ebc361cb8e6/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L102).

**Comment by phene** [comment]
Because I'm overriding [this](https://github.com/rails/rails/blob/e7feaff70f13b56a0507e9f4dfaf3ebc361cb8e6/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L208), the strategy isn't used.

**Comment by presidentbeef** [comment]
Ah yes upon further testing, overriding that method does work.

Are you defining it in ApplicationController? In that case it is pretty easy to detect and not produce this warning.

**Comment by phene** [comment]
Yes, but it could have easily been defined in a concern applied to ApplicationController
