### ISSUE TITLE
Double equal (XSS) not caught

### ISSUE THREAD

**Issue by cktricky** [presidentbeef/brakeman#661]
Tested using 3.0.3, I did not see a warning about XSS for the double equal operator (which is basically raw):

    <%== user_supplied_input %>

![idk](https://cloud.githubusercontent.com/assets/544667/8021203/379bc952-0c64-11e5-9307-9b5caec4f76b.png)

**Comment by presidentbeef** [comment]
I see it, too. Wonder if something changed...anyway, I'll fix it.

**Comment by cktricky** [comment]
Thanks, and I'm not certain if it _ever_ checked for it btw. I had not tested on previous versions.

**Comment by presidentbeef** [comment]
@cktricky can you check #663 and see if it behaves as expected?

**Comment by cktricky** [comment]
:+1:
