### ISSUE TITLE
False positive on Rails 4 Model.find_by(params_permit(:id))

### ISSUE THREAD

**Issue by halostatue** [presidentbeef/brakeman#669]
I’m getting `Possible SQL injection near line 8: Model.find_by(params.permit(:id))` with the following code:

```ruby
class LikeModelController < ApplicationController
  include LikeableActions
  before_action :require_model

  private

  def require_model
    @entity = Model.find_by(params.permit(:id))
  end
end
```

I’m not quite sure *how* this would be detected as legitimate, but it is legal:

```ruby
ActionController::Parameters.new(id: 3, abc: 1234).permit(:id) => {"id"=>3}
```

The only other alternative is to do one of the following:

```ruby
@entity = Model.find(params.permit(:id)[:id]) # Ugly and throws an exception I don’t want to handle.
@entity = Model.find_by(id: params.permit(:id)[:id]) # Ugly and redundant.
```

If I have multiple parameters that I want to `#find_by`, then I now have a fairly ugly format to deal with.

This is essentially the same as #503, but I am reliably getting this and know how to work around it—but don’t think I should have to.

**Comment by presidentbeef** [comment]
Hi Austin,

You are correct, the use of `permit` makes this safe when normally it would not be (see http://rails-sqli.org/#find_by). I haven't seen anyone talk about using strong parameters this way, but it appears to work.

I'll work on fixing the warning. Thanks!

**Comment by halostatue** [comment]
It was code that surprised me when I saw my team doing it—but it’s not much different than doing the same thing with `update_attributes`, so rather than doing what I had been doing before (same as the second example I declared “Ugly and redundant”.

**Comment by presidentbeef** [comment]
This took way longer to fix than it should have, but it should be resolved now. Let me know if there are other instances where Brakeman is warning on `permit` in SQL and it shouldn't.

**Comment by halostatue** [comment]
OK. I will remove our exceptions that we have recorded and re-test this with an updated Brakeman. Thanks.
