### ISSUE TITLE
Brakeman does not appear to warn on render :inline content

### ISSUE THREAD

**Issue by oreoshake** [presidentbeef/brakeman#672]
I put up an example and a semi-valid failing test case: https://github.com/presidentbeef/brakeman/compare/master...oreoshake:render-inline

`render :inline => "<%= xss.html_safe %>", :content_type => "text/html", :locals => {:xss => params[:xss]}` is XSS but brakeman doesn't seem to catch it.

**Comment by presidentbeef** [comment]
Ah yeah this came up before.

I think I can handle this by treating it like a normal render but the template is from the string...
