### ISSUE TITLE
XSS false positive with link_to decorated object and ternary condition

### ISSUE THREAD

**Issue by riffraff** [presidentbeef/brakeman#683]
I have a Rails 4 app using Draper and Devise, with code in a controller which does something like:

```
@user = (params[:id] ? User.find(params[:id]) : current_user).decorate
````

and a view which does 

```
link_to(@user.name, @user)
```

And I am receiving
```

Unsafe model attribute in link_to href near line 2: link_to((params[:id] ? (User.find(params[:id])) : (current_user)).decorate.name, (params[:id] ? (User.find(params[:id])) : (current_user)).decorate)
```
which, AFAICT, is a false positive as the draper decorator only forwards the call to .to_param which is safe.  Also, hardcoding the value to either `User.find(params[:id]).decorate`  or `current_user.decorate` seems to silence the warning.

The warning also goes away if I replace the ternary condition with an `if-then-else` block like
```
if params[:id]
  @user = User.find(params[:id]).decorate
else
  @user = current_user.decorate
end
```

or if I change the view to explicitly call `user_path(@user)`  for the second argument to `link_to`.
Using a static string instead of `@user.name`  does not seem to affect anything, so it looks like the problem is only specific to the second argument. 

FWIW, I'm using slim for views, but I am not sure if it has anything to do with it. 
`brakeman -v` is  3.0.5, tested with both ruby 2.1 and 2.2 it gives me the same result.

**Comment by presidentbeef** [comment]
My apologies for not even responding here. There's no great way to deal with this, so we'll just not warn about `decorate` if Draper is used.

**Comment by riffraff** [comment]
no need to apologize, and thanks for looking into this!
