### ISSUE TITLE
Too much output

### ISSUE THREAD

**Issue by schmijos** [presidentbeef/brakeman#689]
I'm running *brakeman* locally with a git hook. It generates to much output on every commit. I want my pre-commit reports to be short.

Is it possible to generate less output than generated with the `--summary` parameter? I'm only interested in the output if brakeman returns a non-zero value (with option `-z`) otherwise the outputs can be green dots for each check or just a simple message telling that everything is ok.

**Comment by presidentbeef** [comment]
Hi Josua,

No, there is not currently an option like what you want. I would recommend wrapping Brakeman in another script and modifying the output to your liking.

Here's a Ruby example:

```ruby
#!/bin/env ruby
require 'brakeman'

result = Brakeman.run '.'

if result.filtered_warnings.length > 0
  puts result.report
else
  puts "[Brakeman] No warnings"
end
```

**Comment by schmijos** [comment]
Cool! That's a good idea and absolutely suitable for my needs.
