### ISSUE TITLE
Removing a file access warning

### ISSUE THREAD

**Issue by PragTob** [presidentbeef/brakeman#698]
Hi there and thanks for brakeman,

I get a [File Access](http://brakemanscanner.org/docs/warning_types/file_access/) warning in our ape objep when using `send_file`. That is fine and well and now I tried to fix it by sanitizing the file name like so: `sanitized_file_name =  file_name.gsub(/[^0-9A-z.\-]/, '_')` - with that a path traversal should not be possible anymore.

The object is still tainted, though - as it derived from `params`, so I still get the warning. Is there any way to get rid off it other than explicitly [ignoring false positives](http://brakemanscanner.org/docs/ignoring_false_positives/)?

**Comment by presidentbeef** [comment]
Hi Tobias,

Unfortunately, in cases where there is no obvious Rails way of fixing the problem, Brakeman can't determine that your sanitization is correct/sufficient. However, I consider this to be a scenario in which using the ignore file is the right thing to do.

**Comment by PragTob** [comment]
okay cool, thanks! :)
