### ISSUE TITLE
False positive "Unprotected mass assignment" on Rails 3 using strong params? 

### ISSUE THREAD

**Issue by JustinAiken** [presidentbeef/brakeman#699]
### The Issue:

I'm trying to get a Rails 3.2.x app ready for Rails 4 by adding the strong_params gem and moving models one-by-one to `attr_protected` and using strong params in all their controllers..

I'm getting warnings like:
   `Unprotected mass assignment near line 5: ActivityFeedLike.new(activity_feed_like_params)`

Where the code in question looks like:
```ruby
# Line 5:

@like  = ActivityFeedLike.new activity_feed_like_params

...

private

  def activity_feed_like_params
    params.require(:activity_feed_like).permit :activity_feed_id
  end
```

(Of course, it would be better if that id param was RESTfully got from the parent resource, but fixing one thing at a time) :stuck_out_tongue: 

Should brakeman be warning about 'Unprotected mass assignment' there though?

EDIT - Note - this is happening in other controllers where there's no `_id` type params, I just chose this example since it was the shortest one.

### Versions:
- `rails` - 3.2.22
- `brakeman` - 3.0.5
- `strong_parameters` - 0.2.3

**Comment by presidentbeef** [comment]
Hi Justin,

Did you follow the installation instructions [here](https://github.com/rails/strong_parameters#installation)? Are you including `ActiveModel::ForbiddenAttributesProtection` in the model or calling `ActiveRecord::Base.send(:include, ActiveModel::ForbiddenAttributesProtection)` in an initializer? I don't think just installing the gem is enough.

**Comment by JustinAiken** [comment]
Oooh, derp, you're totally right.  Closing as a bad case of user error.
