### ISSUE TITLE
XSS false positive around helper j

### ISSUE THREAD

**Issue by kbrock** [presidentbeef/brakeman#708]
In haml and erb, it is possible to embed parameters into javascript strings.

Rails provides `j` or `escape_javascript` to properly escape strings.

```html
<script>var h = "<%= j param[:x] %>";</script>
```

Unfortunately, this raises a false positive

from #706

**Comment by presidentbeef** [comment]
This should only raise an error in Rails 2.x. Are you seeing something different?

**Comment by kbrock** [comment]
@presidentbeef Thanks for all your help here

Brakeman detected the following (which is correct):

Rails version: 4.2.3
Brakeman version: 3.0.5

So maybe in trying to simplify the problem, I'm incorrectly stating the problem.  I'll repaste from the other PR

@presidentbeef Thanks for the feedback. I am not sure the best way to add this to the code.

---

[code](https://github.com/ManageIQ/manageiq/pull/4016/files#diff-92237fc7f1a886c82c4758d7b315a979R42):

```haml
  :javascript
    var import_file_upload_id = "#{j(@import_file_upload_id)}";
```

running [brakeman on travis](https://travis-ci.org/ManageIQ/manageiq/jobs/76995654) it raising an XSS warning:

```
Weak
miq_policy/import (MiqPolicyController#import)
Cross Site Scripting
Unescaped parameter value near line 42:
find_and_preserve(Haml::Filters::Javascript.render_with_options("var import_file_upload_
```

**Comment by kbrock** [comment]
are you suggesting making `find_and_preserve` a safe method call?

**Comment by presidentbeef** [comment]
`find_and_preserve` and `Haml::Filters::Javascript.render_with_option` should not be exposed to end users at all.

**Comment by kbrock** [comment]
thanks so much

**Comment by fonji** [comment]
There is still a false positive with coffeescript.
Using [Haml Coffee Assets](https://github.com/netzpirat/haml_coffee_assets), the following code will raise a false positive in a hamlc view file:
```haml
:coffeescript
  import_file_upload_id = "#{j(@import_file_upload_id)}"
```
Should I open a new issue?

ruby 2.1.7
rails 4.1.7
brakeman 3.1.5

**Comment by presidentbeef** [comment]
Yes please.
