### ISSUE TITLE
False positive on ActiveRecord subquery from AR#Relation

### ISSUE THREAD

**Issue by amatsuda** [presidentbeef/brakeman#711]
Brakeman warns `Model.from(Model.all)` as an SQL Injection, but this is of course a safe and supported way of building a subquery from an AR Relation. https://github.com/rails/rails/blob/01598e9/activerecord/test/cases/relations_test.rb#L139-L144

**Comment by presidentbeef** [comment]
I agree, it should not warn on relations.

**Comment by amatsuda** [comment]
@presidentbeef Thanks for treating this issue, but unfortunately #715 does not really fix none of our actual issue.

`Model.from(Model.all)` is just an example of an AR subquery that indeed doesn't mean anything at all.
In our real app, we put something like
```ruby
Model.active.order(created_at: :desc).limit(30)  # active is a named scope
```
in the FROM argument.

**Comment by presidentbeef** [comment]
Ah, okay. It always helps to have the actual code :)

I've whitelisted more methods in #719.
