### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by presidentbeef** [presidentbeef/brakeman#723]
Brakeman's test coverage is surprisingly not too bad, but it could be better! Some of the missing test cases are actually pretty straightforward to cover. Some suggestions are below.

**Improving Coverage**

[Current coverage via Code Climate](https://codeclimate.com/github/presidentbeef/brakeman/coverage?sort=covered_percent&sort_direction=asc).

Easy candidates:
-  ~~[lib/brakeman.rb](https://codeclimate.com/github/presidentbeef/brakeman/coverage/55ff8a70d86bab610f0320da)~~
- ~~[lib/brakeman/options.rb](https://codeclimate.com/github/presidentbeef/brakeman/coverage/55ff8a71d86bab610f03211d)~~

Medium candidates:
- [lib/brakeman/ignore/config.rb](https://codeclimate.com/github/presidentbeef/brakeman/coverage/55ff8a71d86bab610f03213f)
- [lib/brakeman/report/report_table.rb](https://codeclimate.com/github/presidentbeef/brakeman/coverage/55ff8a71d86bab610f032149) (Actually all the low coverage reports are the same issue)
- [lib/brakeman/util.rb](https://codeclimate.com/github/presidentbeef/brakeman/coverage/55ff8a71d86bab610f032154) (Several little missed bits)

**Running Tests**

After forking and cloning your fork of Brakeman, I recommend using rvm and creating a separate gemset for Brakeman with `rvm gemset use brakeman --create`.

Then:
- `gem install bundler` to get Bundler
- Run `bundle` to install dependencies
- Run `rake` to run tests
- Alternatively, use `ruby test/test.rb` to run tests
- Use `ruby test/test.rb --name test_name_here` to run a single test

**Adding/Modifying Tests**

Brakeman uses [test-unit](http://test-unit.github.io/#test-unit). Most of the tests are based around scanning applications in the [test/apps/](https://github.com/presidentbeef/brakeman/tree/master/test/apps) directory and then checking for expected warnings with `assert_warning` or `assert_no_warning`. The test infrastructure and coordination is in [test/test.rb](https://github.com/presidentbeef/brakeman/blob/master/test/test.rb).

The `BrakemanTester::RescanTestHelper` class can be useful for tweaking an existing application without changing the code in `test/apps`. See the [CVE tests](https://github.com/presidentbeef/brakeman/blob/master/test/tests/cves.rb) for an example of using rescanning to test specific versions.

Unless you really need to modify an older application, try to add any new application changes to `test/apps/rails4`. The other applications have too many tests depending on them.

If testing a single component/class, a new test file is probably appropriate, like [CallIndexTests](https://github.com/presidentbeef/brakeman/blob/master/test/tests/call_index.rb).

**Generating Tests**

It is possible (and recommended) to generate tests for new warnings. To do so, use the `test/to_test.rb` script. It takes the same arguments as Brakeman. For example, to generate a set of tests for XSS warnings in the Rails 4 application, you could use `ruby test/to_test.rb apps/rails4 -t CrossSiteScripting`. While this generates the whole test suite, normally all one needs is the test methods themselves to copy and paste into an existing test suite.

**Generating Test Coverage**
- Install simplecov: `gem install simplecov`
- Run the tests (`rake` or `ruby test/test.rb`)
- Open `coverage/index.html`

**More Information**

See the [wiki](https://github.com/presidentbeef/brakeman/wiki/How-to-Report-a-Brakeman-Issue#submitting-a-pull-request) for information about pull requests and a little more on tests.

Feel free to ask questions here or on [Gitter](https://gitter.im/presidentbeef/brakeman#).

**Comment by Zanadar** [comment]
@presidentbeef I'd love to work on this one.  Will hopefully start within the week.

**Comment by presidentbeef** [comment]
@Zanadar Cool! Let me know if you need any help.

**Comment by bethanyr** [comment]
I've started working on increasing test coverage for: lib/brakeman.rb

**Comment by Zanadar** [comment]
@bethanyr Oooh I was just about to start on this when I saw your comment, so thanks for the heads up.  I'll check this issue out in a couple to see where we're at and if there's anything else to pick up.

**Comment by bethanyr** [comment]
@Zanadar - you can definitely pick one of the other files to add coverage for - I was only planning to do lib/brakeman.rb for now. I figured there was enough work for both of us to do :)

**Comment by Zanadar** [comment]
@bethanyr Okay awesome.  I'll pick up work on `lib/brakeman/config.rg` friday.
