### ISSUE TITLE
Blind Redirects From Trusted 3rd Party

### ISSUE THREAD

**Issue by phene** [presidentbeef/brakeman#734]
@presidentbeef - What are your thoughts on allowing/whitelisting blind parameter-based redirects from a trusted 3rd party? Specifically, the trusted 3rd party is sending a successful SSO SAML response and including a `RelayState` parameter to where the user should be redirected.

**Comment by presidentbeef** [comment]
Hi Geoffrey,

I don't think there is a way for Brakeman to detect that type of situation. If you trust the parameter, you can always whitelist it using Brakeman's ignore file.

I'm not entirely clear from your description whether or not I would personally trust it. My understanding of SAML isn't particularly deep, but I would think the URL still needs to be validated at some point.
