### ISSUE TITLE
Possible SQL injection false positive using hash rocket syntax with where

### ISSUE THREAD

**Issue by house9** [presidentbeef/brakeman#738]
Possible SQL injection false positive using hash rocket syntax with `where`

Given the following 5 versions of the same query; 2 of them are flagged as 'SQL Injection' issues.

`#5` is flagged as expected, however `#2` is also flagged and I think it might be a false positive

    # 1
    Widget.where(category: params[:category_filter])

    # 2
    Widget.where('widgets.category' => params[:category_filter]) 

    # 3
    Widget.where("category = ?", params[:category_filter]) 

    # 4
    Widget.where("widgets.category = ?", params[:category_filter])
    
    # 5
    Widget.where("widgets.category = '#{params[:category_filter]}'") 
    
The generated sql for each 

given: `params[:category_filter] = "THE_CATEGORY') OR 1; DELETE from users; --"`

    SELECT "widgets".* FROM "widgets" WHERE "widgets"."category" = 'THE_CATEGORY'') OR 1; DELETE from users; --'
    SELECT "widgets".* FROM "widgets" WHERE "widgets"."category" = 'THE_CATEGORY'') OR 1; DELETE from users; --'

    SELECT "widgets".* FROM "widgets" WHERE (category = 'THE_CATEGORY'') OR 1; DELETE from users; --')
    SELECT "widgets".* FROM "widgets" WHERE (widgets.category = 'THE_CATEGORY'') OR 1; DELETE from users; --')

    SELECT "widgets".* FROM "widgets" WHERE (widgets.category = 'THE_CATEGORY') OR 1; DELETE from users; --')
    
Note that 1 and 2 are exactly the same 

This is on Rails 4.2.1

**Comment by presidentbeef** [comment]
Hi Jesse,

Thanks for reporting this! This bug has probably been there forever. Probably I didn't write a proper test at the time.
