### ISSUE TITLE
False-positive for Redirect check when using Devise current_user helper

### ISSUE THREAD

**Issue by tomekr** [presidentbeef/brakeman#744]
It looks like the same issue that was happening for the XSS link_to check (https://github.com/presidentbeef/brakeman/pull/45#issuecomment-148863250) is happening for CheckRedirect.

```
 Weak       | BarsController | update | Redirect     | Possible unprotected redirect near line 49: redirect_to(current_user.bars.find(+params[:id]+), :notice => "Bar was successfully updated.")
```

When changing `current_user.bars.find(+params[:id]+)` to `Bar.find` the warning goes away.

**Comment by presidentbeef** [comment]
Should be fixed with #749
