### ISSUE TITLE
safe_yaml dependency

### ISSUE THREAD

**Issue by robincurry** [presidentbeef/brakeman#752]
It looks like a recent update created a dependency on safe_yaml, but the dependency may not be strict enough.

![image](https://cloud.githubusercontent.com/assets/6195/10825635/eb895d30-7e33-11e5-9688-3ac51da815d7.png)

We are seeing this because the target app has an older version of safe_yaml (0.9.7) installed, however safe_yaml/load isn't available until safe_yaml 1.0.x. I believe this could be avoided/resolved with an update of the gemspec to specify safe_yaml >= 1.0.0.

**Comment by presidentbeef** [comment]
Hi Robin,

You are correct, thanks for pointing this out.

**Comment by robincurry** [comment]
No prob. Thanks for the quick update!
