### ISSUE TITLE
Highline needs to be at least 1.6.17 to use HighLine.new.terminal_size

### ISSUE THREAD

**Issue by kjg** [presidentbeef/brakeman#761]
`HighLine.new.terminal_size` was first called here https://github.com/presidentbeef/brakeman/commit/532675071f8ff523ca134ef70b92b74ccaa918e1 when highline was pinned to at least 1.6.19.

For some reason the highline dependency was relaxed here: https://github.com/presidentbeef/brakeman/commit/7f3743bdc44140662ff4b29c3962ebb715e6fd25

But the first time `HighLine.new.terminal_size` was available as a public method was in HighLine version 1.6.17 as changed here: https://github.com/JEG2/highline/commit/fc20eae0e420bb1c7eeb9e74991e37902fd01643#diff-f1fa94b772102077ba03cf006fe72638 (Mar 18, 2013) with the release of HighLine 1.6.17 on April 14, 2013

**Comment by presidentbeef** [comment]
Hi Kevin,

Ah, that was my mistake. The dependency was relaxed to allow people to use HighLine 1.7 and later, but I should have specified a minimum version as well.

**Comment by kjg** [comment]
Would `s.add_dependency "highline", ">=1.6.17", "<2.0"` or something similar be what you're looking for?

I see at some point you had highline at at least 1.6.20, so we could use that for the min instead. I'd be happy to make the PR if you'd like.

**Comment by presidentbeef** [comment]
Yes, exactly. 1.6.20 should be the minimum. Thanks!
