### ISSUE TITLE
Literal hash in mass assignment with without_protection = true triggers warning

### ISSUE THREAD

**Issue by jjconti** [presidentbeef/brakeman#769]
In https://carouselapps.com/2015/11/24/using-brakeman/ I comment that Brakeman in triggering a false positive warning when I have this in the code:

    User.new({username: "jjconti", admin: false})

which is a mistake from when I tried to simplify the code for the post. I review Brakeman output and all the warn examples includes the 

    :without_protection => true

parameter, which is documented to trigger a warning.

Now, I've introduced this code to my codebase:

    User.new({username: "jjconti", admin: false}, :without_protection => true)

and it's triggered as a warning. Is this the desire behavior?

**Comment by presidentbeef** [comment]
Thanks for filing an issue. 

If it's a literal hash with no user input then it should be easy to avoid warning. Right now, you are correct it will warn about any mass arraignment with `without_protection: true`.
