### ISSUE TITLE
Brakeman invoked from command line does not load config file

### ISSUE THREAD

**Issue by carmi** [presidentbeef/brakeman#770]
I was investigating some weirdness where when running brakeman from the command line with `bundle exec brakeman -c myconfig.yml` it would respect the settings in myconfig.yml for all options except the `exit_on_warn` option.

Further investigation revealed that the loading of the `options[:config_file]` occurs in Brakeman.run and never propogates back to the bin/brakeman file. So on [line 81 of bin/brakeman](https://github.com/presidentbeef/brakeman/blob/master/bin/brakeman#L81) where it checks if `options[:exit_on_warn]` is present, it only respects this flag being passed in the command line options and not being set in the config file.

This seems like a bug to me - I think if you define exit_on_warn in your config file, then running brakeman from the command line should respect that and exit an error status code if warnings are found.

Before I go off and create a pull request, I wanted to check if this is expected behavior for some reason that I am not thinking of, or if in fact this is a bug?

** Repetition Steps **

With a rails app with warnings, and a config `brakeman.yml` with the following:

```
---
:exit_on_warn: true
:min_confidence: 2
```

Running 

`brakeman -c brakeman.yml; echo $?` will output exit code 0.

But running

`brakeman -c brakeman.yml -z; echo $?` will output exit code 3.

I think these should both return exit code 3.

**Comment by carmi** [comment]
I threw together a rough fix at https://github.com/presidentbeef/brakeman/pull/771 to help demonstrate issue.

**Comment by presidentbeef** [comment]
Yes, definitely a bug. Thanks for reporting!
