### ISSUE TITLE
broaden erubis dependency

### ISSUE THREAD

**Issue by voidus** [presidentbeef/brakeman#775]
To make brakeman more compatible, erubis 2.7.0 should be included in the dependency specification

**Comment by presidentbeef** [comment]
Hi Simon,

The dependency is currently `~>2.6` which will match any 2.x release. If you install Brakeman from scratch it will use Erubis 2.7.0, so it is definitely compatible.

Can you describe the issue you are seeing?

**Comment by voidus** [comment]
Ah, sure. sorry about that. I'll take a look at my problem again
