### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by xj90512** [presidentbeef/brakeman#778]
➜  ~  brakeman --help
/usr/local/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:22:in `<class:Date>': uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:3:in `<class:Parse>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:2:in `<module:SafeYAML>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:14:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/brakeman-3.1.3/lib/brakeman.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/brakeman-3.1.3/bin/brakeman:5:in `<top (required)>'
	from /usr/local/bin/brakeman:23:in `load'
	from /usr/local/bin/brakeman:23:in `<main>'

**Comment by presidentbeef** [comment]
I am not sure why this sometimes happens and sometimes doesn't. It's a known issue with [safe_yaml](https://github.com/dtao/safe_yaml/issues/80) but since it doesn't appear to be maintained I've implemented a workaround.
