### ISSUE TITLE
brakeman.yml app_path configuration for subdirectories

### ISSUE THREAD

**Issue by dblandin** [presidentbeef/brakeman#779]
Hi there. I'm having some trouble understanding the intended behavior for the `app_path` configuration option when an app in a subdirectory is involved.

If I have a brakeman configuration file at `./config/brakeman.yml` in the root directory:

```yml
---
app_path: "./my/sub/app"
```

and I run either:

```bash
$ brakeman
$ brakeman -c config/brakeman.yml
```

The current behavior is to ignore the `app_path` option and run Brakeman on the current directory.

First question: Should the `app_path` option be valid within a `brakeman.yml` configuration file?

If it should be a valid option, we should switch the `app_path` to that value if not present in the CLI arguments.

There is one tricky case which is when the root directory's configuration file points `app_path` to a sub directory which also has a brakeman configuration file at `my/sub/app/config/brakeman.yml`. Would be the desired behavior be to:

1. Ignore the subdirectory's config and use the root directory's config?
2. Ignore the root directory's config (beyond `app_path`) and use the subdirectory's config?
3. Merge the subdirectory's config with the root directory's config?

I think that 1 is easiest to implement at the moment.

Thanks for your help!

**Comment by presidentbeef** [comment]
Hi Devon,

> First question: Should the app_path option be valid within a brakeman.yml configuration file?

Honestly never considered it. If this is related to the Code Climate platform engine then it makes more sense to me for it to be configured at the engine level than as a config file inside the source code to be scanned.

Normal use of Brakeman is to either run it in the root of an application or to pass in the path to the application. It's pretty confusing to run it in a directory and have it actually scan a different directory.

> There is one tricky case which is when the root directory's configuration file points app_path to a sub directory which also has a brakeman configuration file at my/sub/app/config/brakeman.yml.

Yeah let's not have recursive configuration file parsing.

**Comment by dblandin** [comment]
Great, thanks for the feedback.

Sounds like an engine-level `app_path` configuration option, passed through to the Brakeman CLI is the right way to go.

Thanks! :+1:
