### ISSUE TITLE
link_to block treated differently (href warning)

### ISSUE THREAD

**Issue by nruth** [presidentbeef/brakeman#787]
I get a warning – hopefully a false positive – for this code:

```
Unsafe model attribute in link_to href near line 129: link_to(
```

```erb
<% Course.all.each do |course| %>
  <%= link_to(course.name, @display_scopes.merge(course: h(course.name))
) %>
<% end %>
```

but when changing it to this the warning goes away

```erb
<% Course.all.each do |course| %>
  <%= link_to(@display_scopes.merge(course: h(course.name))) do %>
    <%= course.name %>
  <% end %>
<% end %>
```

I'm not entirely sure if the warning is about course.name or `@display_scopes` (which comes from [has_scope](https://github.com/plataformatec/has_scope), and does involve some specific request params.

But it seems strange that moving the name out of link_to's args and into its block stopped the error being reported? I tried h'ing the first argument in the first example's link_to, but no change.

**Comment by presidentbeef** [comment]
Hi Nicholas,

I'm having a hard time reproducing this issue. Brakeman warns about the URL value since Rails will let you use URLs like `javascript:eval('bad stuff')` that introduce an XSS when clicked. Since it looks like you are passing in a scope, this is probably a false positive.

**Comment by nruth** [comment]
Thanks for looking at this. I'll try to create a small (simpler) app that reproduces the issue. I'll close for now as no point cluttering things.
