### ISSUE TITLE
'Filter "foo" is not defined' with custom haml filters

### ISSUE THREAD

**Issue by jdelStrother** [presidentbeef/brakeman#789]
If I've defined a custom haml filter, I get the error `Filter "foo" is not defined`.   Is there any way of configuring/monkeypatching Brakeman to accept `foo` as a regular haml filter?

**Comment by presidentbeef** [comment]
Hi Jonathan,

There's no built-in way of doing it, but if you load your filter into Brakeman then it should work. If you are willing to patch Brakeman, you could try dropping in a `require` [here](https://github.com/presidentbeef/brakeman/blob/master/lib/brakeman/parsers/template_parser.rb#L74).

**Comment by jdelStrother** [comment]
I was hoping to find that, eg, Brakeman might source a `config/brakeman.rb` file from inside that app that it's testing, where I could monkeypatch Brakeman at runtime - partly so I don't have to fork Brakeman, partly so that it works with CodeClimate (who would be running a stock brakeman gem).  As far as I can tell, there's nothing in Brakeman that does so.   Is that an intentional choice, or is it worth discussing as a feature request / PR?

**Comment by presidentbeef** [comment]
It is kind of on purpose. In the past, Brakeman would automatically try to load filters when it encountered this exception. But if you are running Brakeman against untrusted code, that is undesirable behavior.

You could abuse the `--add-checks-path` option to load in arbitrary Ruby code. It will load all `.rb` files in the directory though.

**Comment by jdelStrother** [comment]
> It is kind of on purpose. In the past, Brakeman would automatically try to load filters when it encountered this exception. But if you are running Brakeman against untrusted code, that is undesirable behavior

Fair enough - I suspected that might be the case
