### ISSUE TITLE
Problems when using Ruby 2.3's safe navigation operator

### ISSUE THREAD

**Issue by lucascaton** [presidentbeef/brakeman#796]
By adding a `&.`, aka. **safe navigation operator** (released in [Ruby 2.3.0](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/)), it causes the following error:

`[file] :: parse error on value ":" (tCOLON) | Could not parse [file]>>

**Comment by presidentbeef** [comment]
Hi Lucas, yes RubyParser does not support Ruby 2.3.0 syntax yet. It is brand new after all :)

**Comment by presidentbeef** [comment]
Opened https://github.com/seattlerb/ruby_parser/pull/207 to address this.

**Comment by lucascaton** [comment]
@presidentbeef RubyParser now supports 2.3. syntax, could it get its new version?

Thanks!

**Comment by presidentbeef** [comment]
I'm not sure what you mean. RubyParser hasn't had a new release since October and no updates since you opened this issue.

**Comment by lucascaton** [comment]
@presidentbeef https://rubygems.org/gems/parser/versions/2.3.0.1

**Comment by presidentbeef** [comment]
That's a different project.

**Comment by lucascaton** [comment]
Just realised that, sorry :/

**Comment by rhymes** [comment]
@presidentbeef ruby_parser just released support for 2.3.0 in version 3.8.0 https://rubygems.org/gems/ruby_parser/versions/3.8.0

**Comment by presidentbeef** [comment]
#827

**Comment by presidentbeef** [comment]
Fixed with #827

**Comment by lucascaton** [comment]
Thanks @rhymes and @presidentbeef.
Will you bump `brakeman` version?

Thanks!

**Comment by presidentbeef** [comment]
At some point in the next week, yes. You are welcome to use master in the meantime.

**Comment by lucascaton** [comment]
Cool, thanks again! :smile:

**Comment by presidentbeef** [comment]
For your convenience, I have pushed a pre-release version `3.2.0.pre1`. Please test and let me know if there are issues. Thanks!

**Comment by brettchalupa** [comment]
Just poking my head in here to say that I upgraded to `3.2.0.pre1` to test it, and the safe nav operator does not create a brakeman error now. :ok_hand: 

Thank you for the fix. :smile:

**Comment by presidentbeef** [comment]
@brettchalupa thanks!

**Comment by gkop** [comment]
Using brakeman 3.2.1, ruby_parser 3.8.1, ruby2ruby 2.3.0, I am getting the error `parse error on value ":" (tCOLON)`. The error appears at the first line number in the file where there is a semicolon. Removing the safe navigation operator from the file removes the error.

**Comment by presidentbeef** [comment]
@gkop please open a https://github.com/seattlerb/ruby_parser/ issue with a reproducible test case. I can't reproduce with just the information provided above.
