### ISSUE TITLE
dynamic render path error too aggressive

### ISSUE THREAD

**Issue by KevinColemanInc** [presidentbeef/brakeman#812]
https://github.com/presidentbeef/brakeman/blob/2bd52a02b12efc1c8c8005319d413835ec87c848/lib/brakeman/checks/check_render.rb#L72

I am getting a warning High error warning on this line in my code:

    render params[:action], status: status

I think that this is safe, because rails overrides 'action' parameters with the controller's action method.

see this line:

https://github.com/rails/rails/blob/0450642c27af3af35b449208b21695fd55c30f90/actionpack/lib/action_dispatch/http/parameters.rb#L30

I think that params[:action] and params[:controller] should not trigger a warning.

**Comment by presidentbeef** [comment]
Hi Kevin,

I think you are right. It's no problem to exclude those two keys.
