### ISSUE TITLE
HAML + coffeescript XSS false positive around helper j

### ISSUE THREAD

**Issue by fonji** [presidentbeef/brakeman#813]
#708 still happens using HAML + Coffeescript, which is:
In haml and erb, it is possible to embed parameters into javascript strings.
Rails provides j or escape_javascript to properly escape strings.
```<script>var h = "<%= j param[:x] %>";</script>```
Unfortunately, this raises a false positive when used with haml inside of :coffeescript sections.
There used to be one for :javascript sessions as well, which has been patched by [commit 7446b17](https://github.com/presidentbeef/brakeman/commit/7446b17daf841c6f022ce154262ba21b0fafd77f).

[I wrote a test showing the false positive.](https://github.com/fonji/brakeman/commit/dccabc97c63184b29bdcfcecdb238f8ca80d1c0e)
Edit: please note that the fingerprint in this test is wrong. [I patched it here.](https://github.com/fonji/brakeman/commit/a8004f976a0150b057d56ce0f838c2f8aa40fcc5)

**Comment by presidentbeef** [comment]
Hi Yannick,

Thank you for reporting this and for the test case.

**Comment by fonji** [comment]
That's the least I can do. Thank you for Brakeman!

**Comment by fonji** [comment]
Thank you!
