### ISSUE TITLE
brakeman.ignore is rendered differently each time even if there are no new warnings.

### ISSUE THREAD

**Issue by aurcioli-handy** [presidentbeef/brakeman#824]
This could present unnecessary merge conflicts when using Brakeman in a continuous integration environment.

**Comment by presidentbeef** [comment]
Hi,

Do you mean the ordering of warnings? Something else? There is a timestamp that will change regardless.

**Comment by aurcioli-handy** [comment]
Hello, 

I see. I think it would be helpful if there were an option so that the ignore file only changed when there were new warnings, could be ordered predictably and didn't record timestamps and the like. Otherwise it is difficult to manage on a large repository with many contributors.

**Comment by presidentbeef** [comment]
I don't think it needs to be an option. It can be the default behavior.

**Comment by aurcioli-handy** [comment]
Even better! :+1:

**Comment by presidentbeef** [comment]
By the way, diffing seems to work best with `git diff --patience`.
