### ISSUE TITLE
False positive "Possible unprotected redirect" with params.slice

### ISSUE THREAD

**Issue by dvandersluis** [presidentbeef/brakeman#832]
Consider the following code:

```ruby
redirect_to params.slice(:active_tab, :page)
```

Right now, brakeman reports a "Possible unprotected redirect" for this code, I believe because `only_path` and/or `host` are not specified. However, since slice is specifying exactly which params are being included, I think this should be acceptable as long as `:host` isn't given to slice.

I cannot find a way to get brakeman to accept my intention here.

Furthermore, in my specific case, I'm using my own my own Hash method `compact_slice` (which is essentially a wrapper around `slice(...).compact`, which means my code actually looks like:

```ruby
redirect_to params.compact_slice(:active_tab, :page)
```

which probably is even harder to fix.

**Comment by presidentbeef** [comment]
Hi Daniel,

Thank you for mentioning this. I agree the `params.slice` case is safe and I'll fix that on the Brakeman side. I'm not really sure what to tell you about `compact_slice` though. You can always use `-I` and ignore it.

**Comment by dvandersluis** [comment]
Fair enough about `compact_slice`, I didn't really expect there'd be a solution there. I can get around it if `slice` is allowed, though, so thank you!

**Comment by dvandersluis** [comment]
I don't know if you'd want a separate issue, but the following is the same pattern but gives a false positive XSS warning:

```ruby
link_to 'link', params.slice(:active_tab, :page)
```

**Comment by dvandersluis** [comment]
Is this fixed via #867?

**Comment by presidentbeef** [comment]
No, but I'll try to get this one as well.

**Comment by dvandersluis** [comment]
Thanks!

**Comment by cbusick** [comment]
We have code that looks like:

```
redirect_to(GenerateUrl(params[:site_id])
```
and brakeman is complaining about unprotected redirects as well -- doesn't seem like it should.

**Comment by presidentbeef** [comment]
@cbusick Yes, Brakeman generates a weak warning when user input is sent to a method and the result is used for the redirect. That's not really related to this issue though.

**Comment by presidentbeef** [comment]
@cbusick forgot to mention: if you would prefer not to see warnings about the indirect use of user input, you can use the `--report-direct` option.

**Comment by joevandyk** [comment]
@presidentbeef would doing this still result in the warning?
```
redirect_to(URI.parse(GenerateUrl(params[:site_id])).to_s)
```

(in our case, GenerateUrl looks up the site_id from a configuration file and returns a URL)

**Comment by b264** [comment]
@joevandyk Have you considered using `params[:site_id].to_i` ?  This would ensure the user input was scalar or raise.

**Comment by joevandyk** [comment]
site_id is a string, not an integer. The validation of it is handled by the GenerateUrl mechanism. My question is more how brakeman is determining if the user input isn't considered "safe".
