### ISSUE TITLE
False positive SQL Injection on scope

### ISSUE THREAD

**Issue by dvandersluis** [presidentbeef/brakeman#833]
I have a scope that looks like:

``` ruby
scope :grouped, -> { group(Post[:user_id]) }
```

For some reason it's being flagged as a possible SQL injection; any ideas why?

**Comment by presidentbeef** [comment]
Hi Daniel,

Yes, because `group` accepts arbitrary SQL and `Post[:user_id]` is seen as possible user input from the database. I'm not familiar with this syntax...what does `Post.[]` return? A column?

**Comment by dvandersluis** [comment]
It's from the [`arel_helpers`](https://github.com/camertron/arel-helpers#areltable-helper) gem (it's equivalent to `Post.arel_table[:user_id]`), it does return a column (instance of `Arel::Attribute`).

**Comment by presidentbeef** [comment]
This is fixed with #985
