### ISSUE TITLE
False positive SQL injection using Model defined constant hash

### ISSUE THREAD

**Issue by masonwash** [presidentbeef/brakeman#835]
After upgrading from 3.1.5 to 3.2.1, we are getting multiple false positive Possible SQL injections on code with the following pattern:

Possible SQL injection near line 24: where("projects.archived = #{+Project::ARCHIVE_STATUS[:not_archived]+}")

**Comment by presidentbeef** [comment]
Hi Mason,

Brakeman warns on any cases of string interpolation in SQL queries unless it's clear it is safe. Brakeman is not great at constant lookups. If `Project::ARCHIVE_STATUS` is defined in another file or outside the class where it is used, it probably won't be found.

If you can provide a little more context I might be able to pull the constant in better. This may be similar to #453.

**Comment by masonwash** [comment]
in the Project model, ARCHIVE_STATUS is defined as a hash of constants:

  ARCHIVE_STATUS = {not_archived: 0, user_initiated: 1, account_suspension: 2}

**Comment by masonwash** [comment]
Clearly this is safe, and it seems to me a very clear way of specifying coded values such as status

**Comment by presidentbeef** [comment]
What is clear to a human is not always trivial for a computer program to "understand" :)

**Comment by masonwash** [comment]
I understand.  My problem is that we have brakeman setup as a continuous process under Jenkins, and the latest update of brakeman is causing the process to break.  Either I don't update brakeman or I have to rewrite multiple code sections that are working find and safe.

**Comment by presidentbeef** [comment]
The process I've seen work is this:

* Run `brakeman -I` to generate an ignore configuration, which is committed with the code
* Before updating Brakeman in CI, update and run locally with `-I` and update as needed

That way you avoid testing new Brakeman versions in CI.

FWIW this code would have warned for a long time, it's not a new thing. Probably there was a change in Brakeman which caused this particular code to become visible.

You can expect new and changed warnings when you update Brakeman, especially across minor versions (like 3.1 -> 3.2). If new versions never found new warnings, there wouldn't really be a point in upgrading...

**Comment by masonwash** [comment]
We ended up converting these to "?" substitution using Rails built-in SQL sanitizer.  Thanks for you quick responses.

**Comment by presidentbeef** [comment]
This should be fixed by #855.
