### ISSUE TITLE
Support u alias for url_encode

### ISSUE THREAD

**Issue by alethea** [presidentbeef/brakeman#847]
Currently, using the shorthand [`.u` ](http://ruby-doc.org/stdlib-2.2.4/libdoc/erb/rdoc/ERB/Util.html#method-i-u) alias for [`ERB::Util.url_encode`](http://ruby-doc.org/stdlib-2.2.4/libdoc/erb/rdoc/ERB/Util.html#method-i-url_encode) in views marks escaped model attributes as unsafe XSS, event though `.url_encode` is counted as safe. Would it be possible to include `.u` in the list of ignored XSS methods?

**Comment by presidentbeef** [comment]
Hi Alethea,

Of course, no problem. Thank you for pointing it out.

**Comment by presidentbeef** [comment]
I'm going to see if anyone wants to take this issue on as an easy contribution.

This just involves adding `:u` where `:url_encode` is listed as an ignored method and then adding a couple tests as [documented here](https://github.com/presidentbeef/brakeman/wiki/How-to-Report-a-Brakeman-Issue#submitting-a-pull-request).
