### ISSUE TITLE
stop cutting tables up

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#850]
it's frustrating to run brakeman and then only see half the output ... 
resize terminal and run again ... still missing ...
just print all the output like for example db consoles do
could still show continuation so grepping is easy ...

```
| Foo | Bar | something very long but maybe >>
| Foo | Bar | something very long but maybe |
>     |     | important                     |
```

@presidentbeef

**Comment by grosser** [comment]
`--table-width 999` fixes this ... but should be the default imo

**Comment by presidentbeef** [comment]
If you want details, the text report is not really the best. There simply isn't enough room in the simple table layout. My suggestion is to overhaul it entirely. This applies to #853 as well.

**Comment by grosser** [comment]
I want something that is easy to read on the commandline + copy-pasteable
... so tables are ok ... but maybe simpler to do per issue chunks

Weak: Command injection
Location: app/views/xxcxc
Code: xccxcxcx

like bundle-audit does ...

**Comment by presidentbeef** [comment]
Use `-f plain` for this.
