### ISSUE TITLE
False positive on Rails 4 Model.find_by(params.slice(:id))

### ISSUE THREAD

**Issue by bugzpodder** [presidentbeef/brakeman#866]
Similar to https://github.com/presidentbeef/brakeman/issues/669

2.1.7 :002 > ActionController::Parameters.new(id: 3, abc: 1234).permit(:id, :abc)
 => {"id"=>3, "abc"=>1234}
2.1.7 :003 > ActionController::Parameters.new(id: 3, abc: 1234).slice(:id, :abc)
 => {"id"=>3, "abc"=>1234}

**Comment by presidentbeef** [comment]
Hi Jack,

I'm assuming you mean a mass assignment false positive? What does the code/warning look like? Brakeman wouldn't normally warn about `slice` in mass assignment.

**Comment by bugzpodder** [comment]
Hi, thanks for responding quickly.  Here is the analysis from brakeman, both of which seem to be false positives.  Thank you.

| High       | TestController                    | create                            | Mass Assignment      | Parameters should be whitelisted for mass assignment near line 4: params.slice(:id).permit!                                                                 
| High       | TestController                    | create                            | SQL Injection        | Possible SQL injection near line 3: User.find_by(+params.slice(:id)+)

`
class TestController < ApplicationController

    def create

        User.find_by(params.slice(:id))

       User.new(params.slice(:id).permit!)

       User.find_by(params.permit(:id))

        User.new(params.permit(:id))

    end

end
`

**Comment by presidentbeef** [comment]
Yes, they both look like false positives. Thanks for reporting!
