### ISSUE TITLE
Add a custom error code for "Please supply the path to a Rails application."

### ISSUE THREAD

**Issue by thegranddesign** [presidentbeef/brakeman#869]
Brakeman is a linter.  It scans files and determines if there are errors with those files.

Here are all of the linters I've checked to see if they error out of none of the files they're tasked with linting exist:

* Rubocop
* Reek
* JSCS
* SCSSLint
* HTML Tidy
* ESLint
* JSHint

None of these error out if there is nothing for them to do.

Contrast that with brakeman which returns a status code of `1` in such a case.  I think that brakeman should just exit in that case.

I understand that for backwards compatibility, starting to all of a sudden return `0` when you previously returned `1` might be an issue, however if so, I'd propose a compromise of returning a _new_ error code meaning "Nothing to do".  In bash anything other than `0` is a failure, so returning a `15` would still be a failure, but scripts such as overcommit could know the difference of whether it failed because it found an error or if it failed simply because there was nothing to do.

brigade/overcommit#359

**Comment by presidentbeef** [comment]
Hi,

While I disagree with the premise (I don't think Brakeman is like the other tools listed, as it does not operate on a file-by-file basis), I think it's fine and useful to return a different exit code for this case.

**Comment by thegranddesign** [comment]
@presidentbeef so quick, such wow!  Thank you!
