### ISSUE TITLE
symlinked folders are ignored

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#874]
tried to get a few folders covered by symlinking them, but that did not work ...
copying did though ...
alternatively setting app_root option to multiple folders would also be a nice fix for this usecase

https://github.com/zendesk/samson/pull/960

**Comment by presidentbeef** [comment]
Where did you try symlinking them to?

If I understand your issue correctly, #857 should address this.

**Comment by grosser** [comment]
yes that looks about right and is much cleaner then the copy/symlink hack :D

**Comment by grosser** [comment]
should be solved with configureable engines path ...
