### ISSUE TITLE
Brakeman did not raise warning on eval

### ISSUE THREAD

**Issue by bitops** [presidentbeef/brakeman#886]
Ran this piece of code through brakeman and it did not raise an error. Potential bug?

``` ruby
# url parameter is a string containing the name of a rails named route helper

def add_to_list(name, url = "")
  @list ||= []
  url = url + "(token: '#{params[:token]}')" if params["token"]
  url = eval(url) if url =~ /_path|_url|@/
  @list << [name, url]
end
```

Brakeman version in Gemfile.lock:

```
brakeman (3.0.5)
```

**Comment by presidentbeef** [comment]
Hi Sebastian,

First, you should upgrade Brakeman ;)

Secondly, where is this method defined? Is it in `routes.rb`?

**Comment by bitops** [comment]
@presidentbeef it is defined in `application_controller.rb`.

**Comment by presidentbeef** [comment]
I was never able to reproduce this. Could you provide some example code that demonstrates the issue?

**Comment by presidentbeef** [comment]
Never reproduced.
