### ISSUE TITLE
False positive: "Dangerous Send"

### ISSUE THREAD

**Issue by rbf** [presidentbeef/brakeman#890]
> **Notes:** False positive returned with both `brakeman` `v3.3.0` and `v3.3.1`. Code snippets are simplified for the purpose of this issue.

I had a code with a security issue like follows:

``` ruby
## In users_controller.rb

def index
  if @view = params[:view]
    @users = User.try(@view)
  else
    @users = User.all
  end
end
```

Luckily `brakeman` reported the appropriate [**Dangerous Send**](http://brakemanscanner.org/docs/warning_types/dangerous_send/) vulnerability. I fixed it by adding an `Object#allow` method, which whitelists any object against the provided value or list of values. As per my understanding, following code removes the **Dangerous Send** vulnerability:

``` ruby
## In object_extentions.rb

class Object
  # Returns the object itself if either is equal to the argument or (if the
  # argument is a collection) is contained in the argument. In all other cases
  # it returns nil. Note that therefore this method will always return nil when
  # called on nil itself. If the argument is a collection, it can be anything
  # Enumerable, but usually a constant Set is the most interesting for
  # performance, e.g. ALLOWED_VIEWS = Set['by_id', 'admins']. Similar to Rails'
  # #permit but for all objects.
  def allow(allowed_item_or_items)
    if allowed_item_or_items.is_a? Enumerable
      allowed_item_or_items.find { |item| item == self }
    elsif self == allowed_item_or_items
      self
    end
  end
end

## In users_controller.rb

# Views are scopes of the User model.
ALLOWED_VIEWS = Set[
  'by_id',
  'admins'
]

def index
  if @view = params[:view].allow(ALLOWED_VIEWS)
    @users = User.try(@view.to_sym)
  else
    @users = User.all
  end
end
```

Unless I'm missing something, this code indeed fixes the **Dangerous Send** vulnerability because the value in the `:send` method is effectively whitelisted. However, `brakeman` continues to report the vulnerability. I found out that refactoring the code as follows does remove the warning although the logic remains unchanged.

``` ruby
## In users_controller.rb

def index
  view = params[:view].allow(ALLOWED_VIEWS)
  elsif @view = view.present? ? view : nil
    @users = User.try(@view.to_sym)
  else
    @users = User.all
  end
end
```

Any suggestions? Am I doing something wrong with my first fix, or should `brakeman` properly recognise it as a fix for the **Dangerous Send** vulnerability warning?

Thanks for your comments.

**Comment by presidentbeef** [comment]
Hi,

Your solution looks fine to me. In general, Brakeman doesn't look into methods like `allow`, so it doesn't know what the method does.

What's interesting is that it warns on one version of your code and not the other. I would expect either both or neither. I'll check it out.

**Comment by rbf** [comment]
FYI I just checked it against latest `brakeman v3.3.2` and the false positive is still happening.

**Comment by presidentbeef** [comment]
Brakeman is never going to recognize this particular fix, so you will just have to ignore the false positive.
