### ISSUE TITLE
Suggestion: report obsolete ignored errors

### ISSUE THREAD

**Issue by jcheatham** [presidentbeef/brakeman#893]
It'd be nice to have a flag on brakeman to indicate which issues in config/brakeman.ignore are actively in use.

/cc @grosser

**Comment by presidentbeef** [comment]
Hi Jonathan,

I can't find it where it came from but I have a TODO item for adding an option to prune unused entries from the ignore file. Would that be what you want?

**Comment by grosser** [comment]
Having it prune every time someone runs brakeman is be good enough, ideally
we'd also want to 'fail ci' when an unused ignore is in there just to make
sure it stays clean ...

**Comment by jcheatham** [comment]
Hi, yeah!  Though even if it was just a report of the unused ones, like:

```
+Obsolete Ignore Entries+
> a230e693725d76bf076fc1abaa344c9c43e7364a409e8b82244fa22b85910bc2453d1a4381c10304f0bc2b5ee50cc4b97a54aab805c359880a7acaf3c06dede0
> 022061d678da5806c2e7507479db21d15e9f802c072ea2ddd446bd8d450a810d696366b6a26d667d495eb2a0d46131bbbcb165d473805d1a63ab988ce2187895
```

etc, so that we could manually clear out the backlog periodically would be great.

**Comment by presidentbeef** [comment]
Ability to prune added in #934

**Comment by jcheatham** [comment]
oh snap, forgot I had this other issue.  So yeah, 👍 for listing and 👍 for pruning, great job all around folks!
