### ISSUE TITLE
Undocumented warning type

### ISSUE THREAD

**Issue by vasinov** [presidentbeef/brakeman#898]
When Brakeman checks for hardcoded secrets [1] it creates a warning of type "Authentication". This warning type is not documented [2]. We should probably either change the warning type or document it on the official site.
 
1. https://github.com/presidentbeef/brakeman/blob/master/lib/brakeman/checks/check_secrets.rb
2. http://brakemanscanner.org/docs/warning_types/

**Comment by presidentbeef** [comment]
Hi Vasily,

Thanks for letting me know! It's been added now: http://brakemanscanner.org/docs/warning_types/authentication/
