### ISSUE TITLE
Ability to be more specific about safe methods

### ISSUE THREAD

**Issue by jacobbednarz** [presidentbeef/brakeman#906]
Hey there!
I'm currently combing our codebase using brakeman and I'm marking a few of our methods as safe however I've been pondering the following scenario and would love some more thoughts on it.

Consider we have multiple classes that just happen to have the same method name in them.

```rb
class A
  def do_something
    # i'll do something safe here
  end
end

class B
  def do_something
    # i'll live on the edge and do something shifty here
  end
end
```

If I go ahead and mark `do_something` as a safe method (because I came across it in class A first and understand it's workings) then then would also mark the `do_something` in class B as safe. I'm wondering if anyone else has hit this or came across a better solution to mitigate this problem? Keep in mind, I could be completely abusing the safe methods approach in which case, I'm happy to be told this is wrong 😛 .

**Comment by presidentbeef** [comment]
Hi Jacob,

Yes, that is a possible (though unlikely?) scenario. I'm trying to avoid doing anything further with "safe methods", instead preferring use of the [ignore config](http://brakemanscanner.org/docs/ignoring_false_positives/). This is one reason why. Trying to accurately resolve methods in the code and against a whitelist is difficult. (The other big reason is that's hard to remember to always check the whitelist and different methods are safe/unsafe in different contexts...)

If there are cases that Brakeman can just avoid warning about, that is most preferred of course...

**Comment by jacobbednarz** [comment]
> Yes, that is a possible (though unlikely?) scenario. 

How I wish it didn't exist in our codebase :cry:

>  I'm trying to avoid doing anything further with "safe methods", instead preferring use of the ignore config.

Cool! This sounds like a better approach however it will just require more cleanup for me in the long run. 

Thanks for the speedy response! Closing this one off in favour of the ignore config.
