### ISSUE TITLE
Add new text output format

### ISSUE THREAD

**Issue by presidentbeef** [presidentbeef/brakeman#914]
The current tables output is a little restrictive and often runs off the screen, hiding information. Outputting to a file is ugly.
## Proposal

Phase in a new text output format closer to what [bundler-audit](https://github.com/rubysec/bundler-audit)  or `brakeman -I` shows (with colors of course).

Example:

```
Confidence: High
Category: Dangerous Eval
Message: User input in eval
Code: eval(params[:dangerous_input])
File: app/controllers/home_controller.rb
Line: 40
```
## 4.0

In 4.0 this would become the default output. The table format would still be available.

/cc @grosser @gbirchmeier

**Comment by grosser** [comment]
👍 for nice defaults :)

**Comment by gbirchmeier** [comment]
It took me a while to figure out why you cc'd me -- #562  😄 

Any output that is independent of terminal-width is good by me 👍

**Comment by dgsprb** [comment]
Great news! :+1:

**Comment by presidentbeef** [comment]
First cut of this in #935

**Comment by presidentbeef** [comment]
No one has complained about or provided suggestions for `-f plain` which implements this. (I still plan on making it the default in 4.0).
