### ISSUE TITLE
Can not parse erb that uses ruby 1.9 hash syntax whose value is an if expression.

### ISSUE THREAD

**Issue by dreid** [presidentbeef/brakeman#916]
The following fails with `app/views/bug.html.erb:1 :: parse error on value ":" (tCOLON)`

``` erb
<%= helper(foo: if foo
    1
  else
    2
  end) %>
```

This does not fail:

``` erb
<%= helper(:foo => if foo
    1
  else
    2
  end) %>
```

**Comment by presidentbeef** [comment]
Hi David,

Yes, looks like RubyParser does not support this syntax yet. I'll open an issue.

**Comment by presidentbeef** [comment]
This was fixed with https://github.com/seattlerb/ruby_parser/pull/237 which will be included in the next Brakeman release.
