### ISSUE TITLE
breakeman parse error on value ":" (tCOLON) when using  `only:`

### ISSUE THREAD

**Issue by Kufert** [presidentbeef/brakeman#930]
brakeman 3.3.5

I get an error from brakeman when using the following code:

`  before_filter :set_resources , only: [:show, :create, :index]
`
with error:
`parse error on value ":" (tCOLON)
`
When I change it to 

`  before_filter :set_resources , :only => [:show, :create, :index]
`

It works... both are valid ruby syntax. Any way to make brakeman OK with that?

**Comment by presidentbeef** [comment]
Hi Yaron,

I cannot reproduce this issue. In fact, you can see [one of Brakeman's test apps](https://github.com/presidentbeef/brakeman/blob/5961dab69a54ad2d6ac8cbf0ea4b89b457bc7948/test/apps/rails5/app/controllers/users_controller.rb#L2) has almost exactly the same line of code.

Brakeman uses RubyParser for parsing, and it does not have a problem with this code:

```
2.3.1 :001 > require 'ruby_parser'
 => true 
2.3.1 :002 > RubyParser.new.parse "before_filter :set_resources, only: [:show, :create, :index]"
 => s(:call, nil, :before_filter, s(:lit, :set_resources), s(:hash, s(:lit, :only), s(:array, s(:lit, :show), s(:lit, :create), s(:lit, :index)))) 
```

It may be some code before the line you are showing.

**Comment by Kufert** [comment]
@presidentbeef thanks for the fast response. Thing is that when I change the syntax, breakeman stops complaining about this file, and strat reporting a different file with that syntax...

I also tried deleting all code before that line, now I have this:
```

class HealthRecordsController < ActionController::Base
  before_filter :set_resources , only: [:show, :create, :index]
```

and still get an error for this line. I did try to run that 'ruby_parser' from the console and I did not get any errors.  

Any chance that breakeman is using a different ruby_parser version than the one I get from the console? 

We started having this issues when we upgraded to Rails 4. We did not get this errors before.

**Comment by presidentbeef** [comment]
Can you continue removing (not changing) code in the file until the error goes away?

How are you running Brakeman? From the command line?

**Comment by Kufert** [comment]
I did as you said, and deleted stuff until I found what was the reason for the error.. it wasn't related to that code at all, but to code in the bottom of the file (about ~500 lines after...). This is the breaking code:

```
        result['vaccines'] << {
          vg_name: vg_name,
          has_ice_evaluations: (counts[:has_ice_evaluations] if counts),
          count_has: {
            total_count: counts[:total_count_has],
            ice_valid_count: counts[:ice_valid_count]
          },
          count_required: (counts_required[:count_required] if counts_required),
          all_immunizations_fields: (counts_required[:immunizations] if counts_required),
          immunizations: counts[:immunizations].each_with_index.map{|imm, i| {
            id: imm.id,
            administration_date: imm.administration_date,
            status: if counts[:aggregated_immunizations] && counts[:aggregated_immunizations][i]
                      counts[:aggregated_immunizations][i].any? { |imm| imm.status(ice_warning_suppressions) == 'Not Valid' } ? 'Not Valid' : 'Valid'
                    else
                      imm.status(ice_warning_suppressions)
                    end
          }},
          aggregated_immunizations: counts[:aggregated_immunizations] ?
              counts[:aggregated_immunizations].map{ |arr|
                arr.map{ |imm|
                  {
                      administration_date: imm.administration_date,
                      id: imm.id,
                      vaccine: imm.vaccine,
                      vg_name: imm.vaccine.vaccine_groups.first.name
                  }
                } if arr
              } : [],
          next_dose: (recommendation && forecasts_enabled) ? recommendation.administration_date : ''
        }
```

specifically, if was  

```
status: if counts[:aggregated_immunizations] && counts[:aggregated_immunizations][i]
                      counts[:aggregated_immunizations][i].any? { |imm| imm.status(ice_warning_suppressions) == 'Not Valid' } ? 'Not Valid' : 'Valid'
                    else
                      imm.status(ice_warning_suppressions)
                    end
```

Once I took it out into a method, the error was gone. The code works the same... so I guess this issue can be closed.
Ran from CLI btw. 

Thanks for your help!
