### ISSUE TITLE
check_cross_site_scripting flags Environment Variables as unsafe

### ISSUE THREAD

**Issue by JPrevost** [presidentbeef/brakeman#939]
I've got code like:
```
<%= link_to("Thing", "#{ENV['SOME_URL']}") %>
```

Brakeman flags that as unsafe. That's not coming from a user, but a server admin.

Thoughts on whether this could be detected by brakeman as safe? Thanks!

**Comment by presidentbeef** [comment]
Hi Jeremy,

I cannot reproduce this issue. I am fairly certain Brakeman does not warn about `ENV`. Can you share more about the warning?

**Comment by JPrevost** [comment]
I see it here:

https://codeclimate.com/github/MITLibraries/bento/app/views/search/search.html.erb

**Comment by JPrevost** [comment]
Also, I don't mind doing the legwork on this but wanted to ask for guidance before digging in :)

Thanks!

**Comment by presidentbeef** [comment]
Ah, yes it's warning about `params[:q]`. This will be fixed in #940
