### ISSUE TITLE
SQL Injection false positive with where_values_hash

### ISSUE THREAD

**Issue by JasonBarnabe** [presidentbeef/brakeman#942]
Use of [`where_values_hash`](http://apidock.com/rails/ActiveRecord/Relation/where_values_hash) is causing a false positive in brakeman.
```ruby
class CanadianGroup < Group
  has_many :products,
           -> { where(Product.canadian.where_values_hash) }
end
```
(`Product.canadian` here is a scope.)

**Comment by presidentbeef** [comment]
Hi Jason,

Yes, I'll fix that up soon.
