### ISSUE TITLE
False positive - Render path contains parameter value with checked params through case

### ISSUE THREAD

**Issue by sciamp** [presidentbeef/brakeman#944]
Hi,
I'm running brakeman 3.4.0, here is the code raising the security warning:

```
case params[:switch_case_on_this]
  when "one"
    ...
    render partial: params[:switch_case_on_this], locals: { <some hash depending on params> }
  when "two"
    ...
    render partial: params[:switch_case_on_this], locals: { <some hash depending on params> }
 when ...
 else
   # doin nothing
```

I think this is similar to the issue discussed in [0]. So is it a bug or I'm missing something?

Thanks,
  sciamp

[0] http://stackoverflow.com/questions/11263976/rails-brakeman-warning-dynamic-render-path-false-alarm?answertab=votes#tab-top

**Comment by presidentbeef** [comment]
Hi Alessandro,

Currently Brakeman does not really do much with `case` expressions, but it's on my roadmap to handle code like this.
