### ISSUE TITLE
False positive - Unprotected mass assignment ?

### ISSUE THREAD

**Issue by dvandersluis** [presidentbeef/brakeman#954]
The following code:

``` rb
tag_text = Sanitize.clean(params[:tag].strip)
tag = @user.tags.create(client_id: current_client.id, tag: tag_text)
```

is throwing an Unprotected Mass Assignment warning. My understanding is that that's for cases of creating a record from a hash, a la `User.new(params[:user])`. We're making use of a param here, but not mass assigning anything. Any thoughts?

**Comment by presidentbeef** [comment]
Hi Daniel,

The `create` method can also be used for mass assignment. However, I cannot reproduce this issue. Can you please provide the version of Rails, version of Brakeman, and the whole text of the warning? Thanks!

**Comment by dvandersluis** [comment]
We got it through Codeclimate, so there wasn't any further text. I'm not exactly sure which version of brakeman they're using now. We're using Rails 3.2.22.5.

**Comment by presidentbeef** [comment]
Okay, I was able to reproduce. This is a weak confidence warning because it is possible (in some cases) to mass assign through to a nested model.
