### ISSUE TITLE
How to resolve "unprotected redirect"

### ISSUE THREAD

**Issue by mltsy** [presidentbeef/brakeman#956]
I have an action that redirects to an authenticated S3 URL in order to serve private assets, and the redirect shows up as a security warning:

```
Possible unprotected redirect near line 4: redirect_to(+ClientFile.find(params[:id]).private_url+)
```

`private_url` is a method that gets the authenticated URL from CarrierWave (which constructs it using the filename stored in the database, along with a bunch of config data form the initializer and from S3).  Do you have any ideas about how I might call this to avoid the security warning?

**Comment by mltsy** [comment]
I did figure out a way to avoid the warning:

```ruby
uri = URI.parse(file.private_url)
redirect_to(uri.to_s)
```

Kinda sad though... :crying_cat_face: :wink:

**Comment by presidentbeef** [comment]
Hi Joe,

There isn't really a way to avoid this warning. It is a redirect to an external URL. In your case, it is expected and safe. You can ignore the warning (use `-I` to generate an ignore config file) if you'd like.

**Comment by mltsy** [comment]
Oooh, ignore config file - great idea! :+1:  Thanks.
