### ISSUE TITLE
Unrecognized action on _hamlout: format_script (RuntimeError)

### ISSUE THREAD

**Issue by rhomeister** [presidentbeef/brakeman#961]
I'm getting this error with haml 7c7c169 (4.1.0.beta.1) through 1f7a3b5 (5.0 beta)

```
Processing templates....
brakeman-3.1.4/lib/brakeman/processors/haml_template_processor.rb:59:in `process_call': Error when processing admin/clusters/_form: Error when processing admin/clusters/_form: Error when processing admin/clusters/_form: Error when processing admin/clusters/_form: Error when processing admin/clusters/_form: Error when processing admin/clusters/_form: format_script (RuntimeError)
```

How can I either:
1. Fix the root cause of this problem
2. turn off HAML template processing (I tried --skip-files /app/views and --except HAML)

Thanks

**Comment by presidentbeef** [comment]
Hi Ruben,

To address your specific issue, I would suggest updating to the latest Brakeman (3.4.1) which bundles its dependencies.

However, it would be very useful if you could share a bit of a HAML template that causes the issue so I can fix it for when stable HAML 4.1/5.0 versions come out.

**Comment by rhomeister** [comment]
Hi Justin,

Thanks for your reply. Regarding your suggesting to upgrade, I'm already on 3.4.1. None of the switches to skip or ignore files worked for me.

In answer to your second question, I tried to do the following to diagnose the problem:

1. deleting all haml files -> no errors
2. keeping a single file with text only (no haml): `hello world` -> no errors
3. keeping a single file with a single html tag: `%span hello world` -> no errors
4. keeping a single file with a single html tag with Ruby: `%span= 1 + 1` -> error

Any idea what's going on here?

Thanks

**Comment by presidentbeef** [comment]
Are you *sure* you are on` 3.4.1?` Above it says `brakeman-3.1.4` and if you were running `3.3.0` or newer using the `brakeman` gem then it wouldn't load HAML `4.1.0.beta.1`, it would load the version it has bundled.

In terms of what's going on, it's most likely because HAML `4.1.0.beta.1` changed its output and Brakeman needs to support it.

To skip all views you need the `/` on the end: `brakeman --skip-files app/views/`

**Comment by rhomeister** [comment]
Apologies! Coincidence had it that we were indeed running 3.1.4. I'm experiencing "number dyslexia" or something. I just upgraded and it works fine now.

Again, apologies for wasting your time!

**Comment by presidentbeef** [comment]
Hi Ruben, no worries. It's not a waste of time - now I know to watch out for the next release of HAML (although the last stable release was over a year ago).
