### ISSUE TITLE
Enable --run-all-checks by default

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#969]
I was not aware that we are not running all possible checks ...
I'd suggest flipping this to running all by default and maybe marking the 'Optional' ones as 'Optional: true' in the output or something like that ... maybe for the next major release ...

also the findings should show what check they came from so I can easily disable a complete check I don't like

**Comment by presidentbeef** [comment]
They are optional for a reason: noisy, slow, experimental, etc.

I suggest opening a separate issue for including the check name in the warning information.

**Comment by presidentbeef** [comment]
(By the way, Brakeman Pro does run all checks by default 😉)
