### ISSUE TITLE
alert when using checks that do not exist

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#970]
`brakeman --test Foobar`
and
`brakeman --except Foobar`

should blow up ... this gives a false sense of security

**Comment by presidentbeef** [comment]
I use this pretty regularly for testing so I would rather it didn't blow up.

I suppose it's possible to warn about mismatched options, although all the reports include a list of checks run.

**Comment by grosser** [comment]
How is this useful for testing ?
