### ISSUE TITLE
CSRF protection in API

### ISSUE THREAD

**Issue by ivanovaleksey** [presidentbeef/brakeman#977]
Hi @presidentbeef and @futhr

I just faced with the same issue like #573.
And I saw #611 PR.

One thing I don't understand is where `ActionController::API` is defined within Rails 4?
As far as I know `ActionController::API` introduced in Rails 5.

I have an `ApiController` which is inherited directly from `ActionController::Base`.
And brakeman gives me a warning like:
`'protect_from_forgery' should be called in ApiController near line 2`
For API I don't want `protect_from_forgery` to be called and `ActionController::InvalidAuthenticityToken` exception to be raised.

So what could be a solution for this case?
Call `protect_from_forgery with: :exception` in `ApplicationController`, then inherit `ApiController` from it and call `protect_from_forgery with: :null_session`?

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  ...
end

class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  ...
end
```

Like that?

Thank you.

**Comment by presidentbeef** [comment]
I think that approach is fine. Alternatively, you can skip CSRF protection in `ApiController` entirely with `skip_before_action :verify_authenticity_token`.

**Comment by ivanovaleksey** [comment]
Thank you Justin.
I forgot about `skip_before_action` method.

And what about `ActionController::API` [here](https://github.com/presidentbeef/brakeman/blob/master/test/apps/rails4/app/controllers/application_controller.rb#L1)?
Can you please explain me where does it came from?

**Comment by presidentbeef** [comment]
The Brakeman test apps aren't necessarily working applications. That being said, https://github.com/rails-api/rails-api is available for Rails versions prior to Rails 5. Rails 5 merged in the `rails-api` gem.
