### ISSUE TITLE
check_cross_site_scripting flag a safe link as unsafe

### ISSUE THREAD

**Issue by softmonkeyjapan** [presidentbeef/brakeman#979]
## Context
I have an application that generate some link from an active record object. The links are signed and look pretty much like: 
```
https://domain.com/payment/callback?order_id=378&transaction_id=8657326&user_id=216073&status=success&time=2016-12-30T10:58:27Z&reference=WL0000000221&signature=qRsHl/CCf/7Mtot7w/7tEdLP7IauEn+EsE4YjZLBU1kKY7G4/x2/D6tZEbOVEQcAm61KAO8J1vBQxddgzuqldtxrJ2bFhuIGLNFeAhbRzUG8obqeNKDqiO3aud5kUM1fdKB9qB5GIFeRUFgYx2rKSzAOFHdZb3BEq5W8rPwtxkf33dZ5K4oqdasTNUAVSuKvG9yd5NaOegi/fFVJv20Z1YG9itX3JnV3pmbGWAq73xwKhxlUL33a1oCBf25wkpMe2P8f4fQu7HENMSjfnS33cuYL6sEcOUGU96LFauRrBVdvpMSDA4XX4kiRgCoSa70s/N4+MPWvo1xByQhv4mXtIkMnlE6WL2p2uLD6QtmedShCjIulWaUsjNJupTN6r6U3k4+Z2hiasSY+be5UONA9OgDqzowO12RJmpo1E0Fb3quFGD2F+Uyc7+VR80Hyj9Jg2X5hrqJCdo+8fZ+Z+KxDNe8uesGoSW/reKWab2o1Zpz5a5sxfdLrC5HYJY7KCJCmJT5NrOMSCKjta/h6IhvrfujnyELEhA5uf8GuM4dvUs3VKdTBNW7hqlgnaQxc72Wircs0hUWXScIqupwgE105v41x25QZdh/kzAFZBtnHN6g2LccyOSpuWgoJ/v03kygsRT4hhw/KJvP3G40Pf33dptePfA+1n5OSqk/MCUrMd3Q=
```

I consider those links as safe as they are not generated from a user input. Also, upon record insertion within the database, I do check that all values are the one expected. Here is the related code:

```ruby
def url_params
  {
    order_id:       object.id,
    transaction_id: object.transaction_id,
    user_id:        object.user_id,
    status:         object.status,
    time:           Time.now.utc.iso8601,
    reference:      object.success? ? object.reference : ''
  }
end

def url_to_store
  params    = url_params.to_a.map { |a| a.join('=') }.join('&')
  signature = Shield::Wamland.new(params).signature
  "#{object.referer}?#{params}&signature=#{signature}"
end
```

## Problem
Brakeman is raising a cross site scripting warning (medium) regarding those links:
```
Unsafe parameter value in link_to href near line 23: link_to('My Link', order_token(params[:token]).url_to_store)
```
What's weird about that is the `order_token(params[:token])` which does not exists in my code. Here is how the actual link in the code looks like:
```
= link_to 'My Link', @order.url_to_store
```

Any idea why it is happening or how can I actually fix it? Thanks a lot

**Comment by presidentbeef** [comment]
Hi Loïc,

Brakeman is warning because it looks like user input may be used to set the URL of the link. As for why it shows `order_token(params[:token])`, this value was probably assigned to `@order` in your controller.

In this case it is a false positive and you can [ignore it](http://brakemanscanner.org/docs/ignoring_false_positives/).

**Comment by softmonkeyjapan** [comment]
Thanks a lot for this clarification.
