### ISSUE TITLE
Feature Request: reduce thrashing in brakeman.ignore

### ISSUE THREAD

**Issue by mattyb** [presidentbeef/brakeman#982]
When a new interactive ignore is run, massive diffs can be generated with almost no ignore changes. While some of these are just line number changes, entries are re-ordered, which makes code review very challenging.

A possible solution would be to sort the entries either by `fingerprint`, or by `file` and `line`

**Comment by presidentbeef** [comment]
Hi Matthew,

The entries are sorted by fingerprint, since Brakeman 3.2.0: https://github.com/presidentbeef/brakeman/commit/a64a46d185ca1f0a9bc594d17b01f8cb86713e2a

**Comment by mattyb** [comment]
Thanks! We just noticed this when upgrading from 3.1 to 3.4, so I guess it'll be fixed for our next upgrade!
