### ISSUE TITLE
Error with named params/kwargs that are required, combined with Seattle style (no parens)

### ISSUE THREAD

**Issue by rbatta** [presidentbeef/brakeman#984]
With code that has 
```
def method arg1:, arg2:, arg3:
  # do something
end
```

This throws a brakeman error of: `...parse error on value ":" (tCOLON) | Could not parse...`

After some finagling, we noticed that if we have `arg3: nil` at the end, the error goes away.
We also noticed that if we don't use Seattle-style ruby (and have parens), the error goes away:

`def method(arg1:, arg2:, arg3:)`

We'd like to comply with Seattle style, and have required named params....so reporting this as a bug. 

Ruby parser sees it properly (3.7.3) by saying it's kwargs for each of the arguments.
Brakeman version (3.4.1)

Happy to provide more details if needed.

**Comment by presidentbeef** [comment]
The code above does not appear to be supported by either RubyParser 3.7.3 or 3.8.4.

**Comment by drewish** [comment]
I'm also running into this. I'm not clear if this is a brakeman issue or if @presidentbeef is saying it's an upstream problem?

**Comment by presidentbeef** [comment]
It's an upstream problem in RubyParser.

**Comment by presidentbeef** [comment]
Might be addressed with https://github.com/seattlerb/ruby_parser/pull/254

**Comment by presidentbeef** [comment]
Fixed in RubyParser 3.11.0 and Brakeman 4.2.0.
