### ISSUE TITLE
No routes information in JSON output

### ISSUE THREAD

**Issue by snyff** [presidentbeef/brakeman#989]
When creating a JSON report, the list of routes is not present in the report.

**Comment by presidentbeef** [comment]
Hi Louis,

While I understand why you might want that information, I have given up on accurately determining routes. It's way too dynamic and people do strange things in their routes file.

It would be misleading the include this information. Much better to use `rake routes` if you can.

**Comment by snyff** [comment]
Fair enough,  thanks for the great work :)
