### ISSUE TITLE
error: parse error on value ")" (tRPAREN)

### ISSUE THREAD

**Issue by kbrock** [presidentbeef/brakeman#992]
Hi,

I'm getting the following error and don't know how to work around it. [[ref]](https://travis-ci.org/rubygems/rubygems.org/jobs/198898583)

Ideas on what I can do to work around this? (Or what I am doing wrong?)

Thanks

---

brakeman 3.5.0
rails 4.2.7.1

```erb
<%= link_to("/", :id => "home") do %>
  <span>Link Home</span>
<% end %>
```

produces the error

```
+Errors+

+------------------------------------------------------------------------------------------+----------------------->>
| Error                                                                                    | Location              >>
+------------------------------------------------------------------------------------------+----------------------->>
| rubygems.org/app/views/dashboards/show.html.erb:8 :: parse error on value ")" (tRPAREN)  | Could not parse app/vi>>
```

**Comment by presidentbeef** [comment]
Hi Keenan,

I cannot reproduce this error. It may be related to code above what you have provided.

**Comment by kbrock** [comment]
thanks. will look for better reproducer
